### PR TITLE
fix: upgrade cypress version to 7.x plus test updates

### PR DESCRIPTION
**Pull request by dionizh**
- upgrade cypress version to 7.x
- update default browser to chrome
- fix cypress tests
- GA to be triggered only on production
- update codecov ignore list
- remove travis references
- update to contributing section

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1510)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1510#-:-MXrM6FX9YClLCmy0yMu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1510)* status: all files reviewed, 2 unresolved discussions (waiting on @dionizh)

___
*[CONTRIBUTING.md, line 11 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1510#-MYCoOBF-ZQAphBO1f9o:-MYCoOBGCi4sbRQX8iFY:b-dlxqnt) ([raw file](https://github.com/ocadotechnology/aimmo/blob/0424493912b20dc7c1f5b371ce561cfa0c895240/CONTRIBUTING.md#L11)):*
> ```Markdown
> Check the list selected as ["good first issue" here](https://github.com/ocadotechnology/aimmo/contribute).
> ## Now you want to **test** your changes and **run** the project locally...
> * To work on the project, you can use whichever editor you like. Recommended: [VSCode](https://code.visualstudio.com/) with [black formatter](https://black.readthedocs.io/en/stable/) installed.
> ```

Why'd'you remove IntelliJ :joy: :sob: 
___
*[CONTRIBUTING.md, line 14 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1510#-MYCo_1Z3z2ngwq4wxuQ:-MYCo_1_95gTLAAI2Xhe:bt6omxv) ([raw file](https://github.com/ocadotechnology/aimmo/blob/0424493912b20dc7c1f5b371ce561cfa0c895240/CONTRIBUTING.md#L14)):*
> ```Markdown
> * Follow the [setup guideline here](https://github.com/ocadotechnology/aimmo/blob/development/docs/usage.md)
> * You can test your change by running the test suite: `pytest`
> * Don't forget to add comments if you think they will help other people to understand your code
> ```

Full stop

(sorry) :sweat_smile:

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1510)* status: all files reviewed, 3 unresolved discussions (waiting on @dionizh)

___
*[CONTRIBUTING.md, line 21 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1510#-MYCpMON3loW1wzPtQkN:-MYCpMOO92JCgmm1K6He:bjl07ll) ([raw file](https://github.com/ocadotechnology/aimmo/blob/0424493912b20dc7c1f5b371ce561cfa0c895240/CONTRIBUTING.md#L21)):*
> ```Markdown
> - Your PR should be connected to a corresponding ZenHub issue.
> - All required status checks must pass.
> - We use [reviewable](https://reviewable.io/) for code reviews. Keep an eye on notification from reviewable. You might need to go back, revise your code and push the changes again. Repeat until the PR is accepted.
> ```

notifications (plural)
Reviewable (capital R)

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1510)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[CONTRIBUTING.md, line 11 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1510#-MYCoOBF-ZQAphBO1f9o:-MYEVP6J8RzlWMiLDAkD:b-s6hmao) ([raw file](https://github.com/ocadotechnology/aimmo/blob/0424493912b20dc7c1f5b371ce561cfa0c895240/CONTRIBUTING.md#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why'd'you remove IntelliJ :joy: :sob: 
</blockquote></details>

😂because it needs a license. We're opening this up to external contributors, so I think we shouldn't recommend anything that needs paying (and external contributor wouldn't get ocado infrastructure). Unless Intellij can function perfectly without the license? I'm not super sure which functionality that you use to need the license 🙂
___
*[CONTRIBUTING.md, line 14 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1510#-MYCo_1Z3z2ngwq4wxuQ:-MYEY8u3DQGhKc8YPDdp:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/0424493912b20dc7c1f5b371ce561cfa0c895240/CONTRIBUTING.md#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Full stop

(sorry) :sweat_smile: 
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 21 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1510#-MYCpMON3loW1wzPtQkN:-MYEY9b_EyHFhlV2KTEP:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/0424493912b20dc7c1f5b371ce561cfa0c895240/CONTRIBUTING.md#L21)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

notifications (plural)
Reviewable (capital R)
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1510#-:-MYFAaeP76Ga-l__I9ON:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[CONTRIBUTING.md, line 11 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1510#-MYCoOBF-ZQAphBO1f9o:-MYFALSo7kYnnXb5wNYk:b-z3tbs1) ([raw file](https://github.com/ocadotechnology/aimmo/blob/0424493912b20dc7c1f5b371ce561cfa0c895240/CONTRIBUTING.md#L11)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

😂because it needs a license. We're opening this up to external contributors, so I think we shouldn't recommend anything that needs paying (and external contributor wouldn't get ocado infrastructure). Unless Intellij can function perfectly without the license? I'm not super sure which functionality that you use to need the license 🙂
</blockquote></details>

Nah that makes sense :stuck_out_tongue: I was just being a IntelliJ fanboy. But yes ideally you'd need a license. It still works without one but you don't get all the nice features.

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1510)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1510)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Pull request merged**
