### PR TITLE
feat: block GA if there's no consent

### PR DESCRIPTION
**Pull request by razvan-pro**
# Description

Added `hasAnalyticsCookiesConsent` function which checks for the Analytics consent in OneTrust. This is used around ReactGA calls, blocking them if the consent is false.

## Testing

- [ ] Tested locally

## Checklist

- [ ] No Google Analytics cookies are set if Analytics Cookies consent has not been given.
- [ ] If Analytics Cookies consent has been given, Google Analytics works as before, setting cookies.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)

### CODE REVIEW

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)* status: all files reviewed, 6 unresolved discussions (waiting on @razvan-pro)

___
*[.github/workflows/cicd.yml, line 30 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYK9KJN0etXzMvAPtLr:-MYK9KJN0etXzMvAPtLs:b-wsj2c7) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/.github/workflows/cicd.yml#L30)):*
> ```
> # TODO: remove this after publishing common
> ```
So we have a plan to separate cfl_common and publish it separately?
___
*[example_project/example_project/settings.py, line 105 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYK9ysz0Gx3EulQczEM:-MYK9ysz0Gx3EulQczEN:bg1zt01) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/example_project/example_project/settings.py#L105)):*
> ```
> COOKIE_MANAGEMENT_ENABLED = False
> ```
Is this used somewhere? If it is, can we put a comment of where that is? :slightly_smiling_face: 
___
*[game_frontend/djangoBundler.js, line 45 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKBq-p1FixZRbzrUw5:-MYKBq-p1FixZRbzrUw6:b-7kuc0u) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/djangoBundler.js#L45)):*
> ```JavaScript
>     reactUrl: `react/${reactFileName}`,
>     environment: process.env.SERVER_ENV,
>     nodeEnv: process.env.NODE_ENV,
> ```

Is this not used then at this point?
___
*[game_frontend/public/handlebars_template.html, line 6 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKCfvG7NtT2G7r4Odm:-MYKCfvG7NtT2G7r4Odn:b-8r6gat) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/public/handlebars_template.html#L6)):*
> ```HTML
> 
> <head>
>   {% include "common/onetrust_cookies_consent_notice.html" %}
> ```

I think I'd put a comment here to note that this is located in the portal repo.
___
*[game_frontend/src/index.js, line 60 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKD10B5QCV4MS-JCw_:-MYKD10B5QCV4MS-JCwa:b6vt7bj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/src/index.js#L60)):*
> ```JavaScript
>     timeoutStatus: false,
>     gameLoaded: false,
>     cameraCenteredOnUserAvatar: true,
> ```

I assume your formatter was adding all the extra commas, and you didn't do them manually? In this case the extra commas are a bit odd and unnecessary. I was just working on this file recently and mine wasn't adding the commas. Can you maybe check what happens? I don't think I changed any setting. 
___
*[game_frontend/src/redux/features/Analytics/index.js, line 2 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKBOQw7iUEEiH83Ehu:-MYKBOQw7iUEEiH83Ehv:b-mg9d8z) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/src/redux/features/Analytics/index.js#L2)):*
> ```
> 'C0002')
> ```
Does this ID mean something that we want to make note of in the code?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)* status: 11 of 14 files reviewed, 6 unresolved discussions (waiting on @dionizh)

___
*[.github/workflows/cicd.yml, line 30 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYK9KJN0etXzMvAPtLr:-MYKXbN-AVoCAK_AxvcE:bwn5h8g) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/.github/workflows/cicd.yml#L30)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> # TODO: remove this after publishing common
> ```
So we have a plan to separate cfl_common and publish it separately?
</blockquote></details>

Oh, I was referring to just publish it as we do at the moment - meaning we have to merge/release portal first (which will publish common as well), then we can remove this line :slightly_smiling_face: 

But yes, I think there's also a plan to separate it in the future.
___
*[example_project/example_project/settings.py, line 105 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYK9ysz0Gx3EulQczEM:-MYKZ2L62ly6QWzRJIvz:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/example_project/example_project/settings.py#L105)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> COOKIE_MANAGEMENT_ENABLED = False
> ```
Is this used somewhere? If it is, can we put a comment of where that is? :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[game_frontend/djangoBundler.js, line 45 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKBq-p1FixZRbzrUw5:-MYKYfjT7X5fs-xsP-LJ:b-vdihs0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/djangoBundler.js#L45)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Is this not used then at this point?
</blockquote></details>

Good catch - I tried using it and then forgot to remove :grin: 
___
*[game_frontend/public/handlebars_template.html, line 6 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKCfvG7NtT2G7r4Odm:-MYKY6mHCL05CBvyCxxi:bj9onca) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/public/handlebars_template.html#L6)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

I think I'd put a comment here to note that this is located in the portal repo.
</blockquote></details>

But it's in the common package :slightly_smiling_face: I think we should leave it like this, we know where common is and it should be separate in the future.
___
*[game_frontend/src/index.js, line 60 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKD10B5QCV4MS-JCw_:-MYK_KpR-fzwomBNvK2s:bunyads) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/src/index.js#L60)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

I assume your formatter was adding all the extra commas, and you didn't do them manually? In this case the extra commas are a bit odd and unnecessary. I was just working on this file recently and mine wasn't adding the commas. Can you maybe check what happens? I don't think I changed any setting. 
</blockquote></details>

Yep, I'm using prettier and it added the commas. I think it's expected to do this, I just tried here: https://prettier.io/playground/

Maybe yours is not running properly? I remember changing some VSCode settings to make a formatter work, but I'm not sure if it was this one or the python one.
___
*[game_frontend/src/redux/features/Analytics/index.js, line 2 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKBOQw7iUEEiH83Ehu:-MYKaGVdC7o6pDs1xQRy:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/src/redux/features/Analytics/index.js#L2)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> 'C0002')
> ```
Does this ID mean something that we want to make note of in the code?
</blockquote></details>

Done.

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)* status: all files reviewed, 2 unresolved discussions (waiting on @dionizh and @razvan-pro)

___
*[.github/workflows/cicd.yml, line 30 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYK9KJN0etXzMvAPtLr:-MYKwuyF-X8Byg2yBorf:balabg7) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/.github/workflows/cicd.yml#L30)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Oh, I was referring to just publish it as we do at the moment - meaning we have to merge/release portal first (which will publish common as well), then we can remove this line :slightly_smiling_face: 

But yes, I think there's also a plan to separate it in the future.
</blockquote></details>

I see, so it's a short term TODO, more like a placeholder :slightly_smiling_face:

**Review by dionizh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[game_frontend/src/index.js, line 60 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKD10B5QCV4MS-JCw_:-MYKxwzT3yi8eISZT35H:b-ns4a04) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/src/index.js#L60)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Yep, I'm using prettier and it added the commas. I think it's expected to do this, I just tried here: https://prettier.io/playground/

Maybe yours is not running properly? I remember changing some VSCode settings to make a formatter work, but I'm not sure if it was this one or the python one.
</blockquote></details>

I see, I didn't have 'prettier', just downloaded the plugin for VS code. Do you think we want the trailing commas? Apparently there's an option to set it to none on the playground :grimacing:

**Review by dionizh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[game_frontend/src/index.js, line 60 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKD10B5QCV4MS-JCw_:-MYLIb08CjSxTUQHA2Tf:b-3zzh71) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/src/index.js#L60)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

I see, I didn't have 'prettier', just downloaded the plugin for VS code. Do you think we want the trailing commas? Apparently there's an option to set it to none on the playground :grimacing: 
</blockquote></details>

The option is also available in VSCode plugin :slightly_smiling_face:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[game_frontend/src/index.js, line 60 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1511#-MYKD10B5QCV4MS-JCw_:-MYLNbxOBoiezFufdLoz:bmm7uc1) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bf185884aeece231b97dc04307e8fc693b71c10f/game_frontend/src/index.js#L60)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

The option is also available in VSCode plugin :slightly_smiling_face: 
</blockquote></details>

Yeah, I don't mind the commas - they're probably good as they can be forgotten when copy-pasting for example, better to have them everywhere I think :slightly_smiling_face: 

If there's an option on the playground, we can probably set it in `.prettierrc.json` if we decide on that :slightly_smiling_face:

**Review by dionizh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by dionizh — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
