### PR TITLE
fix: track worksheet usage

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1828)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1828)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`aimmo/views.py` line 223 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1828#-Niu264EBC44tcHhqyIy:-Niu264EBC44tcHhqyIz:bx0q3vs) ([raw file](https://github.com/ocadotechnology/aimmo/blob/ebf3f5eda213c1cd8689c089ef19fa8ce2346231/aimmo/views.py#L223)):*
> ```Python
>             game.save()
> 
>         WorksheetUsage.objects.create(
> ```

This would create a WorksheetUsage object every time someone watches the game = every time any user clicks Play or enters the URL for the game, teachers & students alike. Just double-checking that is what we want (I thought we mainly wanted to just keep track of when a Game changes Worksheet).

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1828)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`aimmo/views.py` line 223 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1828#-Niu264EBC44tcHhqyIy:-Niu4WQnA8-cIPlYwpJT:b-bm09ca) ([raw file](https://github.com/ocadotechnology/aimmo/blob/ebf3f5eda213c1cd8689c089ef19fa8ce2346231/aimmo/views.py#L223)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This would create a WorksheetUsage object every time someone watches the game = every time any user clicks Play or enters the URL for the game, teachers & students alike. Just double-checking that is what we want (I thought we mainly wanted to just keep track of when a Game changes Worksheet).
</blockquote></details>

I'm aware - it was intentional. I want to capture every time someone uses/plays a game/worksheet. This way, we know which are most used worksheets

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1828)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1828#-:-Niu54en9RyJ4ZDVJS6x:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1828)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
