### PR TITLE
fix: load correct worksheet in aimmo-game

### PR DESCRIPTION
**Pull request by razvan-pro**
Because of Agones changes, aimmo-game doesn't load the correct worksheet ID at the moment. This is fine for now as worksheets 1 and 2 have the same data, but it will be needed for the third one which will have different properties.

Note this won't work if the game worksheet is changed after the game is running - we will fix this at a later stage.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1476)

### CODE REVIEW

**Review by dionizh — CHANGES_REQUESTED** [review]
Did the pip files change just because of the python version update to 3.7 or is there something else? 

> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1476#-:-MUy8DEF-_stEPjsWHWz:b8ooj40)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

___
*[aimmo-game/simulation/avatar/avatar_manager.py, line 13 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1476#-MUy6rmv-__OPLUH6B1R:-MUy6rmv-__OPLUH6B1S:b-bw0tev) ([raw file](https://github.com/ocadotechnology/aimmo/blob/fc9ff83bb45a4bc4409a19e44f03ca0bd8568787/aimmo-game/simulation/avatar/avatar_manager.py#L13)):*
> ```
> WorksheetData = None
> ```
Might be opening a can of worms, but I like the convention of no space for default parameter. What do you think?
___
*[aimmo-game/simulation/worksheet/__init__.py, line 2 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1476#-MUxrMNv9mc5KH8XUu00:-MUxrMNv9mc5KH8XUu01:b3tsr7u) ([raw file](https://github.com/ocadotechnology/aimmo/blob/fc9ff83bb45a4bc4409a19e44f03ca0bd8568787/aimmo-game/simulation/worksheet/__init__.py#L2)):*
> ```
> from .worksheet import WorksheetData
> __all__ = ["WorksheetData"]
> ```

can we empty this file?

**Review by dionizh — COMMENTED** [review]
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1476)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

**Review by razvan-pro — COMMENTED** [review]
The one in aimmo-game yes. For the other I ran `pipenv lock` to update it :slightly_smiling_face:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1476#-:-MUyE4xZ2h_b7SfdI1iO:b-leu8t0)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @dionizh and @razvan-pro)

___
*[aimmo-game/simulation/avatar/avatar_manager.py, line 13 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1476#-MUy6rmv-__OPLUH6B1R:-MUyDBEMExoagDIu_KOG:b-r2luby) ([raw file](https://github.com/ocadotechnology/aimmo/blob/fc9ff83bb45a4bc4409a19e44f03ca0bd8568787/aimmo-game/simulation/avatar/avatar_manager.py#L13)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> WorksheetData = None
> ```
Might be opening a can of worms, but I like the convention of no space for default parameter. What do you think?
</blockquote></details>

Formatted with black which seems to like spaces :slightly_smiling_face: I'll go with black :slightly_smiling_face: 
___
*[aimmo-game/simulation/worksheet/__init__.py, line 2 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1476#-MUxrMNv9mc5KH8XUu00:-MUyDktZ4IS4wIxxGnrC:b-kryun6) ([raw file](https://github.com/ocadotechnology/aimmo/blob/fc9ff83bb45a4bc4409a19e44f03ca0bd8568787/aimmo-game/simulation/worksheet/__init__.py#L2)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> from .worksheet import WorksheetData
> __all__ = ["WorksheetData"]
> ```

can we empty this file?
</blockquote></details>

Technically yes, but then we'd have to import from `simulation.worksheet.worksheet` instead :slightly_smiling_face: Maybe I should add `get_worksheet_data` here as well? :thinking:

**Review by dionizh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1476)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @dionizh and @razvan-pro)

___
*[aimmo-game/simulation/worksheet/__init__.py, line 2 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1476#-MUxrMNv9mc5KH8XUu00:-MUyMEug2cRyVeLP5gIB:b-x1o31x) ([raw file](https://github.com/ocadotechnology/aimmo/blob/fc9ff83bb45a4bc4409a19e44f03ca0bd8568787/aimmo-game/simulation/worksheet/__init__.py#L2)):*
For me I prefer `__init__.py` empty as much as possible, so it's one less file to check and modify 🙂. I saw that at the other places you import as:
> ```
> from simulation.worksheet import WorksheetData
> from simulation.worksheet.worksheet import get_worksheet_data
> ```
So maybe we can keep it consistent and simple, so both import from simulation.worksheet.worksheet then empty the `__init__.py` as you already changed the convention a bit 😁? But it's not a biggie if you just wanna leave it.

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1476)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @dionizh and @razvan-pro)

___
*[aimmo-game/simulation/worksheet/__init__.py, line 2 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1476#-MUxrMNv9mc5KH8XUu00:-MUzyV0P3d4zjiAnq_RJ:bf5j63x) ([raw file](https://github.com/ocadotechnology/aimmo/blob/fc9ff83bb45a4bc4409a19e44f03ca0bd8568787/aimmo-game/simulation/worksheet/__init__.py#L2)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

For me I prefer `__init__.py` empty as much as possible, so it's one less file to check and modify 🙂. I saw that at the other places you import as:
> ```
> from simulation.worksheet import WorksheetData
> from simulation.worksheet.worksheet import get_worksheet_data
> ```
So maybe we can keep it consistent and simple, so both import from simulation.worksheet.worksheet then empty the `__init__.py` as you already changed the convention a bit 😁? But it's not a biggie if you just wanna leave it. 
</blockquote></details>

Agreed :grin:

**Review by dionizh — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1476#-:-MV0nlkw0nXcP9JQ3czT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
