### PR TITLE
Remove manual deploy script from aimmo

### PR DESCRIPTION
**Pull request by OlafSzmidt**

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Done pushed and working now @mrniket. We can move on with this

**Comment by OlafSzmidt** [comment]
Force pushed back to the previous commit, making the other PR now ;)

**Comment by mrniket** [comment]
We might be able to delete the ingress yaml in this PR as well

**Comment by OlafSzmidt** [comment]
We need `ingress.yaml` and `rc-game-creator.yaml` for `minikube.py`.

**Pull request merged**
