### PR TITLE
Add eslint to codeclimate

### PR DESCRIPTION
**Pull request by OlafSzmidt**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/640)

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Prefixing the title as WIP because eslint examines all files right now. We need to exclude more paths to get a more accurate report.

... And then maybe fail the PR via github settings if codeclimate complains?

**Comment by mrniket** [comment]
I think we need to only lint the files in game_frontend src/ with the .eslintrc.json config

to fail the build we could just put `node node_modules/eslint/bin/eslint.js src/` in the test phase in travis?

---

Review status: 0 of 1 files reviewed, all discussions resolved (waiting on @OlafSzmidt)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/640#-:-LFqQbThA8Gf3zrZBQhl:bnsr5ee)*

**Comment by OlafSzmidt** [comment]
Yep. We can exclude paths but for the whole config. I still haven't looked into if we can config the eslint plugin to exclude paths separately from other plugins :/ Busy with #616

---

Review status: 0 of 1 files reviewed, all discussions resolved (waiting on @OlafSzmidt)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/640#-:-LFqaq919vqvhRN255u_:b-vqjqly)*

**Comment by OlafSzmidt** [comment]
Added a `eslintignore` file. Ready to review now

**Pull request merged**
