### PR TITLE
Move worker creation logic from WorkMangers to Worker

### PR DESCRIPTION
**Pull request by SuperMonanana**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/997)

### CODE REVIEW

**Comment by SuperMonanana** [comment]
> > Reviewed 2 of 6 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/997)_ status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @SuperMonanana)
> 
> _[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-LZiNkKA7dN0tizCxHzG:-LZiNkKA7dN0tizCxHzH:bqzoz9s) (no related file):_
> In the `service.py` in `create_runner`, the `GameRunner` currently asks for a local or Kubernetes worker manager, however as I understand it these have been changed to workers, should the `GameRunner` be changed to reflect this?
> 
> _[aimmo-game/simulation/worker_managers/local_worker_manager.py, line 24 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-LZiOU5uCURKCx0zrah9:-LZiOU5uCURKCx0zrahA:bk5hjjq) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9a888269d41433c5271b0c4f115342d96940796e/aimmo-game/simulation/worker_managers/local_worker_manager.py#L24)):_
> 
> > ```python
> >     def __init__(self, *args, **kwargs):
> >         self.workers = {}
> > ```
> 
> I believe the `worker_manager` already contains a dictionary of `player_id_to_worker` objects, so would this dictionary still need to be here since it's not managing workers anymore?

You are right. It seems not necessary to be here anymore. Will remove it!

**Comment by SuperMonanana** [comment]
I've moved the creation logic to _init_ of the worker. Please kindly review when you have time:)

**Comment by SuperMonanana** [comment]
> > _[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/997)_ status: 14 of 17 files reviewed, 4 unresolved discussions (waiting on @mrniket and @SuperMonanana)
> 
> _[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_gBWC_1yjZuWJnT0d6:-L_gBWC_1yjZuWJnT0d7:b3kro) (no related file):_
> I
> 
> _[aimmo-game-worker/Dockerfile, line 13 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_gBysf4oFj4D5T2vg6:-L_gBysf4oFj4D5T2vg7:b-4i464w) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9a888269d41433c5271b0c4f115342d96940796e/aimmo-game-worker/Dockerfile#L13)):_
> 
> > ```dockerfile
> > FROM base as runner
> > ENV WORKER_MANAGER=kubernetes
> > ```
> 
> I think we need to change the `WORKER_MANAGER` env variables inside of the `aimmo-game-creator/Dockerfile` and `aimmo-game/Dockerfile`
> 
> _[aimmo-game/simulation/workers/worker.py, line 22 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_gFY4X7ot4dKxXwlVy:-L_gFY4Y9MboiXiaZGWl:b-ces84r) ([raw file](https://github.com/ocadotechnology/aimmo/blob/30ebcad2d237e5933bc221e9a607d034af489ac2/aimmo-game/simulation/workers/worker.py#L22)):_
> 
> > ```python
> >     def _create_worker(self):
> >         NotImplemented
> > ```
> 
> can we raise a NotImplementedError here?
> 
> ```python
> raise NotImplementedError
> ```

Thanks Niket, I've resolved these issues.

**Comment by SuperMonanana** [comment]
> > Reviewed 3 of 16 files at r2, 5 of 5 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/997)_ status: all files reviewed, 5 unresolved discussions (waiting on @SuperMonanana)
> 
> _[aimmo-game/simulation/worker_manager.py, line 72 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_lWNUm-bcsc16a_-JB:-L_lWNUm-bcsc16a_-JC:buztu5a) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/worker_manager.py#L72)):_
> 
> > ```python
> >             worker = self.player_id_to_worker[player_id]
> >             del worker
> >             worker.remove_worker()
> > ```
> 
> We need to put `worker.remove_worker()` before we delete it
> 
Yes, you are right, will change it.

> _[aimmo-game/simulation/workers/kubernetes_worker.py, line 97 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_lkmwx3tZYcEIn119v:-L_lkmwx3tZYcEIn119w:b-bgaiff) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/workers/kubernetes_worker.py#L97)):_
> 
> > ```python
> >         raise EnvironmentError('Could not start worker %s.' % player_id)
> > 
> >     def _create_worker(self, player_id):
> > ```
> 
> this `player_id` is now a property of the `KubernetesWorker` and is passed into the `__init__` method instead
> 
Yes, sorry I forgot to remove it, will clean it for `_remove_worker` and `local_worker` as well.

> _[aimmo-game/simulation/workers/local_worker.py, line 23 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_liCUfBs-v6bhF1hEw:-L_liCUfBs-v6bhF1hEx:bn1jiuw) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/workers/local_worker.py#L23)):_
> 
> > ```python
> >     def __init__(self, *args, **kwargs):
> >         self.game_id = os.environ['GAME_ID']
> >         self.port_counter = itertools.count(1989 + int(self.game_id) * 10000)
> > ```
> 
> Since there is now one instance of this `LocalWorker` class for each worker, this port counter needs to be shared across instances to make sure the ports it generates are unique. Not quite sure about the best way to do this, maybe we can define something at the module level at the top of this file?
>
Well, i guess it's hard to move it to the top of the file, because we need the game_id. Maybe move it to `worker_manager` and pass it when worker is instantiated?

> _[aimmo-game/simulation/workers/local_worker.py, line 37 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_li8Fs7RHqY0qgpo8O:-L_li8Fs7RHqY0qgpo8P:ba2r3a) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/workers/local_worker.py#L37)):_
> 
> > ```python
> >                 'environment': {}
> >             }
> >         data_url = 'http://{}:{}/player/{}'.format(self.host, self.port, self.player_id)
> > ```
> 
> I think this needs to be `port` and not `self.port`?

Actually, I'm confused about it. It was `self.port` in the original `local_worker_manager` which should be from `worker_manager`? Do you want that port number here?

Also I've bumped the version in `version.txt`

**Comment by mrniket** [comment]
FYI, It might be easier to have this conversation in reviewable 😅 

[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/997)

I'll copy over your replies onto there :)

**Comment by SuperMonanana** [comment]
Sorry I've never used this before, and I didn't find how to reply

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/workers/local_worker.py, line 23 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_liCUfBs-v6bhF1hEw:-L_moSSzAn_Jcxm8IuS6:bh58m81) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/workers/local_worker.py#L23)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

> Well, we could do that, but we need to move game_id to the top of this file as well then?

Yeah, that's why I'm not quite sure how to do this one, perhaps something like this just above the class?

```python
port_counter = itertools.count(1989 + int(os.environ['GAME_ID']) * 10000)
```
</blockquote></details>

I tried this way, but the problem here is I guess we can't reference os env variables at the module level. Can we define it in WorkerManager?

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/worker_manager.py, line 72 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_lWNUm-bcsc16a_-JB:-L_n8vyR6kZLDclKUWlS:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/worker_manager.py#L72)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

We need to put `worker.remove_worker()` before we delete it
</blockquote></details>

Done.

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/workers/kubernetes_worker.py, line 97 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_lkmwx3tZYcEIn119v:-L_n94kl6yDFouX1BbKc:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/workers/kubernetes_worker.py#L97)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

this `player_id` is now a property of the `KubernetesWorker` and is passed into the `__init__` method instead
</blockquote></details>

Done.

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/workers/local_worker.py, line 23 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_liCUfBs-v6bhF1hEw:-L_qy3V-17-Ut2idd2TS:b-vuyg15) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/workers/local_worker.py#L23)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

We could, but the ports only need to be generated this way with the local worker so I would prefer to keep this logic in there. 

I had a go with putting it at the module level and it seemed to work locally? I made a branch here:

https://github.com/mrniket/aimmo/tree/issue-757/aimmo-game/simulation/workers
</blockquote></details>

Well perhaps I did something wrong when running tests, but when I ran tests locally, I got the following error: 
```tests/test_service.py:3: in <module>
    import service
service.py:19: in <module>
    from simulation.game_runner import GameRunner
simulation/game_runner.py:14: in <module>
    from simulation.worker_manager import WorkerManager
simulation/worker_manager.py:9: in <module>
    from simulation.workers import WORKER
simulation/workers/__init__.py:2: in <module>
    from .local_worker import LocalWorker as _LWorker
simulation/workers/local_worker.py:12: in <module>
    port_counter = itertools.count(1989 + int(os.environ["GAME_ID"]) * 10000)
../../../../.local/share/virtualenvs/aimmo-game-kEBaJu-A/lib/python3.6/os.py:669: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'GAME_ID'```
```

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/workers/local_worker.py, line 37 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_li8Fs7RHqY0qgpo8O:-LaR0hvT4hd7gQH_h6iQ:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/workers/local_worker.py#L37)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

> Actually, I'm confused about it. It was self.port in the original local_worker_manager which should be from worker_manager? Do you want that port number here?

Ah, you are right it is confusing! I got confused also :confounded: 

The `port` is the `worker_port`, that is the port of the worker container/pod. 

The `self.port` is the `game_port`, that is the port of the game container/pod. Previously this game from the `WorkerManager` classes, (maybe we should rename this `game_port`). It is represented by the `EXTERNAL_PORT` environment variable


</blockquote></details>

Done.

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/workers/local_worker.py, line 23 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_liCUfBs-v6bhF1hEw:-LaREGZXDJW594w_LmeG:b-t7sbb6) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/workers/local_worker.py#L23)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Ah I see, it can't find a GAME_ID because it is not set for each test. Perhaps a default value for the GAME_ID could solve this?

```python
os.environ.get('GAME_ID', 0) # 0 is the default value here
```
</blockquote></details>

Yes it solves the problem! Thanks!

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/workers/local_worker.py, line 23 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_liCUfBs-v6bhF1hEw:-LaREQUz-kJWldO8f7gf:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/workers/local_worker.py#L23)):*
<details><summary><i>Previously, SuperMonanana wrote…</i></summary><blockquote>

Yes it solves the problem! Thanks!
</blockquote></details>

Done.

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/workers/worker.py, line 13 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_qxDNg9fsBhDr8HwDD:-LaREY1MCn8fEARupVty:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/6ff0805bd24eabeef0504d00e5650ae913a0c3cf/aimmo-game/simulation/workers/worker.py#L13)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

commented out line
</blockquote></details>

Done.

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/worker_manager.py, line 59 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-LaF4cdKBHKdJFfoJquJ:-La_-r408z6PPmKkGXY9:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/6ff0805bd24eabeef0504d00e5650ae913a0c3cf/aimmo-game/simulation/worker_manager.py#L59)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

this is my mistake, I didn't mean to comment this out :sweat_smile:  this was for testing, we should discard this change
</blockquote></details>

Done.

**Comment by SuperMonanana** [comment]
*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-La_0bYDErlzEiCKrkrk:-La_0bYDErlzEiCKrkrl:bd9eaul) (no related file):*
I've always got the following error when I run the test:
 ```docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/aimmo-2-worker-1" is already in use by container "9b9e25fde2aa3c3fd5dcde453cdf27abbae85b2ddd44bc8c72a104945ae921cd". You have to remove (or rename) that container to be able to reuse that name.")```
Does that mean we need to clean the test context?

---

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/tests/test_simulation/workers/test_local_worker.py, line 26 at r8](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-Laa1j5aD8X7Qr06w52r:-LapBWvh31jDIleQobrX:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a6b40650d27acb49439d53e54c96a58716fbe1f4/aimmo-game/tests/test_simulation/workers/test_local_worker.py#L26)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

I think the code existing test here has got the correct port numbers and the code is correct but because the port_counter is initialized at the module level the `GAME_ID` is  still zero (hence the small numbers) 

It also means there is a shared state between tests which could cause an issue if we add more tests/if they run in a different order. We might need a way to "reset" the port counter with a function maybe?

in `local_worker`:

```python
global port_counter

def init_port_counter():
    port_counter = itertools.count(...)

init_port_counter()
```

I think that might work :crossed_fingers: 

</blockquote></details>

Done.

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/worker_manager.py, line 59 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-LaF4cdKBHKdJFfoJquJ:-LayxROf-Xw6TmMNhFV7:b4g5kyz) ([raw file](https://github.com/ocadotechnology/aimmo/blob/6ff0805bd24eabeef0504d00e5650ae913a0c3cf/aimmo-game/simulation/worker_manager.py#L59)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Not done? I think this should use the

```python
with futures.ThreadPoolExecutor() as executor:
    results = executor.map(func, iterable_args)
```

Maybe my reviewable is not updating correctly though :/
</blockquote></details>

Oh I haven't pushed push the change...sorry for that

**Comment by SuperMonanana** [comment]
*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-La_0bYDErlzEiCKrkrk:-Lazp2JR-Lm_-JSii05n:b8lomji) (no related file):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Copying here for reference:

I found the problem, when we removed the worker_manager parameter from the GameRunner, the tests started using the real one instead of the `ConcreteWorkerManager` (a worker manager for the tests) which doesn’t use docker.

We should be able to solve this by adding back the ability to inject the worker_manager_class to the game runner:

```python
class GameRunner:
    def __init__(self, worker_manager_class = WorkerManager, game_state_generator, django_api_url, port):
        super(GameRunner, self).__init__()

        self.worker_manager = worker_manager_class(port=port)
```

and then using the `ConcreteWorkerManager` (or whatever it was using before) in the test files.
</blockquote></details>

Yes, I changed the original ConcreteWorkerManager to ConcreteWorker and MockWorkerManager to adapt to the changes. This issue was resolved:) The only thing I don't quite understand is that in `test_socketio.py`, we use LocalWorkerManager instead of ConcreteWorkerManager before and it worked. However now I have to change to MockWorkerManager.

---

**Comment by SuperMonanana** [comment]
*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-LaylZK8CI4dFuNsHN5x:-LazqAQNAGWQ7Uk_R0Cc:b-pczzjg) (no related file):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

This PR looks like it is almost ready :) probably a good time merge in development to this branch?
</blockquote></details>

Yes just pushed the latest changes, and got  all the tests passed locally now :) The latest development should be already merged in (I'm getting lost with the version number though)

---

**Comment by SuperMonanana** [comment]
*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-LaylZK8CI4dFuNsHN5x:-LazqdcHC6zSY4PbU747:b-896fix) (no related file):*
<details><summary><i>Previously, SuperMonanana wrote…</i></summary><blockquote>

Yes just pushed the latest changes, and got  all the tests passed locally now :) The latest development should be already merged in (I'm getting lost with the version number though)
</blockquote></details>

Done.

---

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/simulation/worker_manager.py, line 72 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-L_lWNUm-bcsc16a_-JB:-L_mipcYA4xLr_4TwVIP:b7ytzdn) ([raw file](https://github.com/ocadotechnology/aimmo/blob/5f3bff44a96c8fe217f0777c59aa9a49bfc7b5ac/aimmo-game/simulation/worker_manager.py#L72)):*
<details><summary><i>Previously, SuperMonanana wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Just found thought the test that we have to put `del self.player_id_to_worker[player_id]` before `worker.remove_worker` as it was, otherwise it will cause the player_id points to a removed worker in the list

**Comment by SuperMonanana** [comment]
___
*[aimmo-game/tests/test_simulation/workers/test_worker.py, line 7 at r10](https://reviewable.io/reviews/ocadotechnology/aimmo/997#-Lb9Mk-r6x5uWcfzbebQ:-LbTSlO_7QH1LNNDqO0X:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/26ee47df4995cb516b4bbd420fc0f2dd9bd0f375/aimmo-game/tests/test_simulation/workers/test_worker.py#L7)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

commented out line here
</blockquote></details>

Done.

**Pull request merged**
