### PR TITLE
feat: add DropAction

### PR DESCRIPTION
**Pull request by dionizh**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1656)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1656)* status: all files reviewed, 2 unresolved discussions (waiting on @dionizh)

___
*[`aimmo-game/simulation/action.py` line 106 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1656#-N2B7yzt1soxdZzWVXE_:-N2B7yzu6ezrxz_5yjml:b-77hoeb) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9c8b22362bd6f915978f83332f4f5d60c1ceb732/aimmo-game/simulation/action.py#L106)):*
> ```Python
>         self.avatar.add_event(FailedDropEvent())
>         self.avatar.clear_action()
>         self.avatar.logs.append("Uh oh! Your avatar was unable to drop the artefact on that position!")
> ```

Could this say "at that position"? the "on" confused me for a bit
___
*[`aimmo-game-worker/simulation/world_map.py` line 13 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1656#-N2B8SqG8YW1e0hlHNNt:-N2B8SqG8YW1e0hlHNNu:bv8o09z) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9c8b22362bd6f915978f83332f4f5d60c1ceb732/aimmo-game-worker/simulation/world_map.py#L13)):*
> ```Python
> SCAN_LIMIT = 3
> SCAN_RADIUS = 12
> ARTEFACT_TYPES = ["chest", "key", "yellow_orb", "phone", "keyboard", "coins"]
> ```

How come I'm seeing changes linked to artefacts in this PR?

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1656)* status: all files reviewed, 3 unresolved discussions (waiting on @dionizh)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1656#-N2B8eHWCtAn8HpA0ddh:-N2B8eHWCtAn8HpA0ddi:b-g17rmg) (no related file):*
I know we discussed this before in a meeting but what's the feedback when the user drops an artefact? Does anything happen on screen? Do logs show in the console saying they've dropped something?

___

**Review by razvan-pro — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1656)* status: all files reviewed, 3 unresolved discussions (waiting on @dionizh and @faucomte97)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1656#-N2B8eHWCtAn8HpA0ddh:-N2BAomh3AHxz6ggox0s:b872xhw) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I know we discussed this before in a meeting but what's the feedback when the user drops an artefact? Does anything happen on screen? Do logs show in the console saying they've dropped something?
</blockquote></details>

Oh, good question - it should probably show something in logs? I remember we discussed not to show it on the map, so they should have some other feedback.

___

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1656)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1656#-N2B8eHWCtAn8HpA0ddh:-N2Go1VaA3gAByyeB3Yx:b-iw6ly6) (no related file):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Oh, good question - it should probably show something in logs? I remember we discussed not to show it on the map, so they should have some other feedback.
</blockquote></details>

Added log!

___
___
*[`aimmo-game/simulation/action.py` line 106 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1656#-N2B7yzt1soxdZzWVXE_:-N2Go3ze8UxN1fUxah_x:b9j0vve) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9c8b22362bd6f915978f83332f4f5d60c1ceb732/aimmo-game/simulation/action.py#L106)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Could this say "at that position"? the "on" confused me for a bit
</blockquote></details>

Done. (I was thinking on the square at first, but changed the last bit, and forgot to change the on.)
___
*[`aimmo-game-worker/simulation/world_map.py` line 13 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1656#-N2B8SqG8YW1e0hlHNNt:-N2GoP6OE33yEyRjer0f:bm0fwcg) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9c8b22362bd6f915978f83332f4f5d60c1ceb732/aimmo-game-worker/simulation/world_map.py#L13)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

How come I'm seeing changes linked to artefacts in this PR?
</blockquote></details>

Yeah forgot the coins before!

**Review by faucomte97 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Pull request merged**
