### PR TITLE
fix: Use Freshdesk widget in load screen

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1546)

### CODE REVIEW

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1546)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[game_frontend/public/handlebars_template.html, line 144 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1546#-MdNIlIMChkyU4xj4EGZ:-MdNIlIMChkyU4xj4EG_:bjzw6kk) ([raw file](https://github.com/ocadotechnology/aimmo/blob/6ad1c0c9602b16d3d70a75a22874915a6116f06d/game_frontend/public/handlebars_template.html#L144)):*
> ```HTML
>       FreshworksWidget('open');
>     });
>   </script>
> ```

Should we move the freshdesk section to common and import it here and in portal to avoid duplicate code?
___
*[game_frontend/src/components/GameView/index.js, line 101 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1546#-MdNIydy5ebEsZN9zfDS:-MdNIydy5ebEsZN9zfDT:boi5stf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/6ad1c0c9602b16d3d70a75a22874915a6116f06d/game_frontend/src/components/GameView/index.js#L101)):*
> ```JavaScript
>         </LoadingText>
>         <LoadingText variant='body1' color='inherit'>
>           If the game doesn’t load after 60 seconds, please <a href="#" className="freshdesk__contact-us">contact us</a>.
> ```

Minor, I'd suggest changing the `#` in `href` to `javascript:;` so that the URL in the browser top bar doesn't change :slightly_smiling_face:

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1546)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @faucomte97 and @razvan-pro)

___
*[game_frontend/public/handlebars_template.html, line 144 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1546#-MdNIlIMChkyU4xj4EGZ:-MdXzKfN-_UBbqa2RJwp:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/6ad1c0c9602b16d3d70a75a22874915a6116f06d/game_frontend/public/handlebars_template.html#L144)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Should we move the freshdesk section to common and import it here and in portal to avoid duplicate code?
</blockquote></details>

Done.

**Review by razvan-pro — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1546#-:-MdY0Pr15alSAmaWJpLE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by razvan-pro — APPROVED** [review]
> Reviewed 1 of 2 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1546)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1546)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[game_frontend/src/components/GameView/index.js, line 105 at r12](https://reviewable.io/reviews/ocadotechnology/aimmo/1546#-MdwLhMH2vO3Fdoc5zMU:-MdwLhMH2vO3Fdoc5zMV:b-rk9d5a) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2dd3f3837134e1267e46dda082f7c0bea3d9670c/game_frontend/src/components/GameView/index.js#L105)):*
> ```JavaScript
>         <LoadingText variant='body1' color='inherit'>
>           We are building your game... ⏱<br />
>           If the game doesn’t load after 60 seconds, please <a className="freshdesk__contact-us" onClick={() => {this.openFreshworksWidget();}} style={{"cursor": "pointer", "textDecoration": "underline",}}>contact us</a>.
> ```

Does `onClick` work like `onClick={this.openFreshworksWidget}`? It would be easier to read if so :slightly_smiling_face:

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1546)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[game_frontend/src/components/GameView/index.js, line 105 at r12](https://reviewable.io/reviews/ocadotechnology/aimmo/1546#-MdwLhMH2vO3Fdoc5zMU:-MdwSExaDCq_pIDXjvzH:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2dd3f3837134e1267e46dda082f7c0bea3d9670c/game_frontend/src/components/GameView/index.js#L105)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Does `onClick` work like `onClick={this.openFreshworksWidget}`? It would be easier to read if so :slightly_smiling_face: 
</blockquote></details>

Done.

**Review by razvan-pro — APPROVED** [review]
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1546)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
