### PR TITLE
Logic to distinguish current avatar ID serverside

### PR DESCRIPTION
**Pull request by OlafSzmidt**
This PR will do the following:

- Fixes a URL resolution issue that was missed out on earlier locally. 
- When unity is loaded, we call our newly made function.
- That function will send an AJAX request, also created in the PR, to an API url for that game, and return a JSON.
- We parse the ID from the JSON, send it to the `World Controller`, which is not set up yet - therefore omitted by unity.
- Tests added.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/501)

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Not tested on any of our environments yet. I'm slightly concerned about the removal of the slash in worker spawning. Locally it was fine, I need to double check this higher up

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-:-L70D-DV97_hCDc3-E4M:bavvb81)*

**Comment by OlafSzmidt** [comment]
Code was well tested, added the slash back in. Still to be tested on dev.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/501#-:-L70GDy18uGh3ANBgzfe:bxn6dlz)*

**Comment by CelineBoudier** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[players/tests.py, line 283 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L75EIeA4bs8_P-fJIIs:-L75EIeBbk3XflGw7s7L:b-hqdoam) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bebfb4e9870ef59d76e8dd2035371a7b9c39b669/players/tests.py#L283)):*
> ```Python
>         # Set up the first avatar
>         first_user = self.user
>         models.Avatar(owner=first_user, code=self.CODE, game=self.game).save()
> ```

what's that self.CODE? shouldn't use capital letters like that imo?

---

*[players/tests.py, line 301 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L75ER8oy_q94_3776gM:-L75ER8oy_q94_3776gN:b32vin) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bebfb4e9870ef59d76e8dd2035371a7b9c39b669/players/tests.py#L301)):*
> ```Python
> 
>         # Status code starts with 2, success response can be different than 200.
>         self.assertEqual(str(first_response.status_code)[0], "2")
> ```

:D

---

*[players/tests.py, line 305 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L75OFX476vNzx7owILy:-L75OFX476vNzx7owILz:b-lpwkkq) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bebfb4e9870ef59d76e8dd2035371a7b9c39b669/players/tests.py#L305)):*
> ```Python
> 
>         # JSON is returned as string so needs to be evaluated.
>         first_id = ast.literal_eval(first_response.content)['current_avatar_id']
> ```

why are you using literal_eval here instead of json specific deserialisers? Or am i missing something?

---

*[players/views.py, line 192 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L75o_bsXseKQRN2aB6Z:-L75o_bsXseKQRN2aB6_:b-d0wxhj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bebfb4e9870ef59d76e8dd2035371a7b9c39b669/players/views.py#L192)):*
> ```Python
>         return HttpResponse('Avatar does not exist for this user', status=404)
> 
>     return JsonResponse({'current_avatar_id' : avatar.id})
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501)*

**Comment by OlafSzmidt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[players/tests.py, line 301 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L75ER8oy_q94_3776gM:-L79JEZjbl_Ogp_oAVEF:b-wryidh) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bebfb4e9870ef59d76e8dd2035371a7b9c39b669/players/tests.py#L301)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

:D
</blockquote></details>

Yup :D

---

*[players/tests.py, line 305 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L75OFX476vNzx7owILy:-L79JIV9mtSuIfsS-zMu:b-fsnbzg) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bebfb4e9870ef59d76e8dd2035371a7b9c39b669/players/tests.py#L305)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

why are you using literal_eval here instead of json specific deserialisers? Or am i missing something?
</blockquote></details>

My reasoning here is that the input string is not a `JSON` document, so `json.loads()` won't work. `literal_eval` is able to parse python expressions as strings and make dicts out of them. The only downside is it won't stop us from taking untrusted data, but the API is made by us and won't ever change (+ security should be added backend side anyway) so it's all good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501)*

**Comment by OlafSzmidt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[players/tests.py, line 283 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L75EIeA4bs8_P-fJIIs:-L79KhPndnb19O0N9vd1:b-kt4snt) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bebfb4e9870ef59d76e8dd2035371a7b9c39b669/players/tests.py#L283)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

what's that self.CODE? shouldn't use capital letters like that imo?
</blockquote></details>

It's a constant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501)*

**Comment by OlafSzmidt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[players/views.py, line 192 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L75o_bsXseKQRN2aB6Z:-L79LckkO3hQGBmOh4ke:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bebfb4e9870ef59d76e8dd2035371a7b9c39b669/players/views.py#L192)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501)*

**Comment by CelineBoudier** [comment]
Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[aimmo_runner/minikube.py, line 52 at r2](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L79Rx-K5H4ik5BKZArY:-L79Rx-K5H4ik5BKZArZ:b-o20vzq) ([raw file](https://github.com/ocadotechnology/aimmo/blob/8ca8d1f48be09f3dbcad90276ba191714a6da647/aimmo_runner/minikube.py#L52)):*
> ```Python
>     orig_path = os.path.join(BASE_DIR, 'aimmo-game-creator', 'rc-aimmo-game-creator.yaml')
>     with open(orig_path) as orig_file:
>         content = yaml.safe_load(orig_file.read().replace('latest', 'test').replace('REPLACE_ME', 'http://%s:8000/players/api/games/' % get_ip()))
> ```

If this was in a django project you could use reverse or reverse_lazy here
Also there is no trailing slash at the end of games in the original file?

---

*[players/tests.py, line 283 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L75EIeA4bs8_P-fJIIs:-L79RTCstdbXsxzGXbKX:b-5henvt) ([raw file](https://github.com/ocadotechnology/aimmo/blob/bebfb4e9870ef59d76e8dd2035371a7b9c39b669/players/tests.py#L283)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

It's a constant
</blockquote></details>

i didn't see where this was implemented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501)*

**Comment by OlafSzmidt** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[aimmo_runner/minikube.py, line 52 at r2](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L79Rx-K5H4ik5BKZArY:-L79WiAK4RE1i037fqfE:b-71knlf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/8ca8d1f48be09f3dbcad90276ba191714a6da647/aimmo_runner/minikube.py#L52)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

If this was in a django project you could use reverse or reverse_lazy here
Also there is no trailing slash at the end of games in the original file?
</blockquote></details>

The slash is defined in `urls.py`, not sure what you mean by the original file?

Also this is outside the django `players` folder so we have no access to the views, so no `reverse` for us :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501)*

**Comment by OlafSzmidt** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[aimmo_runner/minikube.py, line 52 at r2](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501#-L79Rx-K5H4ik5BKZArY:-L79X9fsKBezo9GrkZ4S:bvn0kv0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/8ca8d1f48be09f3dbcad90276ba191714a6da647/aimmo_runner/minikube.py#L52)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

The slash is defined in `urls.py`, not sure what you mean by the original file?

Also this is outside the django `players` folder so we have no access to the views, so no `reverse` for us :(
</blockquote></details>

It will work for 99% without the slash, but we will get an extra redirection to the trailing slashed URL, so no point imo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/501)*

**Pull request merged**
