### PR TITLE
Minor fix of game creator RC bug.

### PR DESCRIPTION
**Pull request by OlafSzmidt**
See #498 for more info.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/499)

### CODE REVIEW

**Comment by mrniket** [comment]
can we have some tests for this please?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/499#-:-L6w4PyM-HS8_2ECKX2s:bmwjeii)*

**Comment by mrniket** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/499)*

**Comment by mrniket** [comment]
can we have some tests for this please?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499#-:-L6w7O4pCcr1DHNF6mEt:bmwjeii)*

**Comment by mrniket** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499#-L6wAnjdXnHL7_xOE7q_:-L6wAnjdXnHL7_xOE7qa:b1zc0fq) (no related file):*
Testing out reviewable, also add some tests :P  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499)*

**Comment by OlafSzmidt** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499#-L6wAnjdXnHL7_xOE7q_:-L6wES8vdOfeMSLlb4Tc:b-896fja) (no related file):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Testing out reviewable, also add some tests :P  
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499)*

**Comment by mrniket** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[aimmo-game-creator/tests/test_aimmo_game_creator_yaml.py, line 19 at r2](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499#-L6wGu03lXnYfgISqtlc:-L6wGu04AovcPZAcYeSI:b42izal) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2e64514ff00d9b4e95e95dc64207fad927b2c17d/aimmo-game-creator/tests/test_aimmo_game_creator_yaml.py#L19)):*
> ```Python
> 
>     def test_REPLACE_ME_string_exists(self):
>         self.assertEqual(self.yaml_dict['spec']['template']['spec']['containers'][0]['env'][1]['value'],
> ```

Can we assert the function that processes this? and then have the expected dict?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499)*

**Comment by OlafSzmidt** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[aimmo-game-creator/tests/test_aimmo_game_creator_yaml.py, line 19 at r2](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499#-L6wGu03lXnYfgISqtlc:-L7-YXdQEYV97ITf8qll:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2e64514ff00d9b4e95e95dc64207fad927b2c17d/aimmo-game-creator/tests/test_aimmo_game_creator_yaml.py#L19)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Can we assert the function that processes this? and then have the expected dict?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499)*

**Comment by OlafSzmidt** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup.py, line 25 at r3](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499#-L7-h9rZV_1N6lTOvOU8:-L7-mHmMVoT1jAjrOM7F:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d50362247c122c5e34982602e79438fc7ba1b707/setup.py#L25)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

should we fix the versions on these?
also if it's for tests it should go in the tests_require
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499)*

**Comment by mrniket** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/499)*

**Pull request merged**
