### PR TITLE
GitHub actions publish

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1423)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1423)* status: all files reviewed, 6 unresolved discussions (waiting on @razvan-pro)

___
*[.github/workflows/ci.yml, line 14 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxIeLT0c6it1LrhsD3:-MNxIeLT0c6it1LrhsD4:bkvk6s8) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L14)):*
> ```YAML
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v2
> ```

do we need `fetch-depth: 0` here too for the CodeCov report?
___
*[.github/workflows/ci.yml, line 18 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxIn4a05xMAVx1zP8G:-MNxIn4a05xMAVx1zP8H:bex1n8u) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L18)):*
> ```YAML
>         uses: actions/setup-python@v2
>         with:
>           python-version: 3.7.x
> ```

Do we want to specify `architecture: 'x64'` like we did in other repos or is it not necessary?
___
*[.github/workflows/ci.yml, line 62 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxJ2vu3uP2tO0G32X0:-MNxJ2vu3uP2tO0G32X1:b3pju78) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L62)):*
> ```YAML
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v2
> ```

same `fetch-depth` question as above
___
*[.github/workflows/ci.yml, line 82 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxJ7UkB-x6USJKNVRh:-MNxJ7UkB-x6USJKNVRi:b3pju78) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L82)):*
> ```YAML
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v2
> ```

same `fetch-depth` question as above
___
*[.github/workflows/ci.yml, line 102 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxJ9Mm7esNE382qMD1:-MNxJ9Mm7esNE382qMD2:b3pju78) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L102)):*
> ```YAML
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v2
> ```

same `fetch-depth` question as above
___
*[.github/workflows/publish.yml, line 79 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxJVL668k3jgxUWkTd:-MNxJVL668k3jgxUWkTe:b3yen8l) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/publish.yml#L79)):*
> ```YAML
>         id: docker_tag
>         run: |
>           echo "::set-output name=tag::${GITHUB_REF:11}"  # this is either branch name or tag after first character ('v')
> ```

Just checking that this substring will always work here, ie is there any chance of the tag being longer than 11 characters after a while?

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1423)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1423)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[.github/workflows/ci.yml, line 14 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxIeLT0c6it1LrhsD3:-MNxNcC-91dqx4wiMcH8:b2nhswv) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

do we need `fetch-depth: 0` here too for the CodeCov report?
</blockquote></details>

Yep
___
*[.github/workflows/ci.yml, line 18 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxIn4a05xMAVx1zP8G:-MNxNiwx1qDq1oLOSUzo:b-ayiot4) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L18)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we want to specify `architecture: 'x64'` like we did in other repos or is it not necessary?
</blockquote></details>

Yep, it is the default value, but good to be specific I think.
___
*[.github/workflows/ci.yml, line 62 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxJ2vu3uP2tO0G32X0:-MNxNp0V8H-qEkag_9yz:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L62)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

same `fetch-depth` question as above
</blockquote></details>

Done.
___
*[.github/workflows/ci.yml, line 82 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxJ7UkB-x6USJKNVRh:-MNxNpOHBsjhi3C1Zi7T:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L82)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

same `fetch-depth` question as above
</blockquote></details>

Done.
___
*[.github/workflows/ci.yml, line 102 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxJ9Mm7esNE382qMD1:-MNxNpxHDPc_9thx5leL:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/ci.yml#L102)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

same `fetch-depth` question as above
</blockquote></details>

Done.
___
*[.github/workflows/publish.yml, line 79 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-MNxJVL668k3jgxUWkTd:-MNxNuNp85SuhTI5ULrR:bqgwzdg) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d069694be602307cb14260f0893d451ed5f7a3d8/.github/workflows/publish.yml#L79)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Just checking that this substring will always work here, ie is there any chance of the tag being longer than 11 characters after a while?
</blockquote></details>

It should work until github will change the ref pattern :slightly_smiling_face: At the moment, "For branches this in the format `refs/heads/<branch_name>`, and for tags it is `refs/tags/<tag_name>`." and 11 is the lazy way of getting either branch name or the version as the tag will start with 'v' :smile: 

Source: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1423)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1423#-:-MNxWJXs8D9wCMkNNhvr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
