### PR TITLE
fix: Move game creator to Django

### PR DESCRIPTION
**Pull request by faucomte97**
This PR replaces #1575 as the owner of the repo that PR originates from has been archived.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)

### CODE REVIEW

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: 0 of 61 files reviewed, 2 unresolved discussions

___
*[`aimmo/views.py` line 124 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne81NHT1nqdWRPV_2Ez:-Ne81NHT1nqdWRPV_2F-:b70t8e0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/views.py#L124)):*
> ```Python
>         return Response(response)
> 
>     def destroy(self, request, *args, **kwargs):
> ```

Check if this is being used
___
*[`aimmo/game_manager/game_manager.py` line 73 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne82rrD0PeB5xkIHAnA:-Ne82rrD0PeB5xkIHAnB:b-g68fxw) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L73)):*
> ```Python
>             self.game_ingress_manager.add_game_path_to_ingress(game_name=game_name)
>         except ApiException as e:
>             # TODO: Filter out no-ingress exception on localhost
> ```

Look more into what's going on here

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: 0 of 61 files reviewed, 4 unresolved discussions

___
*[`aimmo/game_manager/game_manager.py` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne83CPM60VBAptLOro2:-Ne83CPM60VBAptLOro3:bqq1nhj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L26)):*
> ```Python
>     ) -> None:
>         self.api: CoreV1Api = CoreV1Api()
>         self.api_client: ApiClient = ApiClient()
> ```

Validate we're connecting to the client correctly
___
*[`aimmo/game_manager/game_manager.py` line 92 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne84AcM4XDf40YyrS3W:-Ne84AcM4XDf40YyrS3X:bsc9doj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L92)):*
> ```Python
>         return self.game_server_manager.delete_game_server(game_id=game_id)
> 
>     def recreate_game_server(self, game_id: int, game_data_updates: dict = None) -> None:
> ```

See if we can just update instead of recreating

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: 0 of 61 files reviewed, 6 unresolved discussions

___
*[`aimmo-game/Pipfile` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne860J2D8mbaTwMgo_X:-Ne860J2D8mbaTwMgo_Y:byp18fd) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo-game/Pipfile#L20)):*
> ```TOML
> 
> [packages]
> #aimmo-game = {editable = true, path = "."}
> ```

Remove
___
*[`aimmo-game/simulation/django_communicator.py` line 7 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne86LalA83HhNYt04Vp:-Ne86LalA83HhNYt04Vq:b22quet) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo-game/simulation/django_communicator.py#L7)):*
> ```Python
> import aiohttp
> 
> LOGGER = logging.getLogger(__name__)
> ```

Remove this



_Code quote:_
```Python
import aiohttp

LOGGER = logging.getLogger(__name__)
```

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 24 of 61 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: 24 of 61 files reviewed, 17 unresolved discussions (waiting on @faucomte97)

___
*[`aimmo/models.py` line 177 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NeltprK-g6EtdXP15b4:-NeltprK-g6EtdXP15b5:b25td5t) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/models.py#L177)):*
> ```Python
>             game_manager = GameManager()
>             game_manager.create_game_secret(game_id=self.id, token=self.auth_token)
>             game_manager.create_game_server(game_id=self.id, game_data=GameSerializer(self).data)
> ```

this feels redundant. why serialize data we already have? why not just pass the data in directly?
___
*[`aimmo/models.py` line 202 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NeluXpeCT-WXse8-HKn:-NeluXpeCT-WXse8-HKo:bnd9kg8) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/models.py#L202)):*
> ```Python
> 
> 
> class GameSerializer(serializers.Serializer):
> ```

I'm not sure this serializer is needed but if it were, why not make it a ModelSerializer since where serializing the Game model? 
___
*[`aimmo/views.py` line 124 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne81NHT1nqdWRPV_2Ez:-Nelx3pR5yk-XJyYaE48:b-iodzrd) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/views.py#L124)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Check if this is being used
</blockquote></details>

let me know about this. if the game server is deleted here, then where/how are game servers deleted?
___
*[`aimmo/views.py` line 173 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NelzaWW1TAqPrGwsNJc:-NelzaWW1TAqPrGwsNJd:b9wc4s5) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/views.py#L173)):*
> ```Python
>                 # Re-raise exception so that atomic transaction reverts
>                 raise exception
> ```

besides aborting the db transaction, do we have any graceful feedback or handling of this exception?
___
*[`aimmo/game_manager/game_manager.py` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne83CPM60VBAptLOro2:-Nem8LVRDOnySY_H_20P:b-wtv748) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L26)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Validate we're connecting to the client correctly
</blockquote></details>

how does our Django App Engine instance connect/authenticate with our GKE instance?
___
*[`aimmo/game_manager/game_manager.py` line 43 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Nem94wDAxtCTJmQWjO8:-Nem94wDAxtCTJmQWjO9:b5f4vsf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L43)):*
> ```Python
>         return f"game-{game_id}"
> 
>     def create_game_secret(self, game_id: int, token: str):
> ```

why do we need to create a game secret?
___
*[`aimmo/game_manager/game_manager.py` line 73 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne82rrD0PeB5xkIHAnA:-Nem9BXWElEGJ5mB4iL3:b1d0p40) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L73)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Look more into what's going on here
</blockquote></details>

this code seems dangerous. it could make it possible to create a gamer server + service without an ingress path, meaning the game will be non-contactable. Also, if there's no ingress on localhost, how are requests getting routed locally?
___
*[`aimmo/game_manager/game_manager.py` line 89 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemAMMU9lNNiQVsI4gQ:-NemAMMU9lNNiQVsI4gR:b-deehb2) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L89)):*
> ```Python
>         except ApiException as e:
>             LOGGER.error(e)
>         self.game_service_manager.delete_game_service(game_id=game_id)
> ```

defensive programming - if an exception is raised when deleting the service, the server will not be deleted and remain orphaned. we need to be careful about orphaned instances in our system. 
___
*[`aimmo/game_manager/game_manager.py` line 92 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne84AcM4XDf40YyrS3W:-NemBhBQCCRuhXeYSZn1:bxdg0p6) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L92)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

See if we can just update instead of recreating
</blockquote></details>

I think the confusion stems from how the system is modelled. Conceptually, we're not recreating the game, we're creating a new game. But technically, the way we've implemented it, we recycle game ids (which is conceptually wrong). Let's discuss this further and see if you agree.
___
*[`aimmo/game_manager/game_secret_manager.py` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemEY590K2DEUgY0WbM:-NemEY590K2DEUgY0WbN:b-ca7944) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_secret_manager.py#L12)):*
> ```Python
> 
> 
> class GameSecretManager:
> ```

did we confirm if this is needed? if this is to ensure secure communication with our game servers, couldn't this just be achieved with CORS in our ingress?
___
*[`aimmo/game_manager/game_server_manager.py` line 39 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemFC69C0zzbip5bpjc:-NemFC69C0zzbip5bpjd:b-ws48pg) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_server_manager.py#L39)):*
> ```Python
>                             "game-id": str(game_id),
>                         },
>                         "annotations": game_data,
> ```

why is this annotation needed? was it meant to be an environment variable?
___
*[`aimmo/game_manager/game_server_manager.py` line 55 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemGXck5LSZ9T0_79SS:-NemGXck5LSZ9T0_79ST:b-aqevs) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_server_manager.py#L55)):*
> ```Python
>             return result["status"]["gameServerName"]
> 
>     def delete_game_server(self, game_id: int) -> dict:
> ```

seems we have a few functions that delete game servers. can you help me understand the need for each on a call?
___
*[`aimmo/game_manager/game_service_manager.py` line 45 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemMj3f64UXUs1qB_Mq:-NemMj3f64UXUs1qB_Mr:b-j2oyxs) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_service_manager.py#L45)):*
> ```Python
>         for resource in resources.items:
>             LOGGER.info("Removing service: {}".format(resource.metadata.name))
>             self.api.delete_namespaced_service(resource.metadata.name, K8S_NAMESPACE)
> ```

defensive programming - wrap in a try/except and log any exceptions
___
*[`aimmo/tests/test_game_manager.py` line 37 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemQ-YM6TFO_vtI_jKF:-NemQ-YM6TFO_vtI_jKG:b-4u848o) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/tests/test_game_manager.py#L37)):*
> ```Python
> 
> 
> def test_create_game_server(game_manager: GameManager, game_id, game_data):
> ```

what's the value of these tests? I say this because:
1. we're not making assertions
2. we're not testing our code/functionality? Seems we're testing the k8s client more.
___
*[`aimmo/tests/test_middleware.py` line 84 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemRBNi4-S1EVz4MOFX:-NemRBNi4-S1EVz4MOFY:b-9v6g0k) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/tests/test_middleware.py#L84)):*
> ```Python
>         assert Game.objects.all().count() == 2
> 
>     @patch("aimmo.views.GameManager")
> ```

why mock this if we're not doing anything with it?

**Review by SKairinos — COMMENTED** [review]
> Reviewed 27 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: 51 of 61 files reviewed, 17 unresolved discussions (waiting on @faucomte97)

___
*[`aimmo-game/Pipfile` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne860J2D8mbaTwMgo_X:-NemeYCBDx0D_bNAZiGs:b1kpmcg) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo-game/Pipfile#L20)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

just a reminder
___
*[`aimmo-game/simulation/django_communicator.py` line 7 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne86LalA83HhNYt04Vp:-NemlJB00dQwH5SEs0Fo:brm6u7r) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo-game/simulation/django_communicator.py#L7)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove this
</blockquote></details>

reminder

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: 51 of 61 files reviewed, 16 unresolved discussions (waiting on @SKairinos)

___
*[`aimmo/models.py` line 177 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NeltprK-g6EtdXP15b4:-NfHDdh42eN77I6AQ1GJ:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/models.py#L177)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

this feels redundant. why serialize data we already have? why not just pass the data in directly?
</blockquote></details>

Done.
___
*[`aimmo/views.py` line 124 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne81NHT1nqdWRPV_2Ez:-NfHFiiC69XsLfEVC4hv:b45bc93) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/views.py#L124)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

let me know about this. if the game server is deleted here, then where/how are game servers deleted?
</blockquote></details>

Delete this endpoint
___
*[`aimmo/views.py` line 173 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NelzaWW1TAqPrGwsNJc:-NfHFzBF32cz0s9MtYj9:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/views.py#L173)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

besides aborting the db transaction, do we have any graceful feedback or handling of this exception?
</blockquote></details>

Done.
___
*[`aimmo/game_manager/game_manager.py` line 43 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Nem94wDAxtCTJmQWjO8:-NfHKM9F8218Zo0Uak90:b-9fqt00) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L43)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why do we need to create a game secret?
</blockquote></details>

Add a TODO for the improved solution

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: 51 of 61 files reviewed, 14 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`aimmo/models.py` line 202 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NeluXpeCT-WXse8-HKn:-Nfp--eWClOyx8cdQn-5:b-7z6omm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/models.py#L202)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

I'm not sure this serializer is needed but if it were, why not make it a ModelSerializer since where serializing the Game model?
</blockquote></details>

Added a TODO to replace with ModelSerializer.
___
*[`aimmo/game_manager/game_manager.py` line 43 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Nem94wDAxtCTJmQWjO8:-NfWv15pACxGJlJGXOg9:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L43)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Add a TODO for the improved solution
</blockquote></details>

Done.
___
*[`aimmo/game_manager/game_manager.py` line 73 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne82rrD0PeB5xkIHAnA:-NfX3-7gBS4PD8VmtkJB:b2nhdq0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L73)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

this code seems dangerous. it could make it possible to create a gamer server + service without an ingress path, meaning the game will be non-contactable. Also, if there's no ingress on localhost, how are requests getting routed locally?
</blockquote></details>

Dun
___
*[`aimmo/game_manager/game_manager.py` line 89 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemAMMU9lNNiQVsI4gQ:-NfX371l2cJnQjcvQXZn:b32wsm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L89)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

defensive programming - if an exception is raised when deleting the service, the server will not be deleted and remain orphaned. we need to be careful about orphaned instances in our system.
</blockquote></details>

no
___
*[`aimmo/game_manager/game_manager.py` line 92 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne84AcM4XDf40YyrS3W:-NfX383lBX8-H1fi_PMO:b32wsm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_manager.py#L92)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

I think the confusion stems from how the system is modelled. Conceptually, we're not recreating the game, we're creating a new game. But technically, the way we've implemented it, we recycle game ids (which is conceptually wrong). Let's discuss this further and see if you agree.
</blockquote></details>

no
___
*[`aimmo/game_manager/game_secret_manager.py` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemEY590K2DEUgY0WbM:-NfX3A7X7GjnAUP9VvDk:b32wsm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_secret_manager.py#L12)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

did we confirm if this is needed? if this is to ensure secure communication with our game servers, couldn't this just be achieved with CORS in our ingress?
</blockquote></details>

no
___
*[`aimmo/game_manager/game_server_manager.py` line 39 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemFC69C0zzbip5bpjc:-NfX3Bd-9S5AVu0q2be3:b32wsm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_server_manager.py#L39)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why is this annotation needed? was it meant to be an environment variable?
</blockquote></details>

no
___
*[`aimmo/game_manager/game_server_manager.py` line 55 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemGXck5LSZ9T0_79SS:-NfX3CeN1H1Q4Fs0wfiH:b32wsm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_server_manager.py#L55)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

seems we have a few functions that delete game servers. can you help me understand the need for each on a call?
</blockquote></details>

no
___
*[`aimmo/game_manager/game_service_manager.py` line 45 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemMj3f64UXUs1qB_Mq:-NfX3dQo18azOSTHGo6Z:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/game_manager/game_service_manager.py#L45)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

defensive programming - wrap in a try/except and log any exceptions
</blockquote></details>

Done.
___
*[`aimmo/tests/test_game_manager.py` line 37 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemQ-YM6TFO_vtI_jKF:-Nfp03TGD5wmBL2kwbIH:b-vami9g) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/tests/test_game_manager.py#L37)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

what's the value of these tests? I say this because:
1. we're not making assertions
2. we're not testing our code/functionality? Seems we're testing the k8s client more.
</blockquote></details>

It seems like it just checks that the 3 subcalls of the `create_game_server` function are being called properly, I guess to make sure that the K8s calls are executed fine? :confused: 
___
*[`aimmo/tests/test_middleware.py` line 84 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-NemRBNi4-S1EVz4MOFX:-Nfp-m8x9dHaxLqhus5Z:b-4klchb) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/tests/test_middleware.py#L84)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why mock this if we're not doing anything with it?
</blockquote></details>

It is used, by the `save()` function which calls the GameManager to create the game servers.
___
*[`aimmo-game/Pipfile` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne860J2D8mbaTwMgo_X:-NfX3kAaA0beBmxbza39:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo-game/Pipfile#L20)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just a reminder
</blockquote></details>

Done.
___
*[`aimmo-game/simulation/django_communicator.py` line 7 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne86LalA83HhNYt04Vp:-NfX3tQJ2L9HQPvdMpey:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo-game/simulation/django_communicator.py#L7)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

reminder
</blockquote></details>

Done.

**Review by SKairinos — APPROVED** [review]
> Reviewed 5 of 61 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`aimmo/views.py` line 124 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne81NHT1nqdWRPV_2Ez:-NgIGb9l499mfV6A0l9W:bhb5abl) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/views.py#L124)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Delete this endpoint
</blockquote></details>

Are you going to delete it now or are do you want to just add a TODO for now?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`aimmo/views.py` line 124 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1798#-Ne81NHT1nqdWRPV_2Ez:-NgZtkOD90nO6IrVfJOY:bp90rqm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9957a0f0c6ffef05ffdf56a22f87de7653588c32/aimmo/views.py#L124)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Are you going to delete it now or are do you want to just add a TODO for now?
</blockquote></details>

Dun now

**Review by SKairinos — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1798)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
