### PR TITLE
fix: Fix worksheets not changing on game server

### PR DESCRIPTION
**Pull request by razvan-pro**
# Description

Duplicated part of game_manager in aimmo. Game server now gets recreated when a game worksheet gets updated.

## Testing

Tested locally by changing the worksheet on a running game server, playing it and checking the worksheet is updated. Also tested this on a stopped server.

## Checklist

- [ ] Play a game, go back and change the worksheet, play the game again and check if the worksheet changed.
- [ ] Make sure a game is stopped (wasn't accessed in the past hour). Update the worksheet and play it. It should have the correct worksheet.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1487)

### CODE REVIEW

**Review by dionizh — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1487)* status: all files reviewed, 4 unresolved discussions (waiting on @razvan-pro)

___
*[aimmo/game_manager.py, line 35 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8pUD06lI2Gi-rsr_2:-MW8pUD06lI2Gi-rsr_3:b-fz724m) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/game_manager.py#L35)):*
> ```
> agones.dev
> ```
Can we put this as a constant above like the namespace? Seems to be referenced several times.
Also - I was wondering about the naming `.dev`. Is that just the default agones deployment?
___
*[aimmo/game_manager.py, line 138 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8qAfO5OhIZv-afBN-:-MW8qAfO5OhIZv-afBN0:blsvx6x) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/game_manager.py#L138)):*
> ```
> self.patch_game_service(game_id=game_id, game_server_name=game_server_name)
> ```
It's unclear to me why we need to patch the game service after deleting and creating it 🤔
___
*[aimmo/tests/test_views.py, line 444 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8t32XEVi4fXSOaUcu:-MW8t32XEVi4fXSOaUcv:bdvoif3) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/tests/test_views.py#L444)):*
> ```
>  mocked_game_manager
> ```
Not sure why this is here if it's not actually used anywhere in this function?
___
*[example_project/example_project/settings.py, line 118 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8tN0aB_b-VPsVzvao:-MW8tN0b9t1VFdE2sqdn:bd3uuw6) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/example_project/example_project/settings.py#L118)):*
> ```
> game_server = result_items[0]
> ```
Should this line exist? Seems the work is done below.
I guess you might want to initialise it to None and raise an exception if it's empty later?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1487)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @dionizh and @razvan-pro)

___
*[aimmo/game_manager.py, line 35 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8pUD06lI2Gi-rsr_2:-MWOmmNT4SiOI_0v3egm:b-lg14d5) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/game_manager.py#L35)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> agones.dev
> ```
Can we put this as a constant above like the namespace? Seems to be referenced several times.
Also - I was wondering about the naming `.dev`. Is that just the default agones deployment?
</blockquote></details>

I think it will be ugly to interpolate the constant everywhere, this is like a unique name (making it unique with namespacing). We can use the constant just for `groups` parameters below if you think that helps?

Yep, `agones.dev` is their name/domain :slightly_smiling_face: See https://agones.dev/
___
*[aimmo/game_manager.py, line 138 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8qAfO5OhIZv-afBN-:-MWOnm8O5qVhdGs9daAS:bx91stj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/game_manager.py#L138)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> self.patch_game_service(game_id=game_id, game_server_name=game_server_name)
> ```
It's unclear to me why we need to patch the game service after deleting and creating it 🤔
</blockquote></details>

Because it takes `game_server_name` as a parameter, which is returned by `create_game_server_allocation` :slightly_smiling_face: So, the game name will change when it's recreated, thus the service needs to be updated.
___
*[aimmo/tests/test_views.py, line 444 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8t32XEVi4fXSOaUcu:-MWOo8zd03kiXiTeI8S8:bipdekd) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/tests/test_views.py#L444)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
>  mocked_game_manager
> ```
Not sure why this is here if it's not actually used anywhere in this function?
</blockquote></details>

This is injected by `@patch` - I tried to find a way to not require this argument, but I couldn't. If you know a solution for this, I'll be happy to remove it :grin: 
___
*[example_project/example_project/settings.py, line 118 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8tN0aB_b-VPsVzvao:-MWOomHC1FiYr1ozFE8l:b-oltb9e) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/example_project/example_project/settings.py#L118)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> game_server = result_items[0]
> ```
Should this line exist? Seems the work is done below.
I guess you might want to initialise it to None and raise an exception if it's empty later?
</blockquote></details>

This will raise the `IndexError` exception. We could probably get rid of the try-except by checking its length instead? But `KeyError` is probably safe to keep there, so might as well keep the index one too and let this trigger it :shrug:

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1487)* status: all files reviewed, 4 unresolved discussions (waiting on @razvan-pro)

___
*[aimmo/game_manager.py, line 35 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8pUD06lI2Gi-rsr_2:-MWOxIfg1_w_50m8StEI:b-8z1wxy) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/game_manager.py#L35)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

I think it will be ugly to interpolate the constant everywhere, this is like a unique name (making it unique with namespacing). We can use the constant just for `groups` parameters below if you think that helps?

Yep, `agones.dev` is their name/domain :slightly_smiling_face: See https://agones.dev/
</blockquote></details>

I see, fair enough. I guess as long as they're just contained within this one file it's fine.
___
*[aimmo/game_manager.py, line 138 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8qAfO5OhIZv-afBN-:-MWOy3BlCtRrtdxK4WSE:b-uy8dos) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/game_manager.py#L138)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Because it takes `game_server_name` as a parameter, which is returned by `create_game_server_allocation` :slightly_smiling_face: So, the game name will change when it's recreated, thus the service needs to be updated.
</blockquote></details>

Ah right, so there is the game server and the game service. Gotcha 🙂
___
*[aimmo/tests/test_views.py, line 444 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8t32XEVi4fXSOaUcu:-MWPncoBA3FM0Q9kZ167:by7m62u) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/tests/test_views.py#L444)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

This is injected by `@patch` - I tried to find a way to not require this argument, but I couldn't. If you know a solution for this, I'll be happy to remove it :grin: 
</blockquote></details>

Thanks. Can you put the clarification of why we do this in the comment? 🙂
___
*[example_project/example_project/settings.py, line 118 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8tN0aB_b-VPsVzvao:-MWPpEu990BxoKm8ml-o:bp6qq5c) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/example_project/example_project/settings.py#L118)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

This will raise the `IndexError` exception. We could probably get rid of the try-except by checking its length instead? But `KeyError` is probably safe to keep there, so might as well keep the index one too and let this trigger it :shrug: 
</blockquote></details>

Ah I see, the try except is fairly large so I missed it. It's minor, but can you put a comment that we pick the first server by default, but if there are more, then get one which is not marked for deletion (so it's clearer that the two cases are intentional). Also what happens if the only game server is marked for deletion? Shouldn't we check for that as well? Should it maybe be:
`if len(result_items) > 0` (and remove `game_server = result_items[0]`)?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1487)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @dionizh)

___
*[aimmo/game_manager.py, line 35 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8pUD06lI2Gi-rsr_2:-MWPwcbV1GPTqU60H0nR:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/game_manager.py#L35)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

I see, fair enough. I guess as long as they're just contained within this one file it's fine.
</blockquote></details>

Done.
___
*[aimmo/game_manager.py, line 138 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8qAfO5OhIZv-afBN-:-MWPweC1BhIJedKkoxJL:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/game_manager.py#L138)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Ah right, so there is the game server and the game service. Gotcha 🙂
</blockquote></details>

Done.
___
*[aimmo/tests/test_views.py, line 444 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8t32XEVi4fXSOaUcu:-MWPwfht-THNhtx2Zezq:b-vrx2v0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/tests/test_views.py#L444)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Thanks. Can you put the clarification of why we do this in the comment? 🙂
</blockquote></details>

I can, but I don't know if we want this in the code. This is just how `@patch` works and it's in their docs - we won't want to copy this comment everywhere we use `@patch` in the future.

I added an assertion to make use of the arg instead.
___
*[example_project/example_project/settings.py, line 118 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8tN0aB_b-VPsVzvao:-MWPx8k4D24aXfA9SpuB:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/example_project/example_project/settings.py#L118)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Ah I see, the try except is fairly large so I missed it. It's minor, but can you put a comment that we pick the first server by default, but if there are more, then get one which is not marked for deletion (so it's clearer that the two cases are intentional). Also what happens if the only game server is marked for deletion? Shouldn't we check for that as well? Should it maybe be:
`if len(result_items) > 0` (and remove `game_server = result_items[0]`)?
</blockquote></details>

Done.

**Review by dionizh — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1487)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

**Review by dionizh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1487)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[aimmo/tests/test_views.py, line 444 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-MW8t32XEVi4fXSOaUcu:-MWQ6TIP9aYpRLekreEb:b-e5ewgz) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2853cdc1ed07681d502fc2c375e94aad11a8980d/aimmo/tests/test_views.py#L444)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

I can, but I don't know if we want this in the code. This is just how `@patch` works and it's in their docs - we won't want to copy this comment everywhere we use `@patch` in the future.

I added an assertion to make use of the arg instead.
</blockquote></details>

+1 for extra comment and assert :)

**Review by dionizh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1487)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by dionizh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1487#-:-MWQ73-z94WvXBisJUkU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
