### PR TITLE
feat: Upgrade to Django 2.2

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)

### CODE REVIEW

**Review by mrniket — CHANGES_REQUESTED** [review]
> Reviewed 17 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: 17 of 20 files reviewed, 4 unresolved discussions (waiting on @faucomte97)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRsnfP5Z5VDkSyh2xE:-MLRsnfP5Z5VDkSyh2xF:bvnslho) (no related file):*
are we editing previous migrations here? 

---
___
*[setup.py, line 25 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRsxRL4LtjM8Obo0ve:-MLRsxRL4LtjM8Obo0vf:biecalq) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/setup.py#L25)):*
> ```Python
>     include_package_data=True,
>     install_requires=[
>         "django>=1.11.24, <= 2.0.0",
> ```

we don't have to support 1.11 if we have the long-running feature branch
___
*[aimmo/migrations/0003_auto_20160802_1418.py, line 104 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRsVQs3iZ3qkjVNpID:-MLRsVQt6L2N27qbxyIR:b95tf1d) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/aimmo/migrations/0003_auto_20160802_1418.py#L104)):*
> ```Python
>                         to=settings.AUTH_USER_MODEL,
>                         null=True,
>                         on_delete=models.SET_NULL,
> ```

are we editing a previous migration here? I think we forgot to name this migration something human understandable
___
*[aimmo/tests/test_models.py, line 6 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRtdSTDU2JWEL2tBvl:-MLRtdSTDU2JWEL2tBvm:b-1zvghe) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/aimmo/tests/test_models.py#L6)):*
> ```Python
> 
> 
> class TestModels(TestCase):
> ```

I see what this test case is testing here but I'm unsure whether how useful this test will be to keep? Each test has a maintainability cost associated to it too.

**Review by mrniket — COMMENTED** [review]
> Reviewed 3 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97)

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 4 unresolved discussions (waiting on @mrniket)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRsnfP5Z5VDkSyh2xE:-MLSMBcD3i0SErIlftTF:b2lmofz) (no related file):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

are we editing previous migrations here? 
</blockquote></details>

Yeah, it was required by Django 2.0 to update the `on_delete` fields everywhere including the past migrations. Without that the tests can't run and the migrations can't be run either

---
___
*[setup.py, line 25 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRsxRL4LtjM8Obo0ve:-MLSMcbd-XJVIMefvRBC:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/setup.py#L25)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

we don't have to support 1.11 if we have the long-running feature branch
</blockquote></details>

Done.
___
*[aimmo/migrations/0003_auto_20160802_1418.py, line 104 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRsVQs3iZ3qkjVNpID:-MLSNHXqCLbxQIS7dxuE:bnocq5b) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/aimmo/migrations/0003_auto_20160802_1418.py#L104)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

are we editing a previous migration here? I think we forgot to name this migration something human understandable
</blockquote></details>

Yeah there are about 6 old migrations that have no clear name. Should I figure out what they were for and rename them?
___
*[aimmo/tests/test_models.py, line 6 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRtdSTDU2JWEL2tBvl:-MLSNNpX9hGSFpz3quHG:b-s8e46) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/aimmo/tests/test_models.py#L6)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

I see what this test case is testing here but I'm unsure whether how useful this test will be to keep? Each test has a maintainability cost associated to it too.
</blockquote></details>

True, I think the test would only be useful if someone ever changes the `on_delete` field, so I guess it's more of a safeguard. If you think it's not really useful, I can remove it

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 18 of 20 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 5 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[example_project/example_project/urls.py, line 11 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLha6749Z8GHOiwjSRF:-MLha6749Z8GHOiwjSRG:bu37w6) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b2bff4fb381178b729bdec9d915e777b52e0e600/example_project/example_project/urls.py#L11)):*
> ```Python
> urlpatterns = [
>     url(r"^", include(portal_urls)),
>     url(r'^administration/', include((admin.site.urls[0], 'admin'), namespace='admin')),
> ```

Double quotes and idea in portal PR :slightly_smiling_face:

**Review by razvan-pro — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 5 unresolved discussions (waiting on @faucomte97 and @mrniket)

**Review by mrniket — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @razvan-pro)

___
*[aimmo/migrations/0003_auto_20160802_1418.py, line 104 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRsVQs3iZ3qkjVNpID:-MLrSBq_Bfk--8-SJhzZ:b-lyxlqf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/aimmo/migrations/0003_auto_20160802_1418.py#L104)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Yeah there are about 6 old migrations that have no clear name. Should I figure out what they were for and rename them?
</blockquote></details>

Dw, I think it's fine to leave it as it is 😊 
___
*[aimmo/tests/test_models.py, line 6 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRtdSTDU2JWEL2tBvl:-MLrSd4k9Mq95nHXDVGv:bej1fmp) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/aimmo/tests/test_models.py#L6)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

True, I think the test would only be useful if someone ever changes the `on_delete` field, so I guess it's more of a safeguard. If you think it's not really useful, I can remove it
</blockquote></details>

Yeah, I'm in favour of removing it. @razvan-pro, second opinion?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @razvan-pro)

___
*[example_project/example_project/urls.py, line 11 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLha6749Z8GHOiwjSRF:-MLrUWd61lD1PWywKkf9:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b2bff4fb381178b729bdec9d915e777b52e0e600/example_project/example_project/urls.py#L11)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Double quotes and idea in portal PR :slightly_smiling_face: 
</blockquote></details>

Done.

**Review by mrniket — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @razvan-pro)

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[aimmo/tests/test_models.py, line 6 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRtdSTDU2JWEL2tBvl:-MLs66yX0uTQ1tixe8ma:bh1dig9) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/aimmo/tests/test_models.py#L6)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Yeah, I'm in favour of removing it. @razvan-pro, second opinion?
</blockquote></details>

Hm, it would be good to have a test like this, but maybe we can do it more isolated without going through all the models at once: e.g. test if removing a worksheet which has a game attached to it would raise an error (not sure if users can delete worksheets at the moment). If we don't have tests like this already, it may take a long time to cover everything individually now, so then yeah, we can probably delete this for now and do some functional tests in the future.

**Review by mrniket — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97 and @razvan-pro)

___
*[aimmo/tests/test_models.py, line 6 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRtdSTDU2JWEL2tBvl:-MLvs2SV9RwQlYinbjbX:b-pr0pj2) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/aimmo/tests/test_models.py#L6)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Hm, it would be good to have a test like this, but maybe we can do it more isolated without going through all the models at once: e.g. test if removing a worksheet which has a game attached to it would raise an error (not sure if users can delete worksheets at the moment). If we don't have tests like this already, it may take a long time to cover everything individually now, so then yeah, we can probably delete this for now and do some functional tests in the future.
</blockquote></details>

Yeah, I was thinking a higher-level test but be better in this instance. I believe we don't have tests like this currently...

**Review by razvan-pro — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

**Review by razvan-pro — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: 0 of 36 files reviewed, 1 unresolved discussion (waiting on @faucomte97, @mrniket, and @razvan-pro)

___
*[aimmo/tests/test_models.py, line 6 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MLRtdSTDU2JWEL2tBvl:-MMW5Pza07z-u1o8YgdI:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/96b511c753233e904f5b75527788a210192bf5e6/aimmo/tests/test_models.py#L6)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Yeah, I was thinking a higher-level test but be better in this instance. I believe we don't have tests like this currently...
</blockquote></details>

Done.

**Review by razvan-pro — APPROVED** [review]
> Reviewed 28 of 28 files at r11.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[Pipfile, line 10 at r11](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MMWNI6NA1C71jfMkGzi:-MMWNI6NA1C71jfMkGzj:budwqtf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/7c283c97feffa2ae9771402b19decaad103ff55d/Pipfile#L10)):*
> ```
> pytest-django = "==4.1.0"
> pytest-pythonpath = "*"
> #codeforlife-portal = "*"
> ```

Idea: can we try getting portal from a git branch here? I see there is a way to specify this https://github.com/pypa/pipfile
___
*[setup.py, line 26 at r11](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MMWNcZM9kmbHWg_vnMG:-MMWNcZM9kmbHWg_vnMH:bg0volm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/7c283c97feffa2ae9771402b19decaad103ff55d/setup.py#L26)):*
> ```Python
>     install_requires=[
>         "django==2.2.*",
>         # "django-autoconfig >= 0.3.6, < 1.0.0",
> ```

We'll need to fix this somehow, I assume it's still needed right?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 2 unresolved discussions (waiting on @mrniket and @razvan-pro)

___
*[Pipfile, line 10 at r11](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MMWNI6NA1C71jfMkGzi:-MMp3uX4913n43uBclN0:b-fobjvv) ([raw file](https://github.com/ocadotechnology/aimmo/blob/7c283c97feffa2ae9771402b19decaad103ff55d/Pipfile#L10)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Idea: can we try getting portal from a git branch here? I see there is a way to specify this https://github.com/pypa/pipfile
</blockquote></details>

I can't seem to lock the Pipfile if I do that because portal points to old repos still :(
___
*[setup.py, line 26 at r11](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MMWNcZM9kmbHWg_vnMG:-MMoxOoSE96AMmLjx0Rl:b-qb1vtp) ([raw file](https://github.com/ocadotechnology/aimmo/blob/7c283c97feffa2ae9771402b19decaad103ff55d/setup.py#L26)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

We'll need to fix this somehow, I assume it's still needed right?
</blockquote></details>

yes indeed

**Review by razvan-pro — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1416)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[Pipfile, line 10 at r11](https://reviewable.io/reviews/ocadotechnology/aimmo/1416#-MMWNI6NA1C71jfMkGzi:-MMp9jQy7aaUtcukhimm:bbqmvot) ([raw file](https://github.com/ocadotechnology/aimmo/blob/7c283c97feffa2ae9771402b19decaad103ff55d/Pipfile#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I can't seem to lock the Pipfile if I do that because portal points to old repos still :(
</blockquote></details>

Ah, I see, yeah, we'd need to sync all of them if we want to try this

**Pull request merged**
