### PR TITLE
feat: Add class to game

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1386)

### CODE REVIEW

**Review by mrniket — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1386)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[setup.py, line 33 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1386#-MF5fFkg1jivRw0IyNU-:-MF5fFkg1jivRw0IyNU0:b2ggxv4) ([raw file](https://github.com/ocadotechnology/aimmo/blob/65de4d26538ec84dd813226ef25003e5324d79a3/setup.py#L33)):*
> ```Python
>         "six",
>         "hypothesis",
>         "cfl-common >= 3.1.4"
> ```

I would prefer to fix this to the major version only, that way we don't need to keep on updating it for versions without breaking changes
___
*[aimmo/models.py, line 61 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1386#-MF5fvMu735OT7-gJr9b:-MF5fvMu735OT7-gJr9c:b8vpkwr) ([raw file](https://github.com/ocadotechnology/aimmo/blob/65de4d26538ec84dd813226ef25003e5324d79a3/aimmo/models.py#L61)):*
> ```Python
>     auth_token = models.CharField(max_length=24, blank=True)
>     owner = models.ForeignKey(User, blank=True, null=True, related_name="owned_games")
>     game_class = models.ForeignKey(Class, blank=True, null=True, related_name="games_for_class")
> ```

do we need to specify cascade deletes here too?
___
*[aimmo/tests/test_migration_game_class.py, line 8 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1386#-MF5g7oz7P5URWVGM0yg:-MF5g7oz7P5URWVGM0yh:b-6l5mji) ([raw file](https://github.com/ocadotechnology/aimmo/blob/65de4d26538ec84dd813226ef25003e5324d79a3/aimmo/tests/test_migration_game_class.py#L8)):*
> ```Python
>     dest_migration = "0016_game_class"
> 
>     def test_game_has_worksheet_as_foreign_key(self):
> ```

maybe not a migration test, but can we test what happens when we delete a class too? (or perhaps this is better done at the view level or in portal)

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1386)* status: 8 of 13 files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[setup.py, line 33 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1386#-MF5fFkg1jivRw0IyNU-:-MFBaTOP-MSZyQ_Ko6s-:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/65de4d26538ec84dd813226ef25003e5324d79a3/setup.py#L33)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

I would prefer to fix this to the major version only, that way we don't need to keep on updating it for versions without breaking changes
</blockquote></details>

Done.

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1386)* status: 13 of 18 files reviewed, 2 unresolved discussions (waiting on @mrniket)

___
*[aimmo/models.py, line 61 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1386#-MF5fvMu735OT7-gJr9b:-MFXvfto5qp90NsEeVcL:b-6tgks2) ([raw file](https://github.com/ocadotechnology/aimmo/blob/65de4d26538ec84dd813226ef25003e5324d79a3/aimmo/models.py#L61)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

do we need to specify cascade deletes here too?
</blockquote></details>

We don't need to for now, but we will in Django 2.0.
So might as well add it now :)
___
*[aimmo/tests/test_migration_game_class.py, line 8 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1386#-MF5g7oz7P5URWVGM0yg:-MFXvHqi88ygxNI-Mh9s:b-eehbdm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/65de4d26538ec84dd813226ef25003e5324d79a3/aimmo/tests/test_migration_game_class.py#L8)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

maybe not a migration test, but can we test what happens when we delete a class too? (or perhaps this is better done at the view level or in portal)
</blockquote></details>

Yeah I reckon it would make more sense to do it in portal

**Review by mrniket — APPROVED** [review]
> Reviewed 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1386)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mrniket — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1386)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
