### PR TITLE
Fix backend inconsistency bug 

### PR DESCRIPTION
**Pull request by OlafSzmidt**
Also adds relevant tests that won't pass second this time creeps up again =)

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/506)

### CODE REVIEW

**Comment by CelineBoudier** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[players/tests.py, line 312 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/506#-L7VIuLC392jfLWUJjKh:-L7VIuLC392jfLWUJjKi:b-9j18r) ([raw file](https://github.com/ocadotechnology/aimmo/blob/aa103bb53edbb5c4d05bd961f41b636ebad383d1/players/tests.py#L312)):*
> ```Python
>         self.assertEqual(second_id, 2)
> 
>     def test_current_avatar_api_returns_404_for_logged_out_user(self):
> ```

<nitpicking> test_current_avatar_api_call_returns... might be better and more explicit? </nitpicking>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/506)*

**Comment by OlafSzmidt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[players/tests.py, line 312 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/506#-L7VIuLC392jfLWUJjKh:-L7VKhE_jSUeCSxnB1l1:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/aa103bb53edbb5c4d05bd961f41b636ebad383d1/players/tests.py#L312)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

<nitpicking> test_current_avatar_api_call_returns... might be better and more explicit? </nitpicking>
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/506)*

**Comment by CelineBoudier** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/506)*

**Comment by CelineBoudier** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/506#-:-L7VNDjLJGiuTQF9btJd:bnfp4nl)*

**Pull request merged**
