### PR TITLE
fix: Validate the unique_together constraint in AddGameForm

### PR DESCRIPTION
**Pull request by mrniket**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1417)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1417#-:-MM0alxs76kXibSofvPU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrniket)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1417)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1417#-MM0rhoXBqEqa6_rYWDk:-MM0rhoY74-NEtOHxG1T:bovn4ix) (no related file):*
I think you'll have to make the changes in Cypress too

---

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1417)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @faucomte97 and @mrniket)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1417#-MM0rhoXBqEqa6_rYWDk:-MM153Wb5N_2lR5B-xUH:b-896fix) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I think you'll have to make the changes in Cypress too
</blockquote></details>

Done.

---

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1417)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[aimmo/serializers.py, line 1 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1417#-MM152MHEhChQQ7R3Iq5:-MM152MHEhChQQ7R3Iq6:b-r0ts97) ([raw file](https://github.com/ocadotechnology/aimmo/blob/64d6750bc4f067263daa7f24ff74c762e8acb2c3/aimmo/serializers.py#L1)):*
> ```Python
> from aimmo.models import Game
> ```

imports need organising I think

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1417)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo/serializers.py, line 1 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1417#-MM152MHEhChQQ7R3Iq5:-MM15VF47U9kZYak52Fd:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/64d6750bc4f067263daa7f24ff74c762e8acb2c3/aimmo/serializers.py#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

imports need organising I think
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1417#-:-MM15bR-3CgQbXAFmM-R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
