### PR TITLE
feat: Class game permissions

### PR DESCRIPTION
**Pull request by mrniket**
BREAKING CHANGE: The game form now requires you to specify a class to associate with the game. 

The example_project now incorporates the whole site (portal + game) so we don't need to maintain another flow for development.

The `can_play` field in Game is no longer used. 

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: all files reviewed, 5 unresolved discussions (waiting on @mrniket)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNGwb-AHGPVx4qczxy:-MGNGwb-AHGPVx4qczxz:bs0sg2j) (no related file):*
Do we also want to remove the old aimmo pages (ie home page, create game page, stats page, etc) or leave it for another PR?

---
___
*[aimmo/test_settings.py, line 14 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNGsgqEYXXELZj7x1Y:-MGNGsgqEYXXELZj7x1Z:bhacbqs) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/aimmo/test_settings.py#L14)):*
> ```Python
>     "django.contrib.auth",
>     "portal",
>     "aimmo",
> ```

We don't need aimmo if we have portal right?
___
*[aimmo/templatetags/players_utils.py, line 4 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNFkrhAQdxAOKcf7Bv:-MGNFkrhAQdxAOKcf7Bw:bh19k6k) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/aimmo/templatetags/players_utils.py#L4)):*
> ```Python
> from django import template
> 
> from portal.permissions import logged_in_as_student, logged_in_as_teacher
> ```

import from portal
___
*[aimmo/templatetags/players_utils.py, line 21 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNGb2k4fMtiHLPGnpB:-MGNGb2k4fMtiHLPGnpC:bwaokcp) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/aimmo/templatetags/players_utils.py#L21)):*
> ```Python
>         playable_games = Game.objects.none()
>         for klass in user.userprofile.teacher.class_teacher.all():
>             playable_games |= klass.games_for_class.all()
> ```

Should the operator here be `+=` instead of `|=` ?
___
*[example_project/example_project/urls.py, line 5 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNGp344Mc5TkEOvuBa:-MGNGp344Mc5TkEOvuBb:b-4ujvf9) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/example_project/example_project/urls.py#L5)):*
> ```Python
> from django.contrib import admin
> from game import urls as game_urls
> from portal import urls as portal_urls
> ```

Importing portal URLs but not using them?

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: all files reviewed, 5 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[aimmo/templatetags/players_utils.py, line 21 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNGb2k4fMtiHLPGnpB:-MGO1EbWDJJTM0csJDBa:bycrw3b) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/aimmo/templatetags/players_utils.py#L21)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Should the operator here be `+=` instead of `|=` ?
</blockquote></details>

django has overloaded the | operator here to be "union" 2 sets together  (afaik you can't add two querysets together)
___
*[example_project/example_project/urls.py, line 5 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNGp344Mc5TkEOvuBa:-MGO1VVQBoRcO2nij9BY:bto0pmv) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/example_project/example_project/urls.py#L5)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Importing portal URLs but not using them?
</blockquote></details>

they are used, check again :wink:

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[example_project/example_project/urls.py, line 5 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNGp344Mc5TkEOvuBa:-MGO9tba5za2fhQy1dca:bi1jhey) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/example_project/example_project/urls.py#L5)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

they are used, check again :wink: 
</blockquote></details>

Am blind :roll_eyes:

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: all files reviewed, 7 unresolved discussions (waiting on @mrniket)

___
*[aimmo/urls.py, line 20 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOJlVPEUbhEoEij3fn:-MGOJlVPEUbhEoEij3fo:bu18phe) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/aimmo/urls.py#L20)):*
> ```Python
>     url(
>         r"^$",
>         login_required(TemplateView.as_view(template_name="players/home.html")),
> ```

Can we also delete this one?
___
*[aimmo/tests/test_forms.py, line 34 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOL2aBBWJF5lmSd38A:-MGOL2aBBWJF5lmSd38B:b4zsduk) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_forms.py#L34)):*
> ```Python
> @pytest.fixture
> def worksheet(db) -> Worksheet:
>     return Worksheet.objects.create(name="Test worksheet", starter_code="Trout")
> ```

Lol :fish: 
___
*[aimmo/tests/test_forms.py, line 68 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOLSps3ZXi23BafD8a:-MGOLSps3ZXi23BafD8b:b-lt579e) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_forms.py#L68)):*
> ```Python
>     )
>     _ = form.save()
>     assert form.errors == {}
> ```

How come this is an empty dict?
___
*[aimmo/tests/test_models.py, line 11 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOLbRjCLpZRRfT9T99:-MGOLbRjCLpZRRfT9T9A:bphrjid) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_models.py#L11)):*
> ```Python
> )
> app_settings.GAME_SERVER_PORT_FUNCTION = lambda game_id: 0
> app_settings.GAME_SERVER_SSL_FLAG = True
> ```

Test file without any tests?
___
*[aimmo/tests/test_views.py, line 65 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOM5ZpDHKwknV9jWoB:-MGOM5ZpDHKwknV9jWoC:b2nhkfj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_views.py#L65)):*
> ```Python
>         user_profile.save()
>         teacher: Teacher = Teacher.objects.create(
>             user=user_profile, new_user=cls.user, title="Mx"
> ```

Mx?

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: 16 of 18 files reviewed, 7 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[aimmo/tests/test_forms.py, line 68 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOLSps3ZXi23BafD8a:-MGOVCZxCZjGDm92ml5h:b5u8jeu) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_forms.py#L68)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

How come this is an empty dict?
</blockquote></details>

because the test doesn't work yet 😛 , sorry, shouldn't have committed this yet
___
*[aimmo/tests/test_models.py, line 11 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOLbRjCLpZRRfT9T99:-MGOVNJG4KM17TudX0o9:bif9nx3) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_models.py#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Test file without any tests?
</blockquote></details>

in progress too
___
*[aimmo/tests/test_views.py, line 65 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOM5ZpDHKwknV9jWoB:-MGOVQIZ4UU5OURhFUkI:b5v360u) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_views.py#L65)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Mx?
</blockquote></details>

https://www.wikiwand.com/en/Mx_(title)#:~:text=Mx%20(usually%20pronounced%20%2Fm%C9%AA,that%20does%20not%20indicate%20gender.

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 16 of 16 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: all files reviewed, 5 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[aimmo/tests/test_forms.py, line 51 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGnf7SZ9uAVb7ykhX4Q:-MGnf7S_3FNWoNGE-LKl:bajb8h0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b2a4006a0a7892ddd4536b76097faa8cbb22f744/aimmo/tests/test_forms.py#L51)):*
> ```Python
> 
> @pytest.mark.django_db
> def test_form_with_non_existing_class_and_worksheet():
> ```

I wonder if this should be two separate tests, or at least two separate checks in the test?
For example, say the form suddenly starts working with nonexistent worksheets, this test would still pass cos of the non existent game and we wouldn't necessarily catch it
___
*[aimmo/tests/test_views.py, line 51 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGngF_58fb0O12XoPOd:-MGngF_60To8RmYc_TNM:b-lpa4vl) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b2a4006a0a7892ddd4536b76097faa8cbb22f744/aimmo/tests/test_views.py#L51)):*
> ```Python
>         "status": "r",
>         "settings": '{"GENERATOR": "Main", "OBSTACLE_RATIO": 0.1, "PICKUP_SPAWN_CHANCE": 0.1, "SCORE_DESPAWN_CHANCE": 0.05, "START_HEIGHT": 31, "START_WIDTH": 31, "TARGET_NUM_CELLS_PER_AVATAR": 16.0, "TARGET_NUM_PICKUPS_PER_AVATAR": 1.2, "TARGET_NUM_SCORE_LOCATIONS_PER_AVATAR": 0.5}',
>         "worksheet_id": "3",
> ```

Why change it to 3?

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: 25 of 28 files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[aimmo/test_settings.py, line 14 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNGsgqEYXXELZj7x1Y:-MGmuB66D26oY3F2W7HI:bx0cs48) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/aimmo/test_settings.py#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

We don't need aimmo if we have portal right?
</blockquote></details>

Correct 😊 
___
*[aimmo/urls.py, line 20 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOJlVPEUbhEoEij3fn:-MGmvRASBmdQwoo8yODh:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/aimmo/urls.py#L20)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Can we also delete this one?
</blockquote></details>

Done.
___
*[aimmo/templatetags/players_utils.py, line 4 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNFkrhAQdxAOKcf7Bv:-MGqs6A5DrXEcFFrZOXf:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/9037443c4ae8ca2640a49335d603f7a9e37a43d2/aimmo/templatetags/players_utils.py#L4)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

import from portal
</blockquote></details>

Done.
___
*[aimmo/tests/test_forms.py, line 51 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGnf7SZ9uAVb7ykhX4Q:-MGqxZ5V-M64Wk3mbdRk:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b2a4006a0a7892ddd4536b76097faa8cbb22f744/aimmo/tests/test_forms.py#L51)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I wonder if this should be two separate tests, or at least two separate checks in the test?
For example, say the form suddenly starts working with nonexistent worksheets, this test would still pass cos of the non existent game and we wouldn't necessarily catch it
</blockquote></details>

Done.
___
*[aimmo/tests/test_models.py, line 11 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOLbRjCLpZRRfT9T99:-MGqxhxg-i1ugJQ20BwX:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_models.py#L11)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

in progress too
</blockquote></details>

Done.
___
*[aimmo/tests/test_views.py, line 51 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGngF_58fb0O12XoPOd:-MGqxjCM30QLR3SBdFz_:b-qu5ml2) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b2a4006a0a7892ddd4536b76097faa8cbb22f744/aimmo/tests/test_views.py#L51)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why change it to 3?
</blockquote></details>

The way these tests were made meant that they have shared state in between them (see setupTestData). Unfortunately, whilst the test remains deterministic, the id changes if something else changes. In order to reduce the scope of this task, I'm just changing the id here for now.

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: 23 of 30 files reviewed, 4 unresolved discussions (waiting on @faucomte97)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGNGwb-AHGPVx4qczxy:-MGqyhxo1gLwEzgmnIMN:b-sodaa1) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we also want to remove the old aimmo pages (ie home page, create game page, stats page, etc) or leave it for another PR?
</blockquote></details>

We do, wasn't quite sure if  I should do it in this PR but I did it :thumbsup: 

---

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[aimmo/tests/test_models.py, line 11 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOLbRjCLpZRRfT9T99:-MGr99HoCEin2rJOsaBH:b-v50puo) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_models.py#L11)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm a bit confused as to where these model tests have moved to now, it looks like you've deleted both `test_models` and `tests_models`?

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: 29 of 30 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo/tests/test_models.py, line 11 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-MGOLbRjCLpZRRfT9T99:-MGw94GeC1AGEp41ftp6:b-9r89q9) ([raw file](https://github.com/ocadotechnology/aimmo/blob/001d965872fc711b37e02fffa1d71f7106e1148e/aimmo/tests/test_models.py#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I'm a bit confused as to where these model tests have moved to now, it looks like you've deleted both `test_models` and `tests_models`?
</blockquote></details>

I renamed tests_models.py to test_models.py because it turned out pytest wasn't running them in the first place. Then I looked at what test_models.py is actually testing, and it's testing the permissions for the game. I believe that this is well tested in other tests on a high level so I deleted the tests and then the file.

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1390#-:-MGxwqArCGL_zQnu-nfL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
