### PR TITLE
fix: show pickups on map

### PR DESCRIPTION
**Pull request by razvan-pro**
Game settings are now set in the annotation of the allocation by the game creator and will later be fetched by the game. This should fix the pickups not showing on the map.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1477)

### CODE REVIEW

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1477)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[aimmo-game/service.py, line 178 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1477#-MV0icTY2bALx7c6TJdN:-MV0icTY2bALx7c6TJdO:bso88e5) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b4734ecdf808b9996163ac0bdcc812bd5c6a2e24/aimmo-game/service.py#L178)):*
> ```
> generator = getattr(map_generator, settings["GENERATOR"])(settings)
> ```
Is this the first time the map is created, or is it taking an existing generator? If it's the former, can we do this instead? 

`generator = map_generator.Main(settings)`

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1477)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[aimmo-game/service.py, line 178 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1477#-MV0icTY2bALx7c6TJdN:-MV0yYYb7Gwkvn_hm0ZZ:b-l0ebkk) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b4734ecdf808b9996163ac0bdcc812bd5c6a2e24/aimmo-game/service.py#L178)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> generator = getattr(map_generator, settings["GENERATOR"])(settings)
> ```
Is this the first time the map is created, or is it taking an existing generator? If it's the former, can we do this instead? 

`generator = map_generator.Main(settings)`

</blockquote></details>

Yep, I think this is the first time it's created, but the `Main` bit is taken from settings instead - I'm not sure exactly why, but I assume it's so worksheets/games can support different generators in the future. I actually took this from a previous Agones commit: edc731de8a4f5222253c69f0e41c1db96e1b556b :slightly_smiling_face:

**Review by dionizh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1477)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[aimmo-game/service.py, line 178 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1477#-MV0icTY2bALx7c6TJdN:-MV10MTYCkuHXaBhW9jX:b-vqd8qv) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b4734ecdf808b9996163ac0bdcc812bd5c6a2e24/aimmo-game/service.py#L178)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Yep, I think this is the first time it's created, but the `Main` bit is taken from settings instead - I'm not sure exactly why, but I assume it's so worksheets/games can support different generators in the future. I actually took this from a previous Agones commit: edc731de8a4f5222253c69f0e41c1db96e1b556b :slightly_smiling_face: 
</blockquote></details>

I see, so it changed and you changed it back. Okay I think it's fine for now but this might be something we need to keep an eye on 😁

**Review by dionizh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1477)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dionizh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1477#-:-MV11cDv0REkY9-pjeys:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dionizh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1477)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
