### PR TITLE
Add code climate #229

### PR DESCRIPTION
**Pull request by dionisioC**
This is the config needed (mainly) to configure code climate.

GPA and issues are working as you can see here

https://github.com/dionisioC/aimmo/tree/Add_CodeClimate_%23229

Coverage needs to be configured in travis (done) but I can't test it

The url for the badges must be changed for the ones of the official account

### CODE REVIEW

**Comment by dionisioC** [comment]
The build is mistakenly passing, seems like the result of the coverage analysis are not found, do you know where are them?

**Comment by danalex97** [comment]
@dionisioC Maybe you need to add some other flags in the `all_test.py` file. For example [here](https://pypi.python.org/pypi/python-coveralls/) they have a `--pep8` flag. Sorry if is not this, I don't have much experience with this kind of stuff.

**Comment by dionisioC** [comment]
In theory that is handled by a codeclimate engine (.codeclimate.yml)
  pep8:
    enabled: true

A file with the test coverage analisys should be generated in some part, but I am not able to find it

codeclimate GPA and issues are working, coverage is not yet.

I will check that. Thanks for the help!

**Comment by OlafSzmidt** [comment]
Any updates @dionisioC?

**Comment by dionisioC** [comment]
No, I haven't have time to check @danalex97 suggestion

**Comment by dionisioC** [comment]
Last 3 thing I tested didn't work

**Comment by dionisioC** [comment]
I added debug , bu t I hve no clue on what is waiting for, if there is no clue on how to fix this I will close the pull request so other person can do it

**Pull request closed without merging**
