### PR TITLE
fix: read default starter code from worksheets

### PR DESCRIPTION
**Pull request by mrniket**
Signed-off-by: Niket <niket.shah1@ocado.com>

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1399)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[aimmo/game_creator.py, line 40 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1399#-MI-PGZb94RaaHlZwrlw:-MI-PGZc8FzbCMXubAqB:b-16p7vx) ([raw file](https://github.com/ocadotechnology/aimmo/blob/028a9129ac47e4cb375b868ac52a8facfa5fa22e/aimmo/game_creator.py#L40)):*
> ```Python
>     :param user: The user the Avatar is for.
>     :param game_id: The id of the game in which the Avatar is created.
>     :param avatar_template_name: Optional. The name of the default code template for
> ```

Remove this plz

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1399)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo/game_creator.py, line 40 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1399#-MI-PGZb94RaaHlZwrlw:-MI-SJ753zRVhxYjPEN4:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/028a9129ac47e4cb375b868ac52a8facfa5fa22e/aimmo/game_creator.py#L40)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove this plz
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1399#-:-MI-TMbE09XMY0FgEW6i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1399)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
