### PR TITLE
feat: validate imports

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1838)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1838)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`game_frontend/src/pyodide/syntax.ts` line 93 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1838#-NkK_06u5z8av_F7oiyc:-NkK_06u5z8av_F7oiyd:bscmbzy) ([raw file](https://github.com/ocadotechnology/aimmo/blob/c5b95a59d2ab6ac430f0b3f5022761293133f1cb/game_frontend/src/pyodide/syntax.ts#L93)):*
> ```XML
> 
>   const fromImports: Record<string, Set<string>> = {};
>   for (const match of code.matchAll(pattern)) {
> ```

Do you need this for loop? Could we do something like this? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1838)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`game_frontend/src/pyodide/syntax.ts` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1838#-NkKcJ3TD4pWRbagepPg:-NkKcJ3TD4pWRbagepPh:b-e6by5f) ([raw file](https://github.com/ocadotechnology/aimmo/blob/c5b95a59d2ab6ac430f0b3f5022761293133f1cb/game_frontend/src/pyodide/syntax.ts#L11)):*
> ```XML
>   lineStart: boolean
>   captureName: boolean
>   captureArgs: boolean
> ```

Are these ever true at any point? If not, do we need them as args?



_Code quote:_
```XML
  lineStart: boolean
  captureName: boolean
  captureArgs: boolean
```

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1838)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`game_frontend/src/pyodide/syntax.ts` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1838#-NkKcJ3TD4pWRbagepPg:-NkKd8Z89dIFPmJK9x6P:bxw4fex) ([raw file](https://github.com/ocadotechnology/aimmo/blob/c5b95a59d2ab6ac430f0b3f5022761293133f1cb/game_frontend/src/pyodide/syntax.ts#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Are these ever true at any point? If not, do we need them as args?
</blockquote></details>

not currently. I made them as args in a callable because if in the future we ever need to match a function signature, I would like us to reuse this rather than repeating pattern with slick tweaks each time.
___
*[`game_frontend/src/pyodide/syntax.ts` line 93 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1838#-NkK_06u5z8av_F7oiyc:-NkKdoTl-CWcpN46cTXq:br8ejud) ([raw file](https://github.com/ocadotechnology/aimmo/blob/c5b95a59d2ab6ac430f0b3f5022761293133f1cb/game_frontend/src/pyodide/syntax.ts#L93)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do you need this for loop? Could we do something like this? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll
</blockquote></details>

yes, it's needed because we process each match differently depending on the type of match. see the further processing inside the enclosed if/else statements

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1838#-:-NkKfYoD1XVozUSNeuP_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1838)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
