### PR TITLE
Move logic outside world map

### PR DESCRIPTION
**Pull request by mrniket**
See #534 and it's epic for info

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/544)

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[aimmo-game/simulation/action.py, line 135 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/544#-LAxLN4x4LAf69LjWYXV:-LAxLN4x4LAf69LjWYXW:b-ldpxwm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/dd4b1ccf857a3b797a4f5ca54932df991bcc527a/aimmo-game/simulation/action.py#L135)):*
> ```Python
>             respawn_location = world_map.get_random_spawn_location()
>             attacked_avatar.die(respawn_location)
>             # TODO this logic shouldn't be here
> ```

Issue and comment out instead

---

*[aimmo-game/simulation/world_map.py, line 133 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/544#-LAxLZMXByWKvt3dsQdT:-LAxLZMXByWKvt3dsQdU:bvjqv39) ([raw file](https://github.com/ocadotechnology/aimmo/blob/dd4b1ccf857a3b797a4f5ca54932df991bcc527a/aimmo-game/simulation/world_map.py#L133)):*
> ```Python
>                 pass
> 
>     # TODO this is game logic
> ```

As before, issue and comment out perhaps?

---

*[aimmo-game/simulation/world_map.py, line 150 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/544#-LAxLcn-7mDmfEBTEY80:-LAxLcn-7mDmfEBTEY81:bs0umy0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/dd4b1ccf857a3b797a4f5ca54932df991bcc527a/aimmo-game/simulation/world_map.py#L150)):*
> ```Python
>                 and len(cell.moves) <= 1)
> 
>     # TODO this is game logic
> ```

As before

---

*[aimmo-game/simulation/world_map.py, line 173 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/544#-LAxLbiW7UVUTCGlPHZc:-LAxLbiW7UVUTCGlPHZd:bs0umy0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/dd4b1ccf857a3b797a4f5ca54932df991bcc527a/aimmo-game/simulation/world_map.py#L173)):*
> ```Python
>         return self.settings['NO_FOG_OF_WAR_DISTANCE']
> 
>     # TODO this is game logic
> ```

As before

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/544)*

**Comment by mrniket** [comment]
The comments were for working out what needed to be done, I have removed them now. The issues have already been created and are part of the epic this task is in

---

Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/544#-:-LAxl-s41f8c6ELFsko2:b-q8nx4v)*

**Comment by mrniket** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[aimmo-game/simulation/world_map.py, line 133 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/544#-LAxLZMXByWKvt3dsQdT:-LAxlKO1AjHCZzcA64BO:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/dd4b1ccf857a3b797a4f5ca54932df991bcc527a/aimmo-game/simulation/world_map.py#L133)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

As before, issue and comment out perhaps?
</blockquote></details>

Done.

---

*[aimmo-game/simulation/world_map.py, line 150 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/544#-LAxLcn-7mDmfEBTEY80:-LAxlKkN916kn0GSrGP2:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/dd4b1ccf857a3b797a4f5ca54932df991bcc527a/aimmo-game/simulation/world_map.py#L150)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

As before
</blockquote></details>

Done.

---

*[aimmo-game/simulation/world_map.py, line 173 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/544#-LAxLbiW7UVUTCGlPHZc:-LAxlPW46y2Ov62blEYQ:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/dd4b1ccf857a3b797a4f5ca54932df991bcc527a/aimmo-game/simulation/world_map.py#L173)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

As before
</blockquote></details>

Done.

---

*[aimmo-game/simulation/action.py, line 135 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/544#-LAxLN4x4LAf69LjWYXV:-LAxlQ8kE-Myk0Qza1-2:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/dd4b1ccf857a3b797a4f5ca54932df991bcc527a/aimmo-game/simulation/action.py#L135)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

Issue and comment out instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/544)*

**Comment by mrniket** [comment]
Reviewed 1 of 10 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/544)*

**Comment by OlafSzmidt** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/544)*

**Pull request merged**
