### PR TITLE
fix: update unit tests to pytest

### PR DESCRIPTION
**Pull request by dionizh**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1497)

### CODE REVIEW

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1497)* status: all files reviewed, 2 unresolved discussions (waiting on @dionizh)

___
*[aimmo-game-worker/setup.py, line 19 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1497#-MWxvqx6EOdw-prnSNaF:-MWxvqx70P0o5x-N-C_f:b-y9u0f0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/62716220f24392bc2b47f685e950243bc75bc35e/aimmo-game-worker/setup.py#L19)):*
> ```Python
> 
> setup(
>     name="aimmo-game-worker",
> ```

Maybe we shouldn't change the name just now :slightly_smiling_face: There are a few references we'll need to change if we do (search in project for `aimmo_avatar_api`)

Also, the package has already been published so far with this name, it can be quite confusing to change it now :slightly_smiling_face: 
___
*[aimmo-game-worker/setup.py, line 29 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1497#-MWxwG9F6VvUIr0e8Pc-:-MWxwG9F6VvUIr0e8Pc0:bswnqvy) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d274fc49eca62c9ebee1e908cff0d568dc646d96/aimmo-game-worker/setup.py#L29)):*
> ```Python
>         "Operating System :: OS Independent",
>     ],
>     python_requires=">=3.6",
> ```

Do we have to remove `version`, `classifiers` and `python_requires`? :thinking:  I think they're good to keep.

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1497)* status: all files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

___
*[aimmo-game-worker/setup.py, line 19 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1497#-MWxvqx6EOdw-prnSNaF:-MWyA_buDAI8jQYIddc6:bhwp9gd) ([raw file](https://github.com/ocadotechnology/aimmo/blob/62716220f24392bc2b47f685e950243bc75bc35e/aimmo-game-worker/setup.py#L19)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Maybe we shouldn't change the name just now :slightly_smiling_face: There are a few references we'll need to change if we do (search in project for `aimmo_avatar_api`)

Also, the package has already been published so far with this name, it can be quite confusing to change it now :slightly_smiling_face: 
</blockquote></details>

Oh oops. Yea I can see it's breaking cypress test xD
___
*[aimmo-game-worker/setup.py, line 29 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1497#-MWxwG9F6VvUIr0e8Pc-:-MWyAdqO-NKro3U1dxXS:b-p03vwy) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d274fc49eca62c9ebee1e908cff0d568dc646d96/aimmo-game-worker/setup.py#L29)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Do we have to remove `version`, `classifiers` and `python_requires`? :thinking:  I think they're good to keep.
</blockquote></details>

I copied the setup.py in aimmo-game and over there these don't exist, so I just thought to clean it up. Ok `version` might be used. The `python_requires` shouldn't be needed though, right? As that is older than the version we're supposed to use anyway?

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1497)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[aimmo-game-worker/setup.py, line 19 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1497#-MWxvqx6EOdw-prnSNaF:-MWyFPQGDEbSzj0jW_W-:be0530r) ([raw file](https://github.com/ocadotechnology/aimmo/blob/62716220f24392bc2b47f685e950243bc75bc35e/aimmo-game-worker/setup.py#L19)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Oh oops. Yea I can see it's breaking cypress test xD
</blockquote></details>

:grin: 
___
*[aimmo-game-worker/setup.py, line 29 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1497#-MWxwG9F6VvUIr0e8Pc-:-MWyFdXl916uKaY-iTlL:b-9g52cj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/d274fc49eca62c9ebee1e908cff0d568dc646d96/aimmo-game-worker/setup.py#L29)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

I copied the setup.py in aimmo-game and over there these don't exist, so I just thought to clean it up. Ok `version` might be used. The `python_requires` shouldn't be needed though, right? As that is older than the version we're supposed to use anyway?
</blockquote></details>

I think `classifiers` and `python_requires` are just for the PyPI page: https://pypi.org/project/aimmo-avatar-api/ Not bad to keep them I think :slightly_smiling_face:

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1497)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[aimmo_runner/build_worker_wheel.sh, line 11 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1497#-MWyS3tL3RfuBiF19ve3:-MWyS3tL3RfuBiF19ve4:b9g5vil) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e37e8511d54de5c268beb684c3e7a06238201d57/aimmo_runner/build_worker_wheel.sh#L11)):*
> ```Shell
> # Copy wheel to django's static directory
> mkdir -p aimmo/static/worker/
> cp aimmo-game-worker/dist/*.whl aimmo/static/worker/
> ```

It's probably safer to keep the hardcoded path here instead of * since we use the same one in frontend (`webWorker.ts`) - what do you think? (we'll also have a better idea from where that static `.whl` comes from in the frontend :slightly_smiling_face:)

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1497)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[aimmo_runner/build_worker_wheel.sh, line 11 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1497#-MWyS3tL3RfuBiF19ve3:-MWyXpni2oOkBUm36Hgt:bybr0v5) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e37e8511d54de5c268beb684c3e7a06238201d57/aimmo_runner/build_worker_wheel.sh#L11)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

It's probably safer to keep the hardcoded path here instead of * since we use the same one in frontend (`webWorker.ts`) - what do you think? (we'll also have a better idea from where that static `.whl` comes from in the frontend :slightly_smiling_face:)
</blockquote></details>

Well this came up when I was testing the friendly module console by adding more whl files and then thought it'd be nice for the command to just copy all whl over. And with this we also remove one more place where the version is hardcoded 😀

**Review by razvan-pro — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

___
*[aimmo_runner/build_worker_wheel.sh, line 11 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1497#-MWyS3tL3RfuBiF19ve3:-MWyfjc8BGZS22gVJR52:b-wjcl88) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e37e8511d54de5c268beb684c3e7a06238201d57/aimmo_runner/build_worker_wheel.sh#L11)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Well this came up when I was testing the friendly module console by adding more whl files and then thought it'd be nice for the command to just copy all whl over. And with this we also remove one more place where the version is hardcoded 😀
</blockquote></details>

Ah, I see, ok :smile:

**Review by razvan-pro — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Pull request merged**
