### PR TITLE
changed the text in home - fixes #595

### LINKED ISSUE #595: Update the aimmo main page so it tells you to go to play/aimmo

### PR DESCRIPTION
**Pull request by CelineBoudier**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/596)

### CODE REVIEW

**Comment by j4mesholland** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[players/templates/players/home.html, line 7 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/596#-LD2gMUL4G1h_EMM5OMs:-LD2gMUL4G1h_EMM5OMt:b308xm8) ([raw file](https://github.com/ocadotechnology/aimmo/blob/72bce72832aeefb0574b31a4b83272b64d00432f/players/templates/players/home.html#L7)):*
> ```HTML
>     <p>AI:MMO is a <strong>M</strong>assively <strong>M</strong>ultiplayer <strong>O</strong>nline game, where players
>         create <strong>A</strong>rtificially <strong>I</strong>ntelligent programs to play on their behalf.</p>
>     <p>Are you interested to know more about AI:MMO and trying it out? <a href="https://www.codeforlife.education/play/aimmo/">Find out more and register your interest on our main website.</a></p>
> ```


<p>Are you interested in learning more about AI:MMO and would like to try it out? <a href="https://www.codeforlife.education/play/aimmo/">Find out more and register your interest on our main website.</a></p>

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/596)*

**Comment by j4mesholland** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/596#-:-LD2jZQ29-xM1NQ2QbzC:bnfp4nl)*

**Comment by CelineBoudier** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[players/templates/players/home.html, line 7 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/596#-LD2gMUL4G1h_EMM5OMs:-LD2jxEj1n0kiPvdODF3:bb7f2mf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/72bce72832aeefb0574b31a4b83272b64d00432f/players/templates/players/home.html#L7)):*
<details><summary><i>Previously, j4mesholland (James Holland) wrote…</i></summary><blockquote>

<p>Are you interested in learning more about AI:MMO and would like to try it out? <a href="https://www.codeforlife.education/play/aimmo/">Find out more and register your interest on our main website.</a></p>
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/596)*

**Comment by j4mesholland** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/596)*

**Pull request merged**
