### PR TITLE
feat: Remove worksheet model

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1587)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1587)* status: all files reviewed, 13 unresolved discussions (waiting on @razvan-pro)

___
*[aimmo/worksheets.py, line 44 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotRsG0Cx1ZnSEwQXDp:-MotRsG0Cx1ZnSEwQXDq:bimm8k9) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L44)):*
> ```Python
> #    Task 3: Investigate location
> #       - Investigate what `print(avatar_state.location)` tells you and then
> #         check if you can move to the next location 
> ```

Extra whitespaces :stuck_out_tongue: 
___
*[aimmo/worksheets.py, line 46 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotRvSP68SikXR0kZ6t:-MotRvSP68SikXR0kZ6u:b-k8hnss) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L46)):*
> ```Python
> #         check if you can move to the next location 
> #
> #  New commands: 
> ```

Extra whitespaces part 2
___
*[aimmo/worksheets.py, line 66 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotSX7m6ODtpNycC6IB:-MotSX7m6ODtpNycC6IC:b-sprf8m) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L66)):*
> ```
>         student_pdf_name="Kurono_challenge_1",
>         teacher_pdf_name="Kurono_teacher_guide_1",
> ```
Not blocking, but making a note here that we probably will need to replace these PDF links with direct links to the Gitbook pages. Not sure when we're planning on doing that though.
___
*[aimmo/worksheets.py, line 80 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotShew8yYz_twVbLD6:-MotShew8yYz_twVbLD7:b-k8hnsr) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L80)):*
> ```Python
> #         PickupAction() instead of a MoveAction(DIRECTION).
> #
> #  New commands: 
> ```

Extra whitespaces part 3
___
*[aimmo/worksheets.py, line 90 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotSovd7DaJfqVG3NWn:-MotSovd7DaJfqVG3NWo:b-k8hnsq) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L90)):*
> ```Python
> import random
> 
> def next_turn(world_state, avatar_state): 
> ```

Extra whitespaces part 4
___
*[aimmo/worksheets.py, line 91 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotSrJ155gLKew7611Q:-MotSrJ155gLKew7611R:b-k8hnsp) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L91)):*
> ```Python
> 
> def next_turn(world_state, avatar_state): 
>     #  Choose a random direction to move in 
> ```

Extra whitespaces part 5
___
*[aimmo/worksheets.py, line 102 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotT1OD4qOUJXp7CUIq:-MotT1OD4qOUJXp7CUIr:b6yazrt) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L102)):*
> ```
>     #  Get details about the location
>     #  you would move onto
> ```
Could this comment be put on one line?
___
*[aimmo/worksheets.py, line 113 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotT9U-EAN9gX2HOwhW:-MotT9U-EAN9gX2HOwhX:b-mi71o3) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L113)):*
> ```Python
> """,
>         active_image_path="images/worksheets/future2_active.png",
>         description="Now that you know how to navigate, it’s time to clean up the evidence before leaving this timeline!  Some of the artefacts escaped the vortex and ended up all over the museum - if each of you picks ten of them up, you should be done in time to embark in your journey. But beware! The blue artefacts will need to be separated from the red ones, as they have opposing magnetic fields. Can you tell which one is what type?",
> ```

Two spaces between `timeline!` and `Some` I think
This description is also outdated, worksheet 2 only deals with picking up 1 artefact, and there are no artefact types yet :grimacing: 
___
*[aimmo/worksheets.py, line 140 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotTc_k4gKN9DkrDXUY:-MotTc_k4gKN9DkrDXUZ:b-k8hnso) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L140)):*
> ```Python
> #       - Pick up five artefacts on the board. Check your backpack to see how
> #         many you are holding using `avatar_state.backpack`. Output a message
> #         when you have picked up five. 
> ```

Extra whitespaces part 6
___
*[aimmo/worksheets.py, line 149 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotTgtQ76ArXD3_hN8s:-MotTgtQ76ArXD3_hN8t:b-k8hnsn) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L149)):*
> ```Python
> #         `artefact.type` as above. e.g. I have 3 keys and 2 chests.
> #
> #  New commands: 
> ```

Extra whitespaces part 7
___
*[aimmo/worksheets.py, line 172 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotTlvs4lbg89Ji24CI:-MotTlvs4lbg89Ji24CJ:b-no5qtc) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L172)):*
> ```Python
> """,
>         active_image_path="images/worksheets/ancient_active.png",
>         description="You are now familiar with your equipment and have managed to unlock the gateway to the first time checkpoint. You find yourself in a strange place, full of familiar structures in the form of ruins. After a few minutes, you hear steps and realise you’re not alone! No time to move around aimlessly now, or you might run into someone! Use your navigating system to scan your surroundings and move only towards the artefacts you want to pick up. Be stealthy!",
> ```

This description is also outdated :confused: It was for when we were thinking of adding a `SneakAction()`. The description about picking up multiple artefacts and checking the types from worksheet 2 (and tweaking it a bit) should work here :stuck_out_tongue: 
___
*[aimmo/worksheets.py, line 263 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotUjXH3X03HcjuE0hn:-MotUjXI458VIiI9rG4t:bxjzeiy) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L263)):*
> ```Python
> 
> 
> def get_worksheets_excluding_id(id: int) -> List[Worksheet]:
> ```

Just checking, is this used anywhere?
___
*[aimmo/migrations/0026_remove_worksheets.py, line 16 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotUNY55Pqql70QB5tm:-MotUNY55Pqql70QB5tn:b-incp36) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/migrations/0026_remove_worksheets.py#L16)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         migrations.AlterField(
>             model_name="game",
>             name="auth_token",
>             field=models.CharField(blank=True, max_length=48),
>         ),
> ```
</details>

Why was the token changed? And how was it changed?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1587)* status: 7 of 9 files reviewed, 13 unresolved discussions (waiting on @faucomte97)

___
*[aimmo/worksheets.py, line 44 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotRsG0Cx1ZnSEwQXDp:-Mp6WELE1VNiA3_FbB92:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L44)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces :stuck_out_tongue: 
</blockquote></details>

Done.
___
*[aimmo/worksheets.py, line 46 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotRvSP68SikXR0kZ6t:-Mp6WEcY4-TKk8dqIV3U:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L46)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces part 2
</blockquote></details>

Done.
___
*[aimmo/worksheets.py, line 66 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotSX7m6ODtpNycC6IB:-Mp6WFOkCL_tvigCn1Aq:b4c9lyr) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L66)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

> ```
>         student_pdf_name="Kurono_challenge_1",
>         teacher_pdf_name="Kurono_teacher_guide_1",
> ```
Not blocking, but making a note here that we probably will need to replace these PDF links with direct links to the Gitbook pages. Not sure when we're planning on doing that though.
</blockquote></details>

:thumbsup: 
___
*[aimmo/worksheets.py, line 80 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotShew8yYz_twVbLD6:-Mp6WTJTCpRsoUrFLWwV:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L80)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces part 3
</blockquote></details>

Done.
___
*[aimmo/worksheets.py, line 90 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotSovd7DaJfqVG3NWn:-Mp6WT_ECwrVMUtPvDDX:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L90)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces part 4
</blockquote></details>

Done.
___
*[aimmo/worksheets.py, line 91 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotSrJ155gLKew7611Q:-Mp6WTld8Go-6t63BqvV:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L91)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces part 5
</blockquote></details>

Done.
___
*[aimmo/worksheets.py, line 102 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotT1OD4qOUJXp7CUIq:-Mp6WUB35IS1Jzb5GUa3:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L102)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

> ```
>     #  Get details about the location
>     #  you would move onto
> ```
Could this comment be put on one line?
</blockquote></details>

Done.
___
*[aimmo/worksheets.py, line 113 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotT9U-EAN9gX2HOwhW:-Mp6X9PY3x8QDs1Z6E_g:bf3is6r) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L113)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Two spaces between `timeline!` and `Some` I think
This description is also outdated, worksheet 2 only deals with picking up 1 artefact, and there are no artefact types yet :grimacing: 
</blockquote></details>

:grimacing: Should we ask Laura if we should update this now?
___
*[aimmo/worksheets.py, line 140 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotTc_k4gKN9DkrDXUY:-Mp6XIJr8Ub8_mNE2Is0:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L140)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces part 6
</blockquote></details>

Done.
___
*[aimmo/worksheets.py, line 149 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotTgtQ76ArXD3_hN8s:-Mp6XKYC3CjEMNle310n:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L149)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces part 7
</blockquote></details>

Done.
___
*[aimmo/worksheets.py, line 172 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotTlvs4lbg89Ji24CI:-Mp6YNjo4WP0HyaO5X2d:b-tdsmq5) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L172)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This description is also outdated :confused: It was for when we were thinking of adding a `SneakAction()`. The description about picking up multiple artefacts and checking the types from worksheet 2 (and tweaking it a bit) should work here :stuck_out_tongue: 
</blockquote></details>

Same question as above - shall we update this now?
___
*[aimmo/worksheets.py, line 263 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotUjXH3X03HcjuE0hn:-Mp6YT1u3BcnS8rDkE7v:bdblt7i) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/worksheets.py#L263)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Just checking, is this used anywhere?
</blockquote></details>

Yep, in portal :slightly_smiling_face: 
___
*[aimmo/migrations/0026_remove_worksheets.py, line 16 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-MotUNY55Pqql70QB5tm:-Mp6YZpU1bBr4imzGggd:b4xxmov) ([raw file](https://github.com/ocadotechnology/aimmo/blob/13d492770424238c00eece5ea51d6e3c86305e35/aimmo/migrations/0026_remove_worksheets.py#L16)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

> ```
>         migrations.AlterField(
>             model_name="game",
>             name="auth_token",
>             field=models.CharField(blank=True, max_length=48),
>         ),
> ```
Why was the token changed? And how was it changed?
</blockquote></details>

Ah, I added a comment to another migration that I deleted. Nothing actually changes, just Django believing it does (it's the blank attr I think, which was always true).

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1587)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1587#-:-MpBH05D7iCcrKbn7UES:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1587)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
