### PR TITLE
feat: add scan_nearby, MoveTowardsAction and A* pathfinding

### PR DESCRIPTION
**Pull request by dionizh**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1481)

### CODE REVIEW

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1481)* status: all files reviewed, 4 unresolved discussions (waiting on @dionizh)

___
*[aimmo-game-worker/simulation/action.py, line 35 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVv8Zj5AdYpibDB4AGZ:-MVv8Zj689HpyXCBqcfp:b-kyexzz) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/action.py#L35)):*
> ```Python
> 
> 
> class MoveTowardsAction(Action):
> ```

We can probably superclass `MoveAction` here if it's the same type to avoid duplicating `serialise`?
___
*[aimmo-game-worker/simulation/pathfinding.py, line 4 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvAoyoE1eQVxCXzXvt:-MVvAoyp0N9mSeUZa4BJ:bsg1rn0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/pathfinding.py#L4)):*
> ```Python
> # and https://gist.github.com/ryancollingwood/32446307e976a11a1185a5394d6657bc
> 
> from warnings import warn
> ```

Interesting, I didn't know about the `warnings` module :slightly_smiling_face: Hopefully this is returned nicely to the user, we'll need to test this.
___
*[aimmo-game-worker/simulation/pathfinding.py, line 45 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvBW7N7p1E6z5o0mQK:-MVvBW7N7p1E6z5o0mQL:by2mgm1) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/pathfinding.py#L45)):*
> ```Python
>     adj = []
>     # we move only in 4 directions
>     for direction in ((0, -1), (0, 1), (-1, 0), (1, 0)):
> ```

Maybe we can use `ALL_DIRECTIONS` here, from `simulation.direction`?
___
*[aimmo-game-worker/simulation/pathfinding.py, line 78 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVv8yXL0ATBP_0HatdH:-MVv8yXL0ATBP_0HatdI:b-pnqqw) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/pathfinding.py#L78)):*
> ```Python
>     # Create start and end node
>     start_node = Node(None, start_cell)
>     start_node.g = start_node.h = start_node.f = 0
> ```

Is this initialisation needed? (same for the below) I see they're being set to 0 in `__init__` above.
___
*[aimmo-game-worker/simulation/world_map.py, line 57 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvC4shBc0DNJw2anzg:-MVvC4shBc0DNJw2anzh:bqluuye) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/world_map.py#L57)):*
> ```Python
> 
>         # useful semi private data for the Action
>         self._path = path  # best path to the artefact
> ```

Should this be moved to `Cell` instead of having a separate class? Maybe named `interactable_path` or something like that.

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1481)* status: all files reviewed, 4 unresolved discussions (waiting on @razvan-pro)

___
*[aimmo-game-worker/simulation/action.py, line 35 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVv8Zj5AdYpibDB4AGZ:-MVva0g89LHDxBB_VWax:bh549uo) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/action.py#L35)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

We can probably superclass `MoveAction` here if it's the same type to avoid duplicating `serialise`?
</blockquote></details>

I was thinking that, but MoveTowardsAction accepts Artefact as parameter while MoveAction works with Direction, so it's probably clearer as a different class?
___
*[aimmo-game-worker/simulation/pathfinding.py, line 4 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvAoyoE1eQVxCXzXvt:-MVvajhF7F8jOR9PCDWd:b5gv1yg) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/pathfinding.py#L4)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Interesting, I didn't know about the `warnings` module :slightly_smiling_face: Hopefully this is returned nicely to the user, we'll need to test this.
</blockquote></details>

It seems to just print out with `UserWarning:` prefix. 

Theoretically in our case there should always be a path to an artefact (so it should never get to the warning, hah), because the map and obstacles are programmed to never be blocking 😁
___
*[aimmo-game-worker/simulation/pathfinding.py, line 45 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvBW7N7p1E6z5o0mQK:-MVvbzLG9p7oVLHu-xZU:b-g1ws5k) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/pathfinding.py#L45)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Maybe we can use `ALL_DIRECTIONS` here, from `simulation.direction`?
</blockquote></details>

Yeap agreed
___
*[aimmo-game-worker/simulation/pathfinding.py, line 78 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVv8yXL0ATBP_0HatdH:-MVvcIVMEjufP5C6jONS:b6zrrk4) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/pathfinding.py#L78)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Is this initialisation needed? (same for the below) I see they're being set to 0 in `__init__` above.
</blockquote></details>

Good catch!
___
*[aimmo-game-worker/simulation/world_map.py, line 57 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvC4shBc0DNJw2anzg:-MVvcfaP1H5frYEp48rL:b4leyb9) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/world_map.py#L57)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Should this be moved to `Cell` instead of having a separate class? Maybe named `interactable_path` or something like that.
</blockquote></details>

Yeah this sounds good. Just one thing, on the worksheet it says that scan_nearby returns 'a list of the nearby artefacts'. Using Cell means technically it would be a list of nearby cells containing artefacts. Not sure how pedantic are we about that 😀
So if the student prints out `nearby[0]` for instance, they will see `Cell(...)` instead of `Artefact(...)`

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1481)* status: all files reviewed, 3 unresolved discussions (waiting on @dionizh and @razvan-pro)

___
*[aimmo-game-worker/simulation/action.py, line 35 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVv8Zj5AdYpibDB4AGZ:-MVvpcm91adaMTVY2b1t:bq351v1) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/action.py#L35)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

I was thinking that, but MoveTowardsAction accepts Artefact as parameter while MoveAction works with Direction, so it's probably clearer as a different class?
</blockquote></details>

Ah yes, I missed that they're different types, probably clearer this way you're right :+1:
___
*[aimmo-game-worker/simulation/pathfinding.py, line 4 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvAoyoE1eQVxCXzXvt:-MVvo5s73qCjKTqj70TI:b-jkgn6y) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/pathfinding.py#L4)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

It seems to just print out with `UserWarning:` prefix. 

Theoretically in our case there should always be a path to an artefact (so it should never get to the warning, hah), because the map and obstacles are programmed to never be blocking 😁
</blockquote></details>

Ah, ok :slightly_smiling_face: 
___
*[aimmo-game-worker/simulation/world_map.py, line 57 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvC4shBc0DNJw2anzg:-MVvq-a-D4lE-cOczsbt:b-pls8pv) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/world_map.py#L57)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Yeah this sounds good. Just one thing, on the worksheet it says that scan_nearby returns 'a list of the nearby artefacts'. Using Cell means technically it would be a list of nearby cells containing artefacts. Not sure how pedantic are we about that 😀
So if the student prints out `nearby[0]` for instance, they will see `Cell(...)` instead of `Artefact(...)`
</blockquote></details>

Oh, we can return the interactable inside the cell? That would be the real artefact I think anyway :slightly_smiling_face:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1481)* status: all files reviewed, 3 unresolved discussions (waiting on @dionizh and @razvan-pro)

___
*[aimmo-game-worker/simulation/world_map.py, line 33 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvrVrV7EMIT2pJ6UGQ:-MVvrVrV7EMIT2pJ6UGR:b-u86dww) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/world_map.py#L33)):*
> ```Python
> 
>     def has_artefact(self):
>         return self.interactable is not None and self.interactable["type"] == "artefact"
> ```

Hm, I just realised this probably needs to be updated with the other types of artefacts as part of the other issue - I don't think I updated this :sweat_smile:

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1481)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @razvan-pro)

___
*[aimmo-game-worker/simulation/pathfinding.py, line 4 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvAoyoE1eQVxCXzXvt:-MVvr2-76FQJFltkfHpo:b-35270q) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/pathfinding.py#L4)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Ah, ok :slightly_smiling_face: 
</blockquote></details>

I just tested warnings.warn on the aimmo console. It shows the offending file where the warn comes from, so it probably looks a bit too much for the students, not sure. We'll have to investigate later when we integrate the friendly stack trace. For now I'll change it to print so it's cleaner. 
___
*[aimmo-game-worker/simulation/world_map.py, line 33 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvrVrV7EMIT2pJ6UGQ:-MVvsLpu131N4NgmyloV:bu7qvro) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/world_map.py#L33)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Hm, I just realised this probably needs to be updated with the other types of artefacts as part of the other issue - I don't think I updated this :sweat_smile: 
</blockquote></details>

The issue is cell.interactable corresponds to the Interactable/Artefact backend object (but the backend does not need to know about the path as the pathfinding is all on the frontend), and there's no equivalence of this class on the frontend. Adding the path to the Cell frontend object/class might be the best way?
___
*[aimmo-game-worker/simulation/world_map.py, line 57 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvC4shBc0DNJw2anzg:-MVw3ePh5ggk21k2eR-T:b1ukaj7) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/world_map.py#L57)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Oh, we can return the interactable inside the cell? That would be the real artefact I think anyway :slightly_smiling_face: 
</blockquote></details>

Okay this seems to work fairly well 🙂 
(cell.interactable is serialised as dict so it comes up as dict on the frontend. When printed, the whole content of the dict is printed so we might want to wrap this in a class later depending how much we care about what the students see.)

**Review by razvan-pro — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1481)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[aimmo-game-worker/simulation/pathfinding.py, line 4 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvAoyoE1eQVxCXzXvt:-MVwAv1V89v6TBywkEJZ:bb6mt9b) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/pathfinding.py#L4)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

I just tested warnings.warn on the aimmo console. It shows the offending file where the warn comes from, so it probably looks a bit too much for the students, not sure. We'll have to investigate later when we integrate the friendly stack trace. For now I'll change it to print so it's cleaner. 
</blockquote></details>

:+1:
___
*[aimmo-game-worker/simulation/world_map.py, line 33 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVvrVrV7EMIT2pJ6UGQ:-MVwB8MjE8-4Hg8JU05e:b-dayf5w) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb61c0462dbc7ab66106d2fc428169eae069579f/aimmo-game-worker/simulation/world_map.py#L33)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

The issue is cell.interactable corresponds to the Interactable/Artefact backend object (but the backend does not need to know about the path as the pathfinding is all on the frontend), and there's no equivalence of this class on the frontend. Adding the path to the Cell frontend object/class might be the best way?
</blockquote></details>

Yep, that sounds good. This was a bit unrelated to this task, but I think pathfinding may fail after we merge the artefacts in as they won't have the `type: artefact` from the backend anymore :slightly_smiling_face: 
___
*[aimmo-game-worker/simulation/world_map.py, line 157 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1481#-MVwC8_cAkjws_gj8q6q:-MVwC8_cAkjws_gj8q6r:b-1yx2xj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/7e562dba0646469966538b8abfefa1f65da86f42/aimmo-game-worker/simulation/world_map.py#L157)):*
> ```Python
>         # get the best path to each artefact
>         nearby = defaultdict(list)
>         for artcell in artefacts:
> ```

Minor, could be just `cell` I guess and maybe `artefact_cells`

**Review by razvan-pro — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1481)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Review by razvan-pro — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1481)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Pull request merged**
