### PR TITLE
fix: improve game load time

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1547)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1547)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[aimmo-game-creator/game_manager.py, line 144 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1547#-MdavZsOCqIfyZKZFV9M:-MdavZsOCqIfyZKZFV9N:bu2fxqf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/3650da9c7f017462f450da4efe947c99a66f41cc/aimmo-game-creator/game_manager.py#L144)):*
> ```Python
>             # Delete extra games
>             running_games_ids = set(running_games.keys())
>             self._data.remove_unknown_games(running_games_ids)
> ```

Does this only remove / delete unknown running games now?
The old code seemed to also remove any unknown game + also remove any stopped game (I think so at least).

If that's intended, how come?

And if it is intended, do we still need `remove_stopped_games` or can we delete that function?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1547)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo-game-creator/game_manager.py, line 144 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1547#-MdavZsOCqIfyZKZFV9M:-Mdax9ku2l9u5EiMT15u:b1hlb22) ([raw file](https://github.com/ocadotechnology/aimmo/blob/3650da9c7f017462f450da4efe947c99a66f41cc/aimmo-game-creator/game_manager.py#L144)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Does this only remove / delete unknown running games now?
The old code seemed to also remove any unknown game + also remove any stopped game (I think so at least).

If that's intended, how come?

And if it is intended, do we still need `remove_stopped_games` or can we delete that function?
</blockquote></details>

Yep, it's only fetching a list of running games from Django and removing everything that's not there by getting the actual running games from kubernetes first (see `delete_unknown_games`).

This is why the previous code was slow, there were 2 issues: getting all games from Django and deleting most of the games (that were already stopped/deleted).

Yep, I think `remove_stopped_games` can be removed now, I'll do that :slightly_smiling_face: :thumbsup:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1547)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo-game-creator/game_manager.py, line 144 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1547#-MdavZsOCqIfyZKZFV9M:-MdayqWt5PtFlKjzu1r6:b14vgx3) ([raw file](https://github.com/ocadotechnology/aimmo/blob/3650da9c7f017462f450da4efe947c99a66f41cc/aimmo-game-creator/game_manager.py#L144)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Yep, it's only fetching a list of running games from Django and removing everything that's not there by getting the actual running games from kubernetes first (see `delete_unknown_games`).

This is why the previous code was slow, there were 2 issues: getting all games from Django and deleting most of the games (that were already stopped/deleted).

Yep, I think `remove_stopped_games` can be removed now, I'll do that :slightly_smiling_face: :thumbsup: 
</blockquote></details>

Done. This `game_manager.py` is in a semi-dirty state now since we plan to remove it soon anyway :grin:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1547#-:-Mdb-lH74DBV3SiBtt47:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1547)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
