### PR TITLE
fix: Fix admin pages for old games without classes too

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1555)

### CODE REVIEW

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1555)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo/admin.py, line 22 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1555#-Me5_yJC6syvql-Ffrgc:-Me5_yJC6syvql-Ffrgd:blch3cc) ([raw file](https://github.com/ocadotechnology/aimmo/blob/7deb79d3cf340720045020a6bdcbf08e422c3bf9/aimmo/admin.py#L22)):*
> ```Python
> 
>     def school(self, obj):
>         if obj.game_class:
> ```

Should this be `if obj and obj.game_class` to be safer?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1555)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[aimmo/admin.py, line 22 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1555#-Me5_yJC6syvql-Ffrgc:-Me64K1B3fgrMrryID-s:bclmulo) ([raw file](https://github.com/ocadotechnology/aimmo/blob/7deb79d3cf340720045020a6bdcbf08e422c3bf9/aimmo/admin.py#L22)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Should this be `if obj and obj.game_class` to be safer?
</blockquote></details>

I think checking `if obj` isn't needed as `obj` refers to the object that is listed in the admin page so `obj` shouldn't ever be None.
I can still add the check though if you want?

**Review by dionizh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1555)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo/admin.py, line 22 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1555#-Me5_yJC6syvql-Ffrgc:-Me658HHCGH2g9kMpx1f:bdatvew) ([raw file](https://github.com/ocadotechnology/aimmo/blob/7deb79d3cf340720045020a6bdcbf08e422c3bf9/aimmo/admin.py#L22)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I think checking `if obj` isn't needed as `obj` refers to the object that is listed in the admin page so `obj` shouldn't ever be None.
I can still add the check though if you want?
</blockquote></details>

Yea looking in context the others are not doing it too. All good 🙃

**Review by dionizh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1555)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
