### PR TITLE
feat: Add game dropdown

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1450)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 7 of 7 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1450#-:-MRfIzup7DBSFaR_NpRF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[aimmo/views.py, line 21 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1450#-MRfEV1P18HcT1ZBM-l9:-MRfEV1QBX56PQeL6DHp:bwe58pt) ([raw file](https://github.com/ocadotechnology/aimmo/blob/025e5310207093223d372a48517dd49747440055/aimmo/views.py#L21)):*
> ```Python
> from rest_framework.views import APIView
> 
> from portal.game_creator import create_avatar_for_user
> ```

Just as a note here, I know we said we wanted to move it to portal but I just had a thought about whether or not we might want to move it to common later :sweat_smile: Not sure if this could create any circular dependencies. But since portal is only a dev dependency here, it should be fine (I hope).
___
*[aimmo/migrations/0024_auto_20210119_1723.py, line 10 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1450#-MRfEqWT75F3DxQr_aoh:-MRfEqWUBUp_qpuqyKZI:ba6e04f) ([raw file](https://github.com/ocadotechnology/aimmo/blob/025e5310207093223d372a48517dd49747440055/aimmo/migrations/0024_auto_20210119_1723.py#L10)):*
> ```Python
> 
>     dependencies = [
>         ("aimmo", "0023_remove_level_attempt"),
> ```

Can you please rename this migration so we know what it does, like the previous one? :pray:

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1450)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[aimmo/migrations/0024_auto_20210119_1723.py, line 10 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1450#-MRfEqWT75F3DxQr_aoh:-MRfJBhK-4L3A9mDEKVg:blh9ugl) ([raw file](https://github.com/ocadotechnology/aimmo/blob/025e5310207093223d372a48517dd49747440055/aimmo/migrations/0024_auto_20210119_1723.py#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Can you please rename this migration so we know what it does, like the previous one? :pray: 
</blockquote></details>

Update so I can block :sweat_smile:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1450)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo/views.py, line 21 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1450#-MRfEV1P18HcT1ZBM-l9:-MRtFcNuEgk-S8AmF1LY:bn09k0t) ([raw file](https://github.com/ocadotechnology/aimmo/blob/025e5310207093223d372a48517dd49747440055/aimmo/views.py#L21)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Just as a note here, I know we said we wanted to move it to portal but I just had a thought about whether or not we might want to move it to common later :sweat_smile: Not sure if this could create any circular dependencies. But since portal is only a dev dependency here, it should be fine (I hope).
</blockquote></details>

Ah yes, I was aiming to not import from `portal` initially and then I got to this method and I still did it in the end... I think you're right, we should probably move this to common.
___
*[aimmo/migrations/0024_auto_20210119_1723.py, line 10 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1450#-MRfEqWT75F3DxQr_aoh:-MRtGnFF7UqtNOainqRS:b-8fx2u7) ([raw file](https://github.com/ocadotechnology/aimmo/blob/025e5310207093223d372a48517dd49747440055/aimmo/migrations/0024_auto_20210119_1723.py#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Update so I can block :sweat_smile: 
</blockquote></details>

:+1:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1450#-:-MRtUpUMAvK6a6y95hmk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
