### PR TITLE
Remove Vagrant option from runner

### PR DESCRIPTION
**Pull request by riaJha97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/644)

### CODE REVIEW

**Comment by mrniket** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @riaJha97)

---

*[ubuntu_setup.sh, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/644#-LG07xDN7D-6vt_C9Uyi:-LG07xDN7D-6vt_C9Uyj:b-85qvd5) ([raw file](https://github.com/ocadotechnology/aimmo/blob/87972053e41da505919489caf7b76e866176b57c/ubuntu_setup.sh#L1)):*
> ```Shell
> apt-get update
> ```

could be add something in our docs to refer people to this script?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/644)*

**Comment by riaJha97** [comment]
Review status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mrniket and @riaJha97)

---

*[ubuntu_setup.sh, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/644#-LG07xDN7D-6vt_C9Uyi:-LG09gPj2q54aT9meE3I:b-5jozut) ([raw file](https://github.com/ocadotechnology/aimmo/blob/87972053e41da505919489caf7b76e866176b57c/ubuntu_setup.sh#L1)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

could be add something in our docs to refer people to this script?
</blockquote></details>

Not too sure where it should go. Shall I just link to this script in the README or should it be another section in usage.md?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/644)*

**Comment by mrniket** [comment]
Review status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mrniket)

---

*[ubuntu_setup.sh, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/644#-LG07xDN7D-6vt_C9Uyi:-LG0KgnA4zMQB5mUDDvZ:b-vpo0od) ([raw file](https://github.com/ocadotechnology/aimmo/blob/87972053e41da505919489caf7b76e866176b57c/ubuntu_setup.sh#L1)):*
<details><summary><i>Previously, riaJha97 wrote…</i></summary><blockquote>

Not too sure where it should go. Shall I just link to this script in the README or should it be another section in usage.md?
</blockquote></details>

I would link to the script in the readme, possibly improving the 'Setting up AI:MMO on Linux part'

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/644)*

**Comment by riaJha97** [comment]
Review status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @mrniket and @riaJha97)

---

*[ubuntu_setup.sh, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/644#-LG07xDN7D-6vt_C9Uyi:-LG0_FxA9C5-QOzxGedo:b-8jlrqf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/87972053e41da505919489caf7b76e866176b57c/ubuntu_setup.sh#L1)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

I would link to the script in the readme, possibly improving the 'Setting up AI:MMO on Linux part'
</blockquote></details>

Added ref to this script in usage.md

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/644)*

**Comment by CelineBoudier** [comment]
Reviewed 4 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/644)*

**Comment by CelineBoudier** [comment]
:lgtm:

---

Review status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/644#-:-LG5YrWf8EasBSqT7tau:bnfp4nl)*

**Comment by CelineBoudier** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @mrniket and @riaJha97)

---

*[docs/usage.md, line 12 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/644#-LG5ZMtP3lcRpQa5J3un:-LG5ZMtQBasFBkGEGrP6:bgob9ho) ([raw file](https://github.com/ocadotechnology/aimmo/blob/6f0ff4c45370aec4b7c89bc7115c2ca0531b984d/docs/usage.md#L12)):*
> ```Markdown
> * Follow the instructions at [game frontend documentation](https://github.com/ocadotechnology/aimmo/blob/master/game_frontend/README.md) in order to install all the frontend requirements.
> * Make and activate a virtualenv (We recommend [pipenv](https://docs.pipenv.org/)) - if you have a **[Mac see the section at the bottom](https://github.com/ocadotechnology/aimmo/blob/master/docs/usage.md#on-mac)**.
>     * To set this up, run `./ubuntu_setup.sh`. This will install nodejs, yarn, as well as pipenv. 
> ```

should we say it's for linux?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/644)*

**Comment by CelineBoudier** [comment]
Dismissed @mrniket from a discussion.
Review status: all files reviewed, 1 unresolved discussion

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/644)*

**Pull request merged**
