### PR TITLE
feat: Use Agones to manage gameservers

### PR DESCRIPTION
**Pull request by mrniket**
BREAKING CHANGE: Removed local mode. You must use minikube to run the project locally.

# To do
- [x] Update Tests
- [ ] Update docs

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439)

### CODE REVIEW

**Review by razvan-pro — COMMENTED** [review]
Nice - quite a lot of code removed, especially from `game_manager.py` which is great! :+1: We have to make sure tests run again and I posted some minor comments, but otherwise it looks great! :slightly_smiling_face: 

> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-:-MPDiHuZ3uB0p4-Vcv_Z:b-50yl4c)* status: all files reviewed, 5 unresolved discussions (waiting on @mrniket)

___
*[aimmo-game/activity_monitor.py, line 80 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MP96MAUEwLN-Ddgf0qv:-MP96MAUEwLN-Ddgf0qw:b-pwrj0v) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game/activity_monitor.py#L80)):*
> ```Python
>             LOGGER.error(f"Game status could not be changed: {response}")
> 
>         # self.agones_stub.Shutdown()
> ```

Does this need to be uncommented or removed? If removed - is `self.agones_stub` still being used anywhere?
___
*[aimmo-game/service.py, line 226 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MPDe5QLBLvNzKlhcV3L:-MPDe5QLBLvNzKlhcV3M:b9ot3gr) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game/service.py#L226)):*
> ```Python
>             os.environ["GAME_API_URL"] = annotations["game-api-url"]
>             django_api_url = annotations["game-api-url"]
>             port = 5000
> ```

Do we want this as a constant/config?
___
*[aimmo-game/service.py, line 252 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MPDe_LADvaGPRR5hwvh:-MPDe_LADvaGPRR5hwvi:b1qzfsw) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game/service.py#L252)):*
> ```Python
> 
> async def run_server():
>     port = 5000
> ```

Same question as above - and do they need to match?
___
*[aimmo-game-creator/rc-aimmo-game-creator.yaml, line 24 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MPDgJGLDg-B1Tlsm1M1:-MPDgJGM2DoxR_U6ES7x:b-f7b4uu) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game-creator/rc-aimmo-game-creator.yaml#L24)):*
> ```YAML
>       containers:
>         - name: aimmo-game-creator
>           image: ocadotechnology/aimmo-game-creator:test
> ```

Will this need to be reverted to `latest` after we deploy or at some point?
___
*[aimmo-game-creator/rc-aimmo-game-creator.yaml, line 30 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MPDgVR26GPib3KEraBm:-MPDgVR26GPib3KEraBn:buj3q2q) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game-creator/rc-aimmo-game-creator.yaml#L30)):*
> ```YAML
>           env:
>             - name: IMAGE_SUFFIX
>               value: test
> ```

Same question for this if it's a different answer :slightly_smiling_face:

**Review by razvan-pro — COMMENTED** [review]
* I just noticed the Update Tests TODO after I wrote my previous comment :grin: 

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-:-MPDjafn-uouHEUbT5v4:b-br44v9)* status: all files reviewed, 5 unresolved discussions (waiting on @mrniket)

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439)* status: 20 of 50 files reviewed, 5 unresolved discussions (waiting on @mrniket and @razvan-pro)

___
*[aimmo-game/activity_monitor.py, line 80 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MP96MAUEwLN-Ddgf0qv:-MPjGG7s3sFwTAHsYA1o:bs9yew) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game/activity_monitor.py#L80)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Does this need to be uncommented or removed? If removed - is `self.agones_stub` still being used anywhere?
</blockquote></details>

removed 😊 I was thinking that the game could shut itself down instead of needing a game creator to do it, but decided it was out of scope for this PR
___
*[aimmo-game/service.py, line 226 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MPDe5QLBLvNzKlhcV3L:-MPjHzmV-rExsd791zLZ:b2fin4s) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game/service.py#L226)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Do we want this as a constant/config?
</blockquote></details>

I've put it as a default value for GameAllocationInfo
___
*[aimmo-game/service.py, line 252 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MPDe_LADvaGPRR5hwvh:-MPjI76kB1NAt5WNqOvV:b-gru8c0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game/service.py#L252)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Same question as above - and do they need to match?
</blockquote></details>

I believe they do, refactored
___
*[aimmo-game-creator/rc-aimmo-game-creator.yaml, line 24 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MPDgJGLDg-B1Tlsm1M1:-MPjJ3sM8r0qT1BKtSmL:b-nu3dw9) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game-creator/rc-aimmo-game-creator.yaml#L24)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Will this need to be reverted to `latest` after we deploy or at some point?
</blockquote></details>

this file is only used locally, for deployment, there is a yaml file in codeforlife-deploy-appengine
___
*[aimmo-game-creator/rc-aimmo-game-creator.yaml, line 30 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MPDgVR26GPib3KEraBm:-MPjJY5V5Dw2woZup4NH:b-xu3xlm) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f60cc873352f38ee569205a73a90b890fab169e0/aimmo-game-creator/rc-aimmo-game-creator.yaml#L30)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Same question for this if it's a different answer :slightly_smiling_face: 
</blockquote></details>

Same answer 😊

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 30 of 33 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[aimmo_setup.py, line 97 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSYARpPDEgCewdy3Irb:-MSYARpPDEgCewdy3Irc:b-yf5zk1) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo_setup.py#L97)):*
> ```Python
> #         pass
> #     else:
> #         raise Exception
> ```

We probably need to remove this.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439)* status: all files reviewed, 7 unresolved discussions (waiting on @mrniket and @razvan-pro)

___
*[aimmo_setup.py, line 97 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSYARpPDEgCewdy3Irb:-MSh_BeH8HpmEaV1jfLH:b-fi8b8c) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo_setup.py#L97)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

We probably need to remove this.
</blockquote></details>

Yeah, I assume so, if it's not needed anymore.
___
*[aimmo/game_renderer.py, line 10 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSh_hLWEEjECXS1yHxt:-MSh_hLWEEjECXS1yHxu:b-r170wp) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo/game_renderer.py#L10)):*
> ```Python
> from aimmo import app_settings, exceptions
> from .models import Game
> from django.http import Http404
> ```

Organise imports? :sweat_smile: 
___
*[aimmo-game/service.py, line 6 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MShashh-GpMbDQGEcGQ:-MShashh-GpMbDQGEcGR:bcd521z) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo-game/service.py#L6)):*
> ```Python
> import logging
> import os
> from asyncio.events import AbstractEventLoop
> ```

Organise imports here too
___
*[aimmo-game/tests/test_simulation/test_action.py, line 157 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MShd3Te1iL2BQwrJaRC:-MShd3Te1iL2BQwrJaRD:bwffvwj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo-game/tests/test_simulation/test_action.py#L157)):*
> ```Python
>         artefact = game_state.world_map.get_cell(self.avatar.location).interactable
> 
>         self.assertEqual(artefact.in_backpack, False)
> ```

We should update those asserts to follow the pytest style asserts too
___
*[aimmo_runner/docker_scripts.py, line 48 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSheMHU7VbrYGT7jD3s:-MSheMHV5ke-p4ztkZih:b-ilz5bi) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2d19db75678ec2f599ec30716ece45eddc59d452/aimmo_runner/docker_scripts.py#L48)):*
> ```Python
>         client = create_docker_client(use_raw_env=False, minikube=minikube)
> 
>     directories = ("aimmo-game", "aimmo-game-creator", "aimmo-game-worker")
> ```

Is this OK?
___
*[aimmo_runner/minikube.py, line 9 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSheOwsAalHwpb_LM3V:-MSheOwsAalHwpb_LM3W:b-84a0q5) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo_runner/minikube.py#L9)):*
> ```Python
> from kubernetes.client import AppsV1Api
> from kubernetes.config import load_kube_config
> import yaml
> ```

Sort imports here too
___
*[aimmo-game-creator/aimmo-game-creator-deployment.yaml, line 30 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MShdL4a7MOB22_fFLvz:-MShdL4a7MOB22_fFLw-:b-sidp42) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo-game-creator/aimmo-game-creator-deployment.yaml#L30)):*
> ```YAML
>           env:
>             - name: IMAGE_SUFFIX
>               value: test
> ```

is test here ok instead of latest?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439)* status: all files reviewed, 7 unresolved discussions (waiting on @faucomte97, @mrniket, and @razvan-pro)

___
*[aimmo_runner/docker_scripts.py, line 48 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSheMHU7VbrYGT7jD3s:-MSi20O-2EBQ8v7fqyYY:bhhpz15) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2d19db75678ec2f599ec30716ece45eddc59d452/aimmo_runner/docker_scripts.py#L48)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Is this OK?
</blockquote></details>

I don't see anything wrong with this :thinking: 

I'm looking at `dir` below though, we should probably replace that (it's a global function)
___
*[aimmo-game-creator/aimmo-game-creator-deployment.yaml, line 30 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MShdL4a7MOB22_fFLvz:-MSi1ittC8QvpDq-VGQ2:b-9cailb) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo-game-creator/aimmo-game-creator-deployment.yaml#L30)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

is test here ok instead of latest?
</blockquote></details>

Yep, had a similar question previously :slightly_smiling_face:  - "this file is only used locally, for deployment, there is a yaml file in codeforlife-deploy-appengine"

**Review by razvan-pro — COMMENTED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439)* status: all files reviewed, 6 unresolved discussions (waiting on @faucomte97)

___
*[aimmo/game_renderer.py, line 10 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSh_hLWEEjECXS1yHxt:-MSiB255EirTGb8cbdUd:bb6mt9b) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo/game_renderer.py#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Organise imports? :sweat_smile: 
</blockquote></details>

:+1:
___
*[aimmo-game/service.py, line 6 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MShashh-GpMbDQGEcGQ:-MSiBjX7BF0UnfegDM1N:b-s9jko1) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo-game/service.py#L6)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Organise imports here too
</blockquote></details>

Done if it's just this line - my editor doesn't detect any others, but it's not great at organising imports :slightly_smiling_face:
___
*[aimmo-game/tests/test_simulation/test_action.py, line 157 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MShd3Te1iL2BQwrJaRC:-MSiF1ep4VWjD7EN60PV:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo-game/tests/test_simulation/test_action.py#L157)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

We should update those asserts to follow the pytest style asserts too
</blockquote></details>

Done.
___
*[aimmo_runner/minikube.py, line 9 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSheOwsAalHwpb_LM3V:-MSiHd_F2F8zTIFj-iin:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo_runner/minikube.py#L9)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Sort imports here too
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439)* status: all files reviewed, 2 unresolved discussions (waiting on @mrniket and @razvan-pro)

___
*[aimmo-game/service.py, line 6 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MShashh-GpMbDQGEcGQ:-MSnIoXDE8bjQ3kmlUeL:bj479d8) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo-game/service.py#L6)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Done if it's just this line - my editor doesn't detect any others, but it's not great at organising imports :slightly_smiling_face:
</blockquote></details>

I think it should also put the other ones that are just import at the top.
That's one of the things I prefer about IntelliJ :stuck_out_tongue_winking_eye: 
___
*[aimmo_runner/docker_scripts.py, line 48 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSheMHU7VbrYGT7jD3s:-MSnJH6iBNHbFx5oWem8:b-hlg8ti) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2d19db75678ec2f599ec30716ece45eddc59d452/aimmo_runner/docker_scripts.py#L48)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

I don't see anything wrong with this :thinking: 

I'm looking at `dir` below though, we should probably replace that (it's a global function)
</blockquote></details>

I mean, is it OK that we're removing aimmo-game-worker from the list of directories? And if so why are we doing that?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439)* status: 53 of 54 files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @razvan-pro)

___
*[aimmo-game/service.py, line 6 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MShashh-GpMbDQGEcGQ:-MTBifOY5TBriwFVP7Ci:bamtuy8) ([raw file](https://github.com/ocadotechnology/aimmo/blob/154e09ccbb7f71e329ffdbc3b6262a59dfe44489/aimmo-game/service.py#L6)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I think it should also put the other ones that are just import at the top.
That's one of the things I prefer about IntelliJ :stuck_out_tongue_winking_eye: 
</blockquote></details>

I usually split them into groups as they are now: Python, external and our libraries. Feel free to use IntelliJ optimizer and push the changes though :slightly_smiling_face: 
___
*[aimmo_runner/docker_scripts.py, line 48 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-MSheMHU7VbrYGT7jD3s:-MTBj9QT7aUPWU1rdZzW:b-ina2ry) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2d19db75678ec2f599ec30716ece45eddc59d452/aimmo_runner/docker_scripts.py#L48)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I mean, is it OK that we're removing aimmo-game-worker from the list of directories? And if so why are we doing that?
</blockquote></details>

Ooh, yes, I think so, because it doesn't need to be a docker image anymore :slightly_smiling_face: aimmo-game-worker is a package used in the frontend now.

**Review by razvan-pro — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1439#-:-MTewdxi6ugnrrq7g8dZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
