### PR TITLE
feat: Implement CSP header

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1586)

### CODE REVIEW

**Review by razvan-pro — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1586)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo/autoconfig.py, line 48 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1586#-Mp7jlKACr4mi5i8i9iR:-Mp7jlKACr4mi5i8i9iS:b58naps) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e07c6a9988b5e411cb5b1df97b6d8535dfc539b4/aimmo/autoconfig.py#L48)):*
> ```Python
>         "ws://localhost:41949/",
>         "ws://192.168.58.2:7959/socket.io/",
>         "http://192.168.58.2:7959/socket.io/",
> ```

Minor, hmm, I have a feeling this may not be the same on all machines - we'll probably disable CSP on localhost though.

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1586)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[aimmo/autoconfig.py, line 30 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1586#-MpCe3gg35VbCHcu5sDb:-MpCe3gg35VbCHcu5sDc:b-nofuap) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e07c6a9988b5e411cb5b1df97b6d8535dfc539b4/aimmo/autoconfig.py#L30)):*
> ```Python
>     ],
>     "USE_TZ": True,
>     # ----------------------------------------------------------------------------------
> ```

Same comment about separation :grin:

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1586)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @razvan-pro)

___
*[aimmo/autoconfig.py, line 30 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1586#-MpCe3gg35VbCHcu5sDb:-MpDFWHb-UEUgIVx_KLy:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e07c6a9988b5e411cb5b1df97b6d8535dfc539b4/aimmo/autoconfig.py#L30)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Same comment about separation :grin: 
</blockquote></details>

Done.

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1586)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @razvan-pro)

___
*[aimmo/autoconfig.py, line 48 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1586#-Mp7jlKACr4mi5i8i9iR:-MpDFvhrDiws1aL2__AQ:b-xqtuj9) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e07c6a9988b5e411cb5b1df97b6d8535dfc539b4/aimmo/autoconfig.py#L48)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Minor, hmm, I have a feeling this may not be the same on all machines - we'll probably disable CSP on localhost though.
</blockquote></details>

Should I leave it for now?
Should we test it on other machines?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1586)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @faucomte97 and @razvan-pro)

___
*[aimmo/autoconfig.py, line 48 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1586#-Mp7jlKACr4mi5i8i9iR:-MpGMju81SET0qxBGDVB:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e07c6a9988b5e411cb5b1df97b6d8535dfc539b4/aimmo/autoconfig.py#L48)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Should I leave it for now?
Should we test it on other machines?
</blockquote></details>

Done.

**Review by razvan-pro — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1586#-:-MpGNFuu5uJJrp5zDM4L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
