### PR TITLE
fix: fixed setup script, including cmdtest and init docker repo

### PR DESCRIPTION
**Pull request by KamilPawel**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1584)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1584#-:-MnR-3u40sl6gpAHj8lu:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @KamilPawel)

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1584)* status: all files reviewed, 3 unresolved discussions (waiting on @KamilPawel)

___
*[aimmo_setup.py, line 508 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1584#-MnANE4F-ySaNquveE15:-MnVTkVOAPB_wlS_e1xA:bra98iv) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2ccd88f4fd55da04d2b670bdd39b03e9553266f8/aimmo_setup.py#L508)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Please give a more specific message such as: "`cmdtest` clashes with `yarn` and we recommend to remove it. Is it okay to remove cmdtest?" Remove I.
</blockquote></details>

Update text please:
"Looks like cmdtest is installed on your machine. cmdtest clashes with yarn so we recommend to remove it. Is it okay to remove cmdtest? [y/n]"
___
*[aimmo_setup.py, line 145 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1584#-MnVT3ICDQOhOjrqijfj:-MnVT3IDEgWBv-X9DN2Q:bswyblt) ([raw file](https://github.com/ocadotechnology/aimmo/blob/0725065c0d0ea9e728bf977578d93eb79dd50d34/aimmo_setup.py#L145)):*
> ```Python
>         arch_type (ArchType): host architecture type
>     """
>     tasks = [
> ```

Where is the nodejs installation for Mac? 
___
*[aimmo_setup.py, line 285 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1584#-MnVTGVM4USCZB0K48o6:-MnVTGVM4USCZB0K48o7:b6t0y8h) ([raw file](https://github.com/ocadotechnology/aimmo/blob/0725065c0d0ea9e728bf977578d93eb79dd50d34/aimmo_setup.py#L285)):*
> ```Python
> 
>     if os_type == OSType.MAC:
>         _cmd("brew install yarn")
> ```

Can you follow this here https://classic.yarnpkg.com/en/docs/install - as this is the more preferred way to install yarn now. 
Make sure that npm is installed before this step (related to my comment above about nodejs).

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1584)* status: all files reviewed, 2 unresolved discussions (waiting on @KamilPawel)

___
*[aimmo_setup.py, line 503 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/1584#-Mnkx0ufB-vSLq2u1Pks:-Mnkx0ufB-vSLq2u1Pkt:b-kcuovx) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e046b00ea36afba62c42c64bb4a41223011c944a/aimmo_setup.py#L503)):*
> ```Python
>         except CalledProcessError:
>             print("cmdtest not found")
>             return
> ```

Did you check if cmdtest is not found it throws CalledProcessError? I'd think it returns something else, and only throws an error if `dkpg-query` is not found? Can you also remove the print - I don't think it's necessary to notify the user if they don't have cmdtest.

**Review by dionizh — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

___
*[aimmo_setup.py, line 503 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/1584#-Mnkx0ufB-vSLq2u1Pks:-Mnl0DFJAMDd_4l70d2L:b-sbz9jb) ([raw file](https://github.com/ocadotechnology/aimmo/blob/e046b00ea36afba62c42c64bb4a41223011c944a/aimmo_setup.py#L503)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Did you check if cmdtest is not found it throws CalledProcessError? I'd think it returns something else, and only throws an error if `dkpg-query` is not found? Can you also remove the print - I don't think it's necessary to notify the user if they don't have cmdtest.
</blockquote></details>

Perfect :)

**Review by dionizh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1584#-:-Mnl0MdjEWb0nYRBNfqx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
