### PR TITLE
fix: Update Cypress tests with portal flow

### PR DESCRIPTION
**Pull request by mrniket**
Signed-off-by: Niket <niket.shah1@ocado.com>

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395)

### CODE REVIEW

**Review by mrniket — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[aimmo/tests/test_views.py, line 74 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MHu0NMC683tjFmu4PyM:-MHu0NMC683tjFmu4PyN:b8y8qgb) ([raw file](https://github.com/ocadotechnology/aimmo/blob/89d8cf8f4e82fb081c476340543dd08528ef611b/aimmo/tests/test_views.py#L74)):*
> ```Python
>         cls.game = models.Game(
>             id=1,
>             owner=cls.user,
> ```

why is owner id needed?
___
*[game_frontend/cypress/support/commands.ts, line 75 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MHu0fjV9eGv3Oa-Kfio:-MHu0fjV9eGv3Oa-Kfip:b-7e2rpg) ([raw file](https://github.com/ocadotechnology/aimmo/blob/89d8cf8f4e82fb081c476340543dd08528ef611b/game_frontend/cypress/support/commands.ts#L75)):*
> ```XML
>     const games = response.body
>     let firstUserGameId
>     console.log(games)
> ```

remove log message here
___
*[game_frontend/cypress/support/commands.ts, line 76 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MHu0usO46ZmDhxLpPvB:-MHu0usO46ZmDhxLpPvC:b2mxgob) ([raw file](https://github.com/ocadotechnology/aimmo/blob/89d8cf8f4e82fb081c476340543dd08528ef611b/game_frontend/cypress/support/commands.ts#L76)):*
> ```XML
>     let firstUserGameId
>     console.log(games)
>     for (const gameId of Object.keys(games))
> ```

using `Object.entries` might be more readable here: 

`for (const [key, value] of Object.entries(object1))`

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @mrniket)

___
*[aimmo/tests/test_views.py, line 74 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MHu0NMC683tjFmu4PyM:-MHu4eY6BNFFzr02R0Yi:b-e8rys1) ([raw file](https://github.com/ocadotechnology/aimmo/blob/89d8cf8f4e82fb081c476340543dd08528ef611b/aimmo/tests/test_views.py#L74)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

why is owner id needed?
</blockquote></details>

Because I added it to the serialiser so the tests started failing.
I added it to the serialiser so I could use it in the Cypress commands to delete / go to games that are the user's, not any other user's because that caused a 403.
___
*[game_frontend/cypress/support/commands.ts, line 75 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MHu0fjV9eGv3Oa-Kfio:-MHu5-tqD6PejLkHxh1S:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/89d8cf8f4e82fb081c476340543dd08528ef611b/game_frontend/cypress/support/commands.ts#L75)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

remove log message here
</blockquote></details>

Done.
___
*[game_frontend/cypress/support/commands.ts, line 76 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MHu0usO46ZmDhxLpPvB:-MHu6NRI-HWkQu5TmagV:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/89d8cf8f4e82fb081c476340543dd08528ef611b/game_frontend/cypress/support/commands.ts#L76)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

using `Object.entries` might be more readable here: 

`for (const [key, value] of Object.entries(object1))`
</blockquote></details>

Done.

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[aimmo/tests/test_views.py, line 74 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MHu0NMC683tjFmu4PyM:-MHuBGVr6rKIAnWOvZi8:b-yrtxx1) ([raw file](https://github.com/ocadotechnology/aimmo/blob/89d8cf8f4e82fb081c476340543dd08528ef611b/aimmo/tests/test_views.py#L74)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Because I added it to the serialiser so the tests started failing.
I added it to the serialiser so I could use it in the Cypress commands to delete / go to games that are the user's, not any other user's because that caused a 403.
</blockquote></details>

hmm we shouldn't be adding stuff to our apis just for tests :/ is there another way to do this? maybe use UI or fetch the gameID of the game we create in the other "new game" command?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[aimmo/tests/test_views.py, line 74 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MHu0NMC683tjFmu4PyM:-MHuLZsg6_piqEp513lx:b-2kgp6l) ([raw file](https://github.com/ocadotechnology/aimmo/blob/89d8cf8f4e82fb081c476340543dd08528ef611b/aimmo/tests/test_views.py#L74)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

hmm we shouldn't be adding stuff to our apis just for tests :/ is there another way to do this? maybe use UI or fetch the gameID of the game we create in the other "new game" command?
</blockquote></details>

We should be able to do that, what do we do for the delete games command though? Do it through the UI? :/

**Review by mrniket — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

**Review by mrniket — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395)* status: 8 of 13 files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[game_frontend/cypress/integration/avatarWorker/codeExecution.spec.js, line 82 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MI-Kii39SqquZ8No2kS:-MI-Kii39SqquZ8No2kT:b3kre) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f2bf0535fa94e095da9297365a8d2f32921d040d/game_frontend/cypress/integration/avatarWorker/codeExecution.spec.js#L82)):*
> ```JavaScript
>         direction: {
>           x: 0,
>           y: gameId
> ```

?
___
*[game_frontend/cypress/integration/avatarWorker/webWorker.spec.ts, line 10 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MI-Kr9-3Z0720onEfjW:-MI-Kr9-3Z0720onEfjX:bluihv0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f2bf0535fa94e095da9297365a8d2f32921d040d/game_frontend/cypress/integration/avatarWorker/webWorker.spec.ts#L10)):*
> ```XML
>   beforeEach(() => {
>     cy.login()
>     gameId = cy.addTestGame()
> ```

I think this is not a number which is why the tests are failing

**Review by faucomte97 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-:-MHuLg7uCKjTJWOd-h75:bnfp4nl)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[game_frontend/cypress/integration/avatarWorker/codeExecution.spec.js, line 82 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MI-Kii39SqquZ8No2kS:-MI-T_gs2UX4DB6JqPyL:bbzlsg3) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f2bf0535fa94e095da9297365a8d2f32921d040d/game_frontend/cypress/integration/avatarWorker/codeExecution.spec.js#L82)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

?
</blockquote></details>

Nothing to see here :angel: 
___
*[game_frontend/cypress/integration/avatarWorker/webWorker.spec.ts, line 10 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MI-Kr9-3Z0720onEfjW:-MI-TdKmCtD0YWWWeQYn:b-aexiia) ([raw file](https://github.com/ocadotechnology/aimmo/blob/f2bf0535fa94e095da9297365a8d2f32921d040d/game_frontend/cypress/integration/avatarWorker/webWorker.spec.ts#L10)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

I think this is not a number which is why the tests are failing
</blockquote></details>

What number? :angel:

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[aimmo/tests/test_views.py, line 74 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1395#-MHu0NMC683tjFmu4PyM:-MI-V8RZDtWYtz26ilqQ:busawlc) ([raw file](https://github.com/ocadotechnology/aimmo/blob/89d8cf8f4e82fb081c476340543dd08528ef611b/aimmo/tests/test_views.py#L74)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

We should be able to do that, what do we do for the delete games command though? Do it through the UI? :/
</blockquote></details>

Fixed :)

**Review by mrniket — COMMENTED** [review]
> Reviewed 5 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1395)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
