### PR TITLE
feat: archive game on delete and django changes

### PR DESCRIPTION
**Pull request by dionizh**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1605#-Mtbu6m-0m70_5ITXRya:-Mtbu6m-0m70_5ITXRyb:bsavai4) (no related file):*
What if a teacher creates a game with a class, "deletes" it and then recreates it for the same class? Is it gonna unarchive it or create a new game in the DB?

---

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/1605#-Mtbu6m-0m70_5ITXRya:-Mtbue-vB_YxPU44-TsF:bcd2gby) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

What if a teacher creates a game with a class, "deletes" it and then recreates it for the same class? Is it gonna unarchive it or create a new game in the DB?
</blockquote></details>

Yes, creation is always new game. They don't know that the games are not really deleted, that's just internal. So you can never revive a game. Right now we don't have a way to name the game too, and reviving only makes sense if user can identify the games I think.

---

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605)* status: all files reviewed, 2 unresolved discussions (waiting on @dionizh and @faucomte97)

___
*[aimmo/templatetags/players_utils.py, line 17 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1605#-MtbvFDhEs58YInn4mR3:-MtbvFDi4_KrQ_2v-IWa:b-srkm51) ([raw file](https://github.com/ocadotechnology/aimmo/blob/1882b3e410877babf088abd4c6e0fabc4da2a34f/aimmo/templatetags/players_utils.py#L17)):*
> ```Python
>     user = context.request.user
>     if logged_in_as_student(user):
>         playable_games = user.userprofile.student.class_field.game
> ```

I think we'll need something for the student somewhere as well, like showing the unarchived game - it feels like this will still show the attached game even if it's been deleted, won't it? :thinking:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605#-:-MtcBJR2368Amg0FWZI0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[aimmo/templatetags/players_utils.py, line 17 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1605#-MtbvFDhEs58YInn4mR3:-Mtcs3SxDu7x-8kVCrrA:bya8ou4) ([raw file](https://github.com/ocadotechnology/aimmo/blob/1882b3e410877babf088abd4c6e0fabc4da2a34f/aimmo/templatetags/players_utils.py#L17)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

So this function is actually only called by teacher and never by student - to construct the games table. My cleanup is here: https://github.com/ocadotechnology/aimmo/pull/1606
</blockquote></details>

:heavy_check_mark: Approved the cleanup

We'll need some changes in portal I think, for the student dashboard, so it only fetches the non-archived game :slightly_smiling_face:

**Review by razvan-pro — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605)* status: 6 of 11 files reviewed, all discussions resolved (waiting on @faucomte97 and @razvan-pro)

___
*[aimmo/templatetags/players_utils.py, line 17 at r4](https://reviewable.io/reviews/ocadotechnology/aimmo/1605#-MtbvFDhEs58YInn4mR3:-Mtd8fbX6fwNiCUr_6PH:b-wzncbh) ([raw file](https://github.com/ocadotechnology/aimmo/blob/1882b3e410877babf088abd4c6e0fabc4da2a34f/aimmo/templatetags/players_utils.py#L17)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

:heavy_check_mark: Approved the cleanup

We'll need some changes in portal I think, for the student dashboard, so it only fetches the non-archived game :slightly_smiling_face: 
</blockquote></details>

Yes 🙂

**Review by razvan-pro — APPROVED** [review]
> Reviewed 2 of 4 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r9, 2 of 2 files at r11, 1 of 1 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1605#-:-MtnPoP92ZHqMKizKc4R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

**Pull request merged**
