### PR TITLE
Integrate react with django

### PR DESCRIPTION
**Pull request by mrniket**
As agreed for this task, this works locally

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/507)

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[.gitignore, line 82 at r1](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/507#-L7aCgmt6YtgPVH2kwUr:-L7aCgmt6YtgPVH2kwUs:bihb0ju) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b3dcc616ef844291a31d0a83644cb08948eb7981/.gitignore#L82)):*
> ```
> # Frontend generated files
> players/static/react/
> players/templates/players/game_ide.html
> ```

Only `game_ide.html`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/507)*

**Comment by CelineBoudier** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/507)*

**Comment by mrniket** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 82 at r1](https://reviewable.io:443/reviews/ocadotechnology/aimmo/507#-L7aCgmt6YtgPVH2kwUr:-L7aHFkSsXo5_Wcii2pT:bbywkql) ([raw file](https://github.com/ocadotechnology/aimmo/blob/b3dcc616ef844291a31d0a83644cb08948eb7981/.gitignore#L82)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

Only `game_ide.html`?
</blockquote></details>

yes, this is the only file generated by `game_frontend/djangoBundler.js`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/507)*

**Comment by CelineBoudier** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ocadotechnology/aimmo/507#-:-L7dxSB6wDa5rxMMZ2n7:bnfp4nl)*

**Pull request merged**
