### PR TITLE
feat: 1752 kurono badges

### PR DESCRIPTION
**Pull request by SKairinos**
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have linked this PR to a ZenHub Issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1767)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1767)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`game_frontend/src/components/Badge/badges.js` line 37 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1767#-NVd9jiL90HyTOuLgePw:-NVd9jiL90HyTOuLgePx:bw1hyvd) ([raw file](https://github.com/ocadotechnology/aimmo/blob/73ca03b911d7ceea18739209837861feebee40b1/game_frontend/src/components/Badge/badges.js#L37)):*
> ```JavaScript
>     message: 'You picked up your first artefact!',
>     img: PickupBadge,
>     name: 'Pickup artefact'
> ```

Something about these badges isn't working right
___
*[`game_frontend/src/pyodide/badges.ts` line 34 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1767#-NVd9s-37hQIQrDCXqAU:-NVd9s-37hQIQrDCXqAV:b-km55pj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/73ca03b911d7ceea18739209837861feebee40b1/game_frontend/src/pyodide/badges.ts#L34)):*
> ```XML
>   } = await response.json();
> 
>   for (var i = 0; i < responseJson.passed.length; i++) {
> ```

can we have `let` here?
___
*[`game_frontend/src/pyodide/badges.ts` line 42 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1767#-NVdA2xIBfd-cpZcnaF0:-NVdA2xIBfd-cpZcnaF1:b-tdga5p) ([raw file](https://github.com/ocadotechnology/aimmo/blob/73ca03b911d7ceea18739209837861feebee40b1/game_frontend/src/pyodide/badges.ts#L42)):*
> ```XML
> 
>   return badges;
> }
> ```

Add a new line please

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1767)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @SKairinos)

**Review by faucomte97 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1767)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1767)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`game_frontend/src/components/Badge/badges.js` line 37 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1767#-NVd9jiL90HyTOuLgePw:-NViHqf4B5m-rLAWnhfk:boywwaq) ([raw file](https://github.com/ocadotechnology/aimmo/blob/73ca03b911d7ceea18739209837861feebee40b1/game_frontend/src/components/Badge/badges.js#L37)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Something about these badges isn't working right
</blockquote></details>

following up with Rebecca
___
*[`game_frontend/src/pyodide/badges.ts` line 34 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1767#-NVd9s-37hQIQrDCXqAU:-NViGlM16M-OHJMiJUIN:bb7f2mf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/73ca03b911d7ceea18739209837861feebee40b1/game_frontend/src/pyodide/badges.ts#L34)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

can we have `let` here?
</blockquote></details>

done
___
*[`game_frontend/src/pyodide/badges.ts` line 42 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/1767#-NVdA2xIBfd-cpZcnaF0:-NViGpG55lG8bjArBeYw:bb7f2mf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/73ca03b911d7ceea18739209837861feebee40b1/game_frontend/src/pyodide/badges.ts#L42)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Add a new line please
</blockquote></details>

done

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1767#-:-NVik2VN8hh6TtAfTJyj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 3 of 4 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
