### PR TITLE
Add only school users to game

### PR DESCRIPTION
**Pull request by riaJha97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/593)

### CODE REVIEW

**Comment by riaJha97** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD11HTNBPGDY9q7Lxml:-LD11HTNBPGDY9q7Lxmm:b-qk2xqw) (no related file):*
This pull request is only to review the code. Currently testing on dev so won't be merged just yet

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/593)*

**Comment by CelineBoudier** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[players/views.py, line 181 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD19UVy25KzHgyFX_Id:-LD19UVy25KzHgyFX_Ie:b-6w9nmf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a706f11ea55268d13ed6e1eb1b32288cf71487e8/players/views.py#L181)):*
> ```Python
>     if is_teacher:
>         classes = user.class_teacher.all()
>         print "Adding students from all of the teacher's classes"
> ```

no prints in the commit please

---

*[players/views.py, line 186 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD18yMl6jJjQYkMq_aM:-LD18yMl6jJjQYkMq_aN:b-6w9nmf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a706f11ea55268d13ed6e1eb1b32288cf71487e8/players/views.py#L186)):*
> ```Python
>     else:
>         c = user.class_field
>         print "Adding all students from the same class"
> ```

no prints in the commit please

---

*[players/views.py, line 192 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD19TXw80sWsojL4YUM:-LD19TXw80sWsojL4YUN:b-6w9nmf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a706f11ea55268d13ed6e1eb1b32288cf71487e8/players/views.py#L192)):*
> ```Python
> 
> def get_users(user):
>     print "Getting users"
> ```

no prints in the commit please

---

*[players/views.py, line 196 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD18xKN5XhQ7auNyhXx:-LD18xKN5XhQ7auNyhXy:b-6w9nmf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a706f11ea55268d13ed6e1eb1b32288cf71487e8/players/views.py#L196)):*
> ```Python
>     if hasattr(user, 'userprofile'):
>         if hasattr(user.userprofile, 'teacher') and user.userprofile.teacher.has_school():
>             print "Got here"
> ```

no prints in the commit please

---

*[players/views.py, line 201 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD19Sng187WKsuBGt8U:-LD19Sng187WKsuBGt8V:b-6w9nmf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a706f11ea55268d13ed6e1eb1b32288cf71487e8/players/views.py#L201)):*
> ```Python
>         elif hasattr(user.userprofile, 'student'):
>             if user.userprofile.student.is_independent():
>                 print "Adding all independent students"
> ```

no prints in the commit please

---

*[players/views.py, line 206 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD19SHwCzA7qqZMu-AK:-LD19SHwCzA7qqZMu-AL:b-6w9nmf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a706f11ea55268d13ed6e1eb1b32288cf71487e8/players/views.py#L206)):*
> ```Python
> 
>                 return get_students_from_class(user.userprofile.student, False)
>         print "Adding all users"
> ```

no prints in the commit please

---

*[players/views.py, line 208 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD18uO74rfD2dLmmiON:-LD18uO74rfD2dLmmiOO:b-6w9nmf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a706f11ea55268d13ed6e1eb1b32288cf71487e8/players/views.py#L208)):*
> ```Python
>         print "Adding all users"
>         return User.objects.all()
>     print "Adding all users"
> ```

no prints in the commit please

---

*[players/views.py, line 223 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD19QEZ4iMowtZzJcrn:-LD19QEZ4iMowtZzJcro:b78dmc6) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a706f11ea55268d13ed6e1eb1b32288cf71487e8/players/views.py#L223)):*
> ```Python
>             game.save()
>             users = get_users(request.user)
>             # TODO: If this does not work, use a loop
> ```

we should remove this as well

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/593)*

**Comment by OlafSzmidt** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[players/views.py, line 207 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-LD1cOkC0AtCOFvK_wYE:-LD1cOkC0AtCOFvK_wYF:b730iyq) ([raw file](https://github.com/ocadotechnology/aimmo/blob/a706f11ea55268d13ed6e1eb1b32288cf71487e8/players/views.py#L207)):*
> ```Python
>                 return get_students_from_class(user.userprofile.student, False)
>         print "Adding all users"
>         return User.objects.all()
> ```

This will be super slow. Is there any way of replacing this with something?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/593)*

**Comment by CelineBoudier** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/593)*

**Comment by CelineBoudier** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/593)*

**Comment by CelineBoudier** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/593#-:-LD36BtD45MpvzXs2idb:bnfp4nl)*

**Pull request closed without merging**
