### PR TITLE
Document createShallowWithTheme

### PR DESCRIPTION
**Pull request by mrniket**
image

This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/641)

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @mrniket)

---

*[game_frontend/src/redux/store.js, line 5 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/641#-LFr-C5oC2o75CRvn-tS:-LFr-C5oC2o75CRvn-tT:br5tlvz) ([raw file](https://github.com/ocadotechnology/aimmo/blob/c8979345fec4818fb863f862912dac7c9fde4c38/game_frontend/src/redux/store.js#L5)):*
> ```JavaScript
> import { createEpicMiddleware } from 'redux-observable'
> import api from './api'
> import { composeWithDevTools } from 'redux-devtools-extension/logOnlyInProduction'
> ```

How does this work? `logOnlyInProduction`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/641)*

**Comment by mrniket** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @mrniket)

---

*[game_frontend/src/redux/store.js, line 5 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/641#-LFr-C5oC2o75CRvn-tS:-LFr0UGO5CVY5hcPx26U:b-4nax1p) ([raw file](https://github.com/ocadotechnology/aimmo/blob/c8979345fec4818fb863f862912dac7c9fde4c38/game_frontend/src/redux/store.js#L5)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

How does this work? `logOnlyInProduction`?
</blockquote></details>

We can use redux-devtools-extension in production, but the logOnly version (a subset of the devtools package). This means the performance of the webapp isn't affected too much in production.

Here is more information on the topic: https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/641)*

**Comment by CelineBoudier** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @OlafSzmidt and @mrniket)

---

*[game_frontend/package.json, line 40 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/641#-LFr1jze9JxpLb-8gdOk:-LFr1jze9JxpLb-8gdOl:ben8pto) ([raw file](https://github.com/ocadotechnology/aimmo/blob/c8979345fec4818fb863f862912dac7c9fde4c38/game_frontend/package.json#L40)):*
> ```JSON
>     "redux": "^3.7.2",
>     "redux-observable": "^0.18.0",
>     "redux-devtools-extension": "^2.13.2",
> ```

sounds like a dev dependency? Am I missing the difference between devdependencies and dependencies?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/641)*

**Comment by mrniket** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @OlafSzmidt and @mrniket)

---

*[game_frontend/package.json, line 40 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/641#-LFr1jze9JxpLb-8gdOk:-LFr4A-k8pk0RndNPv47:b-7fahpw) ([raw file](https://github.com/ocadotechnology/aimmo/blob/c8979345fec4818fb863f862912dac7c9fde4c38/game_frontend/package.json#L40)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

sounds like a dev dependency? Am I missing the difference between devdependencies and dependencies?
</blockquote></details>

I thought so too (which it was originally there). Then the deploy build phase failed on travis since that wasn't installed. So I looked into it and it has its uses in production. Here is the article for more information: https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/641)*

**Comment by OlafSzmidt** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @CelineBoudier)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/641#-:-LFr8yP17fyVdzgTF1m6:bnfp4nl)*

**Comment by CelineBoudier** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/641#-:-LFrAvzW0KolNc0qKQ3i:bnfp4nl)*

**Pull request merged**
