### PR TITLE
Front-end layout setup

### PR DESCRIPTION
**Pull request by OlafSzmidt**
Sets up the layout for the future front-end.

Uses CSS Grid and styled components.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/523)

### CODE REVIEW

**Comment by mrniket** [comment]
Reviewed 4 of 9 files at r1, 3 of 6 files at r2, 7 of 7 files at r3, 9 of 14 files at r5, 12 of 13 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/523)*

**Comment by riaJha97** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/523#-:-L9j1Zwe9jYJnyE-Nrla:bnfp4nl)*

**Comment by CelineBoudier** [comment]
:lgtm:

---

Reviewed 2 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/523#-:-L9j5Pe85H73lY30GHpE:bnfp4nl)*

**Comment by j4mesholland** [comment]
:lgtm:

---

Reviewed 4 of 9 files at r1, 3 of 6 files at r2, 7 of 7 files at r3, 9 of 14 files at r5, 12 of 13 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/523#-:-L9jC85u4IqR32xh0Zy5:bg7igk9)*

**Comment by mrniket** [comment]
Reviewed 1 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ocadotechnology/aimmo/523)*

**Pull request merged**
