### PR TITLE
feat: Two artefacts

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 20 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480)* status: all files reviewed, 3 unresolved discussions (waiting on @razvan-pro)

___
*[aimmo-game/simulation/interactables/pickups/__init__.py, line 19 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqkIBl6Vsymc-FbA7X:-MVqkIBl6Vsymc-FbA7Y:b44hcxj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/efbe3ae4efe8a59800a6fff3c3dcad36a3b73675/aimmo-game/simulation/interactables/pickups/__init__.py#L19)):*
> ```Python
>     InvulnerabilityPickup,
>     HealthPickup,
>     Artefact,
> ```

Should we rename this to YellowOrbArtefact (or something similar) to avoid confusion in the future?
___
*[aimmo-game/simulation/interactables/pickups/artefact.py, line 6 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqkkGS73DkiqoUtfAR:-MVqkkGS73DkiqoUtfAS:bpscjrt) ([raw file](https://github.com/ocadotechnology/aimmo/blob/efbe3ae4efe8a59800a6fff3c3dcad36a3b73675/aimmo-game/simulation/interactables/pickups/artefact.py#L6)):*
> ```Python
> 
> 
> class Artefact(_Interactable):
> ```

Is this class now a Parent class for all artefacts, or does it still represent the yellow orb artefact? (or both?)
___
*[aimmo-game-creator/game_manager.py, line 304 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqlSpaCjwQ5Nltx1u_:-MVqlSpb48cO8cqbr765:bzbe37d) ([raw file](https://github.com/ocadotechnology/aimmo/blob/efbe3ae4efe8a59800a6fff3c3dcad36a3b73675/aimmo-game-creator/game_manager.py#L304)):*
> ```Python
>             },
>         )
>         if result["status"]["state"] == "UnAllocated" and retry_count < 60:
> ```

What is this for?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[aimmo-game/simulation/interactables/pickups/__init__.py, line 19 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqkIBl6Vsymc-FbA7X:-MVqpJzi8suUtkJlul26:b-qtwaow) ([raw file](https://github.com/ocadotechnology/aimmo/blob/efbe3ae4efe8a59800a6fff3c3dcad36a3b73675/aimmo-game/simulation/interactables/pickups/__init__.py#L19)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Should we rename this to YellowOrbArtefact (or something similar) to avoid confusion in the future?
</blockquote></details>

Yes, we can keep this one as a parent class and make another one for the yellow orb - I'll do that :slightly_smiling_face: 
___
*[aimmo-game/simulation/interactables/pickups/artefact.py, line 6 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqkkGS73DkiqoUtfAR:-MVqnL9K81q4SlbxJ7mo:b-a6tdic) ([raw file](https://github.com/ocadotechnology/aimmo/blob/efbe3ae4efe8a59800a6fff3c3dcad36a3b73675/aimmo-game/simulation/interactables/pickups/artefact.py#L6)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Is this class now a Parent class for all artefacts, or does it still represent the yellow orb artefact? (or both?)
</blockquote></details>

Both, but I mainly thought of it as a Parent class.
___
*[aimmo-game-creator/game_manager.py, line 304 at r2](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqlSpaCjwQ5Nltx1u_:-MVqnTao-lHAzkD9Gmnv:b-gt5a21) ([raw file](https://github.com/ocadotechnology/aimmo/blob/efbe3ae4efe8a59800a6fff3c3dcad36a3b73675/aimmo-game-creator/game_manager.py#L304)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

Ah, this will give Agones more time to start. I noticed this happening locally (it can happen in production too when deploying): sometimes the fleet will take longer to create and game-creator will fail to allocate a game - I think this may cause games to be semi-started and keep hanging indefinitely (they'll have a path in ingress, but the actual game server won't be running).

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[aimmo-game/simulation/interactables/pickups/__init__.py, line 20 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqw-WI0M6Ma63t4lK-:-MVqw-WI0M6Ma63t4lK0:bskciic) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24d33950e08fdc8c20cb59d68a03202a3783d2bb/aimmo-game/simulation/interactables/pickups/__init__.py#L20)):*
> ```Python
>     InvulnerabilityPickup,
>     HealthPickup,
>     Artefact,
> ```

Do we still need this in the end? :stuck_out_tongue:

**Comment by dionizh** [comment]
___
*[aimmo-game/simulation/interactables/pickups/__init__.py, line 20 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqw-WI0M6Ma63t4lK-:-MVuPa314jdHBczyy_QE:b-71euec) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24d33950e08fdc8c20cb59d68a03202a3783d2bb/aimmo-game/simulation/interactables/pickups/__init__.py#L20)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we still need this in the end? :stuck_out_tongue: 
</blockquote></details>

It seems an overkill to have the different types of artefacts in the individual files, as they don't have fundamental differences except for name and model. Following on Florian's comment on the other old irrelevant artefacts, should we maybe make things a lot simpler by having just a single artefact.py containing various artefacts (similar to effects.py and on the same level too without additional subfolder), then remove the irrelevant pickups?

(I saw some traces of the old pickups on the aimmo-game-worker too and was wondering what to do with them, so I might get the same comment 🙂)

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo-game/simulation/interactables/pickups/__init__.py, line 20 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqw-WI0M6Ma63t4lK-:-MVukHYL5mZCUYQN3gZV:b-m0zbhh) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24d33950e08fdc8c20cb59d68a03202a3783d2bb/aimmo-game/simulation/interactables/pickups/__init__.py#L20)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

It seems an overkill to have the different types of artefacts in the individual files, as they don't have fundamental differences except for name and model. Following on Florian's comment on the other old irrelevant artefacts, should we maybe make things a lot simpler by having just a single artefact.py containing various artefacts (similar to effects.py and on the same level too without additional subfolder), then remove the irrelevant pickups?

(I saw some traces of the old pickups on the aimmo-game-worker too and was wondering what to do with them, so I might get the same comment 🙂)

</blockquote></details>

@faucomte97 Yes, that's the base class of artefacts :slightly_smiling_face: 

I agree with you @dionizh. I considered having just an `artefacts.py` with all of them, but didn't do it in the end (I thought they're already grouped into pickups and to keep the same structure) - I'll do it now. I'm not sure about removing other pickups though - there may be too much to go around and remove all references and other things linked to them (effects for example) - we might fall into a rabbit hole of removing old code - I don't know if we want to do this now, we can probably have a separate ticket for it.

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo-game/simulation/interactables/pickups/__init__.py, line 20 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqw-WI0M6Ma63t4lK-:-MVunVldEtTk3rxfGY0R:b8tng8e) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24d33950e08fdc8c20cb59d68a03202a3783d2bb/aimmo-game/simulation/interactables/pickups/__init__.py#L20)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

@faucomte97 Yes, that's the base class of artefacts :slightly_smiling_face: 

I agree with you @dionizh. I considered having just an `artefacts.py` with all of them, but didn't do it in the end (I thought they're already grouped into pickups and to keep the same structure) - I'll do it now. I'm not sure about removing other pickups though - there may be too much to go around and remove all references and other things linked to them (effects for example) - we might fall into a rabbit hole of removing old code - I don't know if we want to do this now, we can probably have a separate ticket for it.
</blockquote></details>

Oh, I just realised, @faucomte97 if you meant in `ALL_PICKUPS`, then no, I'll remove it from here :grin:

**Comment by dionizh** [comment]
___
*[aimmo-game/simulation/interactables/pickups/__init__.py, line 20 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqw-WI0M6Ma63t4lK-:-MVuncE37RhoSYPJfWDX:b-tg1fur) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24d33950e08fdc8c20cb59d68a03202a3783d2bb/aimmo-game/simulation/interactables/pickups/__init__.py#L20)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Oh, I just realised, @faucomte97 if you meant in `ALL_PICKUPS`, then no, I'll remove it from here :grin: 
</blockquote></details>

Sounds good, I'm happy with that 🙂

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480)* status: 19 of 26 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[aimmo-game/simulation/interactables/pickups/__init__.py, line 20 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-MVqw-WI0M6Ma63t4lK-:-MVusiso6g30OswQnLE3:bb6mt9b) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24d33950e08fdc8c20cb59d68a03202a3783d2bb/aimmo-game/simulation/interactables/pickups/__init__.py#L20)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Sounds good, I'm happy with that 🙂
</blockquote></details>

:+1:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-:-MVuv0GP3pTw2P2nXSBb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by dionizh — APPROVED** [review]
It seems an overkill to have the different types of artefacts in the individual files, as they don't have fundamental differences except for name and model. Following on Florian's comment on the other old irrelevant artefacts, should we maybe make things a lot simpler by having just a single artefact.py containing various artefacts (similar to effects.py and on the same level too without additional subfolder), then remove the irrelevant pickups? 

(I saw some traces of the old pickups on the aimmo-game-worker too and was wondering what to do with them, so I might get the same comment 🙂)

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-:-MVuNUxZ5a9trmNdjCBU:b-ohf26e)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by dionizh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by dionizh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1480#-:-MVvq80X4DyKJaz7CLrA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
