### PR TITLE
ci: GitHub actions build

### PR DESCRIPTION
**Pull request by razvan-pro**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1419)

### CODE REVIEW

**Comment by razvan-pro** [comment]
TODO: remove cypress.yml workflow when PR check is changed to ci.yml

**Review by faucomte97 — APPROVED** [review]
Can we do that now?

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1419#-:-MMVJJ48-4gW7tvk3EVA:b-274hcm)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by razvan-pro — COMMENTED** [review]
We need an admin to switch the required check, but we probably need this change for django2 upgrades

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1419#-:-MMVJzdq3mCbfkT09YP0:bpazk7h)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1419)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
