### PR TITLE
Add only school users to game

### PR DESCRIPTION
**Pull request by riaJha97**
Must be merged before the pull request on portal is merged into master

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)

### CODE REVIEW

**Comment by OlafSzmidt** [comment]
Reviewed 1 of 8 files at r2, 6 of 18 files at r3, 8 of 13 files at r5, 2 of 2 files at r6.
Review status: all files reviewed, 6 unresolved discussions (waiting on @riaJha97)

---

*[aimmo_runner/minikube.py, line 83 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExy0Pk-kvNGG7OvPpY:-LExy0Pk-kvNGG7OvPpZ:b-abebd8) ([raw file](https://github.com/ocadotechnology/aimmo/blob/134ac83209b9e661b1ba3e810e1012d0b8d2a235/aimmo_runner/minikube.py#L83)):*
> ```Python
>         else:
>             run_command([minikube, 'start', '--memory=2048', '--cpus=2'])
>     except:
> ```

What's this `except` about?

---

*[players/app_settings.py, line 19 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzJ2t14QuqpuU4Wdr:-LExzJ2t14QuqpuU4Wds:b-x2bq7g) ([raw file](https://github.com/ocadotechnology/aimmo/blob/134ac83209b9e661b1ba3e810e1012d0b8d2a235/players/app_settings.py#L19)):*
> ```Python
>         func = import_string(PREVIEW_USER_AIMMO_DECORATOR)
>         return func
>     else:
> ```

Removing the else = 1 less line of code ;P

---

*[players/app_settings.py, line 15 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzm_jAUl7Cq8afgRT:-LExzm_jAUl7Cq8afgRU:bz6u7ld) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L15)):*
> ```Python
> 
> 
> def get_aimmo_preview_user_decorator():
> ```

I'm not convinced that this should be in app settings? Maybe instead of having `decorator` as part of the function name, we should be storing decorators separately from the rest of the code?

---

*[players/app_settings.py, line 23 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzpPU6wiDndIgJN5v:-LExzpPU6wiDndIgJN5w:b680w9u) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L23)):*
> ```Python
> 
> 
> def get_users_for_new_game_function(request):
> ```

Same goes for this, should this be in app settings? Same for the `function` in the name, is it needed if it goes into the right place?

---

*[players/app_settings.py, line 27 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzNcqB1EPSPI86Pb7:-LExzNcqB1EPSPI86Pb8:b-x2bq7g) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L27)):*
> ```Python
>         func = import_string(USERS_FOR_NEW_AIMMO_GAME)
>         return func(request)
>     else:
> ```

Removing the else = 1 less line of code ;P

---

*[integration_tests/tests/test_integration.py, line 48 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExwvAY8UxiaWRKZn4R:-LExyyFC7ZjnmBLV4dzu:bcn5miu) ([raw file](https://github.com/ocadotechnology/aimmo/blob/134ac83209b9e661b1ba3e810e1012d0b8d2a235/integration_tests/tests/test_integration.py#L48)):*
<details><summary><i>Previously, riaJha97 wrote…</i></summary><blockquote>

I'm not sure if it's okay to mock the client here because this is an integration test
</blockquote></details>

It's fine to mock in integration tests to isolate some functionality to one piece, so no probs

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by CelineBoudier** [comment]
Reviewed 1 of 8 files at r2, 6 of 18 files at r3, 7 of 13 files at r5, 2 of 2 files at r6.
Review status: all files reviewed, 6 unresolved discussions (waiting on @riaJha97)

---

*[aimmo_runner/minikube.py, line 83 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExy0Pk-kvNGG7OvPpY:-LEyDQaw0XFM5zBYL1bW:bsgje3l) ([raw file](https://github.com/ocadotechnology/aimmo/blob/134ac83209b9e661b1ba3e810e1012d0b8d2a235/aimmo_runner/minikube.py#L83)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

What's this `except` about?
</blockquote></details>

yes we should specify the error

---

*[players/app_settings.py, line 15 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzm_jAUl7Cq8afgRT:-LEyE5MyE2lImpjVQUd2:b32v57) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L15)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

I'm not convinced that this should be in app settings? Maybe instead of having `decorator` as part of the function name, we should be storing decorators separately from the rest of the code?
</blockquote></details>

+1

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by riaJha97** [comment]
Review status: 13 of 16 files reviewed, 5 unresolved discussions (waiting on @CelineBoudier, @OlafSzmidt, and @riaJha97)

---

*[aimmo_runner/minikube.py, line 83 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExy0Pk-kvNGG7OvPpY:-LEyaRnqAzqBc9btvgSJ:b5qlqbt) ([raw file](https://github.com/ocadotechnology/aimmo/blob/134ac83209b9e661b1ba3e810e1012d0b8d2a235/aimmo_runner/minikube.py#L83)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

yes we should specify the error
</blockquote></details>

I've removed it and it works fine, I was testing something last week

---

*[players/app_settings.py, line 19 at r5](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzJ2t14QuqpuU4Wdr:-LEya17F4xDZJZUVMd74:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/134ac83209b9e661b1ba3e810e1012d0b8d2a235/players/app_settings.py#L19)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

Removing the else = 1 less line of code ;P
</blockquote></details>

Done.

---

*[players/app_settings.py, line 15 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzm_jAUl7Cq8afgRT:-LEyVh2c5A1ds46konxO:bm6lsc5) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L15)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

+1
</blockquote></details>

I'm not too sure where it would go. In rapid router, anything that is imported from portal is stored in app_settings. I don't call this decorator using the function name, it's called using preview_user (line 29)

---

*[players/app_settings.py, line 23 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzpPU6wiDndIgJN5v:-LEya1gP5nlmJ7JfaCnl:b-joyis0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L23)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

Same goes for this, should this be in app settings? Same for the `function` in the name, is it needed if it goes into the right place?
</blockquote></details>

I've changed the function name but I've been following rapid router so I'm not sure where it should go

---

*[players/app_settings.py, line 27 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzNcqB1EPSPI86Pb7:-LEyaGhhEaqyyqyZ9e2E:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L27)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

Removing the else = 1 less line of code ;P
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by OlafSzmidt** [comment]
Reviewed 3 of 4 files at r7.
Review status: all files reviewed, 2 unresolved discussions (waiting on @OlafSzmidt)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by OlafSzmidt** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @OlafSzmidt and @riaJha97)

---

*[players/app_settings.py, line 28 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHJ6wO0NBgyA_901eX:-LFHJ6wO0NBgyA_901eY:b-5la8em) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/players/app_settings.py#L28)):*
> ```
> preview_user = get_aimmo_preview_user_decorator()
> ```

Would be good if others (@mrniket, @celineboudier) would comment on this, but what if we had a `decorators` file somewhere and instead of doing this, we would just have decorator functions imported directly from that file in places where they're being used?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by mrniket** [comment]
Reviewed 1 of 8 files at r2, 6 of 18 files at r3, 3 of 13 files at r5, 1 of 2 files at r6, 2 of 4 files at r7.
Review status: all files reviewed, 6 unresolved discussions (waiting on @OlafSzmidt and @riaJha97)

---

*[all_tests.py, line 17 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHV9-YCtSDfJ00Ep8l:-LFHV9-YCtSDfJ00Ep8m:bd72arx) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/all_tests.py#L17)):*
> ```Python
> 
> BASE_DIR = os.path.abspath(os.path.dirname(__file__))
> APPS = ('', 'aimmo-game/', 'aimmo-game-worker/', 'aimmo-game-creator/',)
> ```

interesting the trailing comma doesn't break anything!

---

*[aimmo_runner/runner.py, line 38 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHVL8p6m6SAWw3Adbd:-LFHVL8p6m6SAWw3Adbe:b-dxj2zy) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/aimmo_runner/runner.py#L38)):*
> ```Python
> def run(use_minikube, server_wait=True, capture_output=False, test_env=False):
>     logging.basicConfig()
>     if test_env:
> ```

is the test_env for local development or for testing?

---

*[players/app_settings.py, line 23 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzpPU6wiDndIgJN5v:-LFHWg0F7zr5AuZI3udz:b9pw2tj) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L23)):*
<details><summary><i>Previously, riaJha97 wrote…</i></summary><blockquote>

I've changed the function name but I've been following rapid router so I'm not sure where it should go
</blockquote></details>

either a decorators folder or maybe we can have a config file/folder somewhere. I say config because it makes it explicit that that's what this is. Then again this is the app_settings file so maybe this is the config file that rapid router chose. I guess we can just make it better organised 

(sorry internal monologue here)

---

*[players/app_settings.py, line 28 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHJ6wO0NBgyA_901eX:-LFHW4hM5peeFKKpGl3K:b-kxp6rx) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/players/app_settings.py#L28)):*
<details><summary><i>Previously, OlafSzmidt (Olaf Szmidt) wrote…</i></summary><blockquote>

> ```
> preview_user = get_aimmo_preview_user_decorator()
> ```

Would be good if others (@mrniket, @celineboudier) would comment on this, but what if we had a `decorators` file somewhere and instead of doing this, we would just have decorator functions imported directly from that file in places where they're being used?
</blockquote></details>

yeah, a decorators folder or file would work, in portal we have custom decorators too right?

---

*[players/app_settings.py, line 28 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHXXxRCWG8xA8efz4Y:-LFHXXxRCWG8xA8efz4Z:btdge2e) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/players/app_settings.py#L28)):*
> ```Python
> 
> 
> preview_user = get_aimmo_preview_user_decorator()
> ```

Might be good to rename this `preview_user_required` so it matches the convention of the `login_required` decorator?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by riaJha97** [comment]
Review status: 13 of 16 files reviewed, 6 unresolved discussions (waiting on @OlafSzmidt, @mrniket, @CelineBoudier, and @riaJha97)

---

*[all_tests.py, line 17 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHV9-YCtSDfJ00Ep8l:-LFHZ81d3ho52YKzDY10:b2ijuy0) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/all_tests.py#L17)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

interesting the trailing comma doesn't break anything!
</blockquote></details>

Shall I remove it?

---

*[aimmo_runner/runner.py, line 38 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHVL8p6m6SAWw3Adbd:-LFHZE4IAyIwF5UG0AeN:by296l) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/aimmo_runner/runner.py#L38)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

is the test_env for local development or for testing?
</blockquote></details>

test_env is for testing. The test_settings file will always be using when you're running the tests.

---

*[players/app_settings.py, line 28 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHJ6wO0NBgyA_901eX:-LFHqhF_19n3ffTmv-TN:b-bv6uvo) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/players/app_settings.py#L28)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

yeah, a decorators folder or file would work, in portal we have custom decorators too right?
</blockquote></details>

My issue with this is that this is not the actual decorator, this function is just importing the actual decorator from portal if that makes sense

---

*[players/app_settings.py, line 28 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHXXxRCWG8xA8efz4Y:-LFHrqB_2_jy4M2NizEZ:bb6un1j) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/players/app_settings.py#L28)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

Might be good to rename this `preview_user_required` so it matches the convention of the `login_required` decorator?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by CelineBoudier** [comment]
Review status: 13 of 16 files reviewed, 6 unresolved discussions (waiting on @OlafSzmidt, @mrniket, and @CelineBoudier)

---

*[all_tests.py, line 17 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHV9-YCtSDfJ00Ep8l:-LFHYC_tEnYt0bI3Cerm:bex27fx) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/all_tests.py#L17)):*
<details><summary><i>Previously, riaJha97 wrote…</i></summary><blockquote>

Shall I remove it?
</blockquote></details>

na it makes it easier to "template" i think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by mrniket** [comment]
Reviewed 1 of 13 files at r5, 5 of 5 files at r8.
Review status: all files reviewed, 3 unresolved discussions (waiting on @OlafSzmidt)

---

*[all_tests.py, line 17 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHV9-YCtSDfJ00Ep8l:-LFISW3942da1NIZmifb:bnkwoc9) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/all_tests.py#L17)):*
<details><summary><i>Previously, CelineBoudier (Celine Boudier) wrote…</i></summary><blockquote>

na it makes it easier to "template" i think?
</blockquote></details>

yeah probs :)

---

*[players/app_settings.py, line 28 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHJ6wO0NBgyA_901eX:-LFIStBp7jVMJGV2K8yl:bfxl2q1) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/players/app_settings.py#L28)):*
<details><summary><i>Previously, riaJha97 wrote…</i></summary><blockquote>

My issue with this is that this is not the actual decorator, this function is just importing the actual decorator from portal if that makes sense
</blockquote></details>

perhaps a dependencies folder or file? we don't really have a convention for this (unless we follow how rapid router is done).

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by riaJha97** [comment]
Review status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @mrniket and @OlafSzmidt)

---

*[players/app_settings.py, line 28 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHJ6wO0NBgyA_901eX:-LFIYZH4-XD95oVNP_3v:b-wy19pr) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/players/app_settings.py#L28)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

perhaps a dependencies folder or file? we don't really have a convention for this (unless we follow how rapid router is done).
</blockquote></details>

I've added comments for both functions

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by riaJha97** [comment]
Review status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @mrniket and @OlafSzmidt)

---

*[players/app_settings.py, line 15 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzm_jAUl7Cq8afgRT:-LFIa0LI20Y1x9Z8cRAk:bgqhil) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L15)):*
<details><summary><i>Previously, riaJha97 wrote…</i></summary><blockquote>

I'm not too sure where it would go. In rapid router, anything that is imported from portal is stored in app_settings. I don't call this decorator using the function name, it's called using preview_user (line 29)
</blockquote></details>

Switched to using comments

---

*[players/app_settings.py, line 23 at r6](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LExzpPU6wiDndIgJN5v:-LFIa4uuCm0jvOtpdNcI:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/22576cfa0ab73e70901d469a617d98623de0c23d/players/app_settings.py#L23)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

either a decorators folder or maybe we can have a config file/folder somewhere. I say config because it makes it explicit that that's what this is. Then again this is the app_settings file so maybe this is the config file that rapid router chose. I guess we can just make it better organised 

(sorry internal monologue here)
</blockquote></details>

Done.

---

*[players/app_settings.py, line 28 at r7](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-LFHJ6wO0NBgyA_901eX:-LFIa5Pw1S_DyAHH3haa:b-896fix) ([raw file](https://github.com/ocadotechnology/aimmo/blob/24fb51d01c7f6b4541c55ec7a92898617658cd09/players/app_settings.py#L28)):*
<details><summary><i>Previously, riaJha97 wrote…</i></summary><blockquote>

I've added comments for both functions
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by mrniket** [comment]
:lgtm:

---

Review status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @mrniket and @OlafSzmidt)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-:-LFMGMC44E1FG8s7lEva:bnfp4nl)*

**Comment by mrniket** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed, 3 unresolved discussions (waiting on @OlafSzmidt)

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622)*

**Comment by OlafSzmidt** [comment]
This will need merging in with master now after vagrant changes :lgtm_cancel: 

---

Reviewed 4 of 5 files at r8, 1 of 1 files at r9.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/622#-:-LFMJWGRAjddZeiSKv7F:b4zujpi)*

**Pull request merged**
