### PR TITLE
feat: allow inspection of artefact's type and types via the world map

### PR DESCRIPTION
**Pull request by dionizh**
These changes will allow the users to do the following:

```
            artefact = my_backpack[index]
            if artefact.type == world_state.artefact_types.KEY:
                key_count += 1
            elif artefact.type == world_state.artefact_types.CHEST:
                chest_count += 1    
```

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1494)

### CODE REVIEW

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[aimmo-game-worker/simulation/avatar_state.py, line 14 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1494#-MWeQ3Ax670eqjoPB_Kj:-MWeQ3Ax670eqjoPB_Kk:b-bg70oe) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2eec10125bc7f1a6e5e176e7127bb57d69c4a75a/aimmo-game-worker/simulation/avatar_state.py#L14)):*
> ```Python
>         namedtuple("Artefact", artefact.keys())(*artefact.values())
>         for artefact in avatar_state_json["backpack"]
>     ]
> ```

This may need a check on `backpack` key in `avatar_state_json` as I think it's not available for worksheet 1 :slightly_smiling_face:

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[aimmo-game-worker/simulation/avatar_state.py, line 14 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1494#-MWeQ3Ax670eqjoPB_Kj:-MWeUgGF0aCUcEy47c3f:b-i1cxes) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2eec10125bc7f1a6e5e176e7127bb57d69c4a75a/aimmo-game-worker/simulation/avatar_state.py#L14)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

This may need a check on `backpack` key in `avatar_state_json` as I think it's not available for worksheet 1 :slightly_smiling_face: 
</blockquote></details>

Ah yea of course!

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[aimmo-game-worker/simulation/avatar_state.py, line 14 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1494#-MWeQ3Ax670eqjoPB_Kj:-MWegFvq10SY6WiBquVF:b-7z59si) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2eec10125bc7f1a6e5e176e7127bb57d69c4a75a/aimmo-game-worker/simulation/avatar_state.py#L14)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Ah yea of course!
</blockquote></details>

I'd suggest `"backpack" in avatar_state_json`, otherwise this will be falsey even if there is a backpack but it's empty :slightly_smiling_face:

**Review by razvan-pro — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1494)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

___
*[aimmo-game-worker/simulation/avatar_state.py, line 14 at r1](https://reviewable.io/reviews/ocadotechnology/aimmo/1494#-MWeQ3Ax670eqjoPB_Kj:-MWi8T3uD8GIiGAaQLoS:b-ykrzjt) ([raw file](https://github.com/ocadotechnology/aimmo/blob/2eec10125bc7f1a6e5e176e7127bb57d69c4a75a/aimmo-game-worker/simulation/avatar_state.py#L14)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

I'd suggest `"backpack" in avatar_state_json`, otherwise this will be falsey even if there is a backpack but it's empty :slightly_smiling_face: 
</blockquote></details>

Ah, even if it's falsey when it's empty, the `"backpack"` key will still be in dict as an empty list because it copies json initially, so I'm happy with the if as it is as well :slightly_smiling_face:

**Review by razvan-pro — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[aimmo-game-worker/tests/tests_simulation/test_avatar_state.py, line 23 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1494#-MWiPlRs6R9t4k_-x2N9:-MWiPlRtB_DlDsd0Syqn:b-l52hrp) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb7652bcf5ccba0650048ab6aa2f0c1a69f5fb5e/aimmo-game-worker/tests/tests_simulation/test_avatar_state.py#L23)):*
> ```Python
>         self.assertEqual(
>             avatar_state.backpack[0].type, self.AVATAR["backpack"][0]["type"]
>         )
> ```

We're trying to move towards a `pytest` style, so mainly replacing `self.assertEqual` with normal `assert`. There are also some other things you can do (I think they're quite optional, but they look more `pytest`y :grin:): `AVATAR` can be a fixture instead and maybe you can also remove the class in that case? (you can see some examples in `aimmo-game` tests :slightly_smiling_face:)

**Review by razvan-pro — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1494)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

___
*[aimmo-game-worker/tests/tests_simulation/test_avatar_state.py, line 23 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1494#-MWiPlRs6R9t4k_-x2N9:-MWjVSPS72vYtw2zzmna:b-sgn28g) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb7652bcf5ccba0650048ab6aa2f0c1a69f5fb5e/aimmo-game-worker/tests/tests_simulation/test_avatar_state.py#L23)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

We're trying to move towards a `pytest` style, so mainly replacing `self.assertEqual` with normal `assert`. There are also some other things you can do (I think they're quite optional, but they look more `pytest`y :grin:): `AVATAR` can be a fixture instead and maybe you can also remove the class in that case? (you can see some examples in `aimmo-game` tests :slightly_smiling_face:)
</blockquote></details>

Agreed to do this later, so we can deploy the change today :+1:

**Review by dionizh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/aimmo/1494)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dionizh)

___
*[aimmo-game-worker/tests/tests_simulation/test_avatar_state.py, line 23 at r3](https://reviewable.io/reviews/ocadotechnology/aimmo/1494#-MWiPlRs6R9t4k_-x2N9:-MWjVxNL3HVm-HZieiFk:b-x0paxf) ([raw file](https://github.com/ocadotechnology/aimmo/blob/cb7652bcf5ccba0650048ab6aa2f0c1a69f5fb5e/aimmo-game-worker/tests/tests_simulation/test_avatar_state.py#L23)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Agreed to do this later, so we can deploy the change today :+1: 
</blockquote></details>

Yes :)

**Pull request merged**
