### PR TITLE
Auth tokens

### PR DESCRIPTION
**Pull request by joshuablake**
Requires #124 as that adds the models in the backend [(diff with just this pull request)](https://github.com/joshuablake/aimmo/compare/multiple_games...joshuablake:auth_tokens).

Whenever a component receives a request, the receiver should check authentication from the caller. Workers should _never_ know any other components auth token due to running user code.

Places where needs/has been implemented:
- [x] players/creator interface (needs a new auth token generated before the creator app is started).
- [x] players/game interface (game auth token).
- [x] game/worker interface (avatar auth token).

### CODE REVIEW

**Comment by joshuablake** [comment]
Not sure how we can pass in an auth token to the aimmo-game-creator app.

**Comment by CelineBoudier** [comment]
will add the token as hidden env var in Snap CI!

**Comment by joshuablake** [comment]
@CelineBoudier I think an env var CREATOR_AUTH_TOKEN with the output of `urlsafe_b64encode(urandom(16))` (or some other urlsafe string, that's just what we're currently using elsewhere) should work.

**Comment by joshuablake** [comment]
So it's now accessiable from Django (might need to be added to [app.yaml](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/master/app.yaml.tmpl#L62)?) but still not sure how to pass it into the container.

**Comment by CelineBoudier** [comment]
yup!

**Comment by CelineBoudier** [comment]
https://github.com/ocadotechnology/codeforlife-deploy-appengine/pull/12

**Comment by joshuablake** [comment]
3efee2a should have a solution

**Comment by joshuablake** [comment]
I think this is done although there might be a better method for getting the token to the creator.

**Comment by joshuablake** [comment]
Fixes #115

**Comment by CelineBoudier** [comment]
@joshuablake if you write Fixes #115 in a commit it will actually close this issue once accepted :)

**Comment by joshuablake** [comment]
Works locally minikube after cherry-picking 3ba46c9 and 5da34e3.

**Comment by mikebryant** [comment]
Derp, put the wrong issue number in, sorry

**Comment by Spycho** [comment]
@mikebryant is probably the only one that knows what this is all about!

**Comment by mikebryant** [comment]
@Spycho we should have auth on all of the comms between components
Otherwise someone's worker could conceivably send messages masquerading as other users into the game

**Comment by Spycho** [comment]
Makes sense @mikebryant, I more meant you might know how that can be done, and how far these commits get us there, and how to resolve the merge conflicts.

**Comment by OlafSzmidt** [comment]
# Closing this pull request to stale it. We will review this at a later stage and perhaps re-open it.

**Pull request closed without merging**
